[package]
name = "runtime-interfaces"
version = "1.10.0-unstable"
edition = "2024"
license = "Apache-2.0"
description = "Shared interfaces for Spice runtime data connectors and accelerators."
repository = "https://github.com/spiceai/spiceai"
publish = false

[lib]
name = "runtime_interfaces"
path = "src/lib.rs"

[dependencies]
runtime-parameters = { path = "../runtime-parameters" }
arrow-schema = { workspace = true }
datafusion = { workspace = true }
