/*
Copyright 2026 The Spice.ai OSS Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//! Top-level cross-partition commit WAL (issue #10125 §6.5).
//!
//! Each partition has its own per-partition staging WAL (see
//! [`super::staging_wal`]) that anchors single-partition crash recovery: WAL
//! file present ⇒ a per-partition append was interrupted between staging and
//! finalize. That is enough for the non-coordinated path, but the
//! cross-partition append coordinator (#10125 step 6) needs an additional
//! anchor: if the writer crashes mid-barrier with some partitions' files
//! moved and others not, we need to know *which set of partitions belongs
//! together* so recovery can either finish or roll back all of them
//! atomically.
//!
//! This module provides that anchor as a simple file at
//! `<table_root>/_partitioned_wal/<commit_uuid>.json`:
//!
//! 1. The coordinator generates a fresh `commit_id` (`UUIDv7`) and writes a
//!    [`PartitionedWal`] file *before* starting the per-partition
//!    `apply_under_barrier` loop.
//! 2. The coordinator runs the loop.
//! 3. On success, the coordinator removes the WAL file.
//!
//! A file under `_partitioned_wal/` after a process restart indicates a
//! coordinator that crashed mid-barrier; the per-partition staging WALs
//! that exist on disk correspond to partitions named in the top-level
//! record. **Today this file is a diagnostic / manual-recovery anchor**:
//! the existing per-partition `ensure_no_incomplete_write` check at table
//! open blocks subsequent writes until an operator clears the leftover
//! per-partition WALs. Wiring an automated replay-or-rollback driver into
//! `PartitionTableProvider::open` (or anywhere else upstream of those
//! checks) is a follow-up; the format and IO helpers in this module are
//! the load-bearing primitive that driver will consume.
//!
//! This module is intentionally just the format + IO primitives. Any
//! recovery logic would live where the coordinator does, because it needs
//! access to per-partition `CayenneTableProvider` handles.

use std::path::{Path, PathBuf};

use super::Result;
use crate::provider::Error;

/// Subdirectory name under a partitioned-table root that holds top-level
/// WAL files. Sits next to the per-partition data directories.
pub const PARTITIONED_WAL_DIR: &str = "_partitioned_wal";

/// On-disk record of a cross-partition commit that is in flight. Used to
/// drive recovery if the writer crashes before removing the file.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct PartitionedWal {
    /// `UUIDv7` generated by the coordinator. Used as the on-disk filename and
    /// as the linearization key for recovery (latest-by-time wins if two
    /// WALs ever exist for the same partition set).
    pub commit_id: String,
    /// Absolute path of the partitioned-table root, captured for diagnostic
    /// purposes (the file's own location is the authoritative root).
    pub table_root: String,
    /// Every partition participating in this commit.
    pub partitions: Vec<PartitionedWalEntry>,
    /// ISO-8601 timestamp when the WAL was written.
    pub created_at: String,
}

/// A single partition's reference inside a [`PartitionedWal`].
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct PartitionedWalEntry {
    /// The Cayenne catalog `table_id` for this partition (`UUIDv7`). Recovery
    /// uses this to find the partition's `CayenneTableProvider` in the
    /// already-loaded partition map.
    pub table_id: String,
    /// Absolute path of this partition's own per-partition staging WAL file,
    /// if it had one staged when the cross-partition WAL was written. May be
    /// `None` for partitions that were beyond the coordinator's prepare
    /// phase at the time of the crash.
    pub staging_wal_path: Option<String>,
}

impl PartitionedWal {
    /// Construct an in-memory record. Use [`Self::write_to`] to persist it.
    #[must_use]
    pub fn new(
        commit_id: impl Into<String>,
        table_root: impl Into<String>,
        partitions: Vec<PartitionedWalEntry>,
    ) -> Self {
        Self {
            commit_id: commit_id.into(),
            table_root: table_root.into(),
            partitions,
            created_at: chrono::Utc::now().to_rfc3339(),
        }
    }

    /// Return the on-disk path for this WAL under the given table root.
    #[must_use]
    pub fn path_under(&self, table_root: &Path) -> PathBuf {
        wal_path(table_root, &self.commit_id)
    }

    /// Serialize this record and write it to
    /// `<table_root>/_partitioned_wal/<commit_id>.json`, creating the
    /// `_partitioned_wal/` directory if needed.
    ///
    /// Fsyncs the file before returning so the WAL is durable before the
    /// coordinator starts moving any files.
    ///
    /// # Errors
    ///
    /// Returns an error if the directory cannot be created, the file cannot
    /// be written, or serialization fails.
    pub async fn write_to(&self, table_root: &Path) -> Result<PathBuf> {
        let wal_dir = table_root.join(PARTITIONED_WAL_DIR);
        tokio::fs::create_dir_all(&wal_dir).await?;

        let wal_path = wal_dir.join(format!("{}.json", self.commit_id));
        let content = serde_json::to_string_pretty(self).map_err(|e| Error::Internal {
            table: self.table_root.clone(),
            message: format!("Failed to serialize partitioned WAL: {e}"),
        })?;

        tokio::fs::write(&wal_path, content.as_bytes()).await?;

        // fsync the file so the WAL is durable before any file moves begin.
        let file = tokio::fs::File::open(&wal_path).await?;
        file.sync_all().await?;

        tracing::debug!(
            "Wrote partitioned WAL at {} for {} partition(s)",
            wal_path.display(),
            self.partitions.len(),
        );

        Ok(wal_path)
    }

    /// Remove the WAL file for the given commit id. Safe to call multiple
    /// times — a `NotFound` is treated as success.
    ///
    /// # Errors
    ///
    /// Returns an error if the file exists but cannot be removed.
    pub async fn remove(table_root: &Path, commit_id: &str) -> Result<()> {
        let path = wal_path(table_root, commit_id);
        match tokio::fs::remove_file(&path).await {
            Ok(()) => {
                tracing::debug!(
                    "Removed partitioned WAL at {} (commit {commit_id})",
                    path.display(),
                );
                Ok(())
            }
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(()),
            Err(e) => Err(Error::IoError { source: e }),
        }
    }

    /// Read every partitioned WAL file under `table_root/_partitioned_wal/`.
    ///
    /// Files that fail to parse are logged as warnings and skipped (rather
    /// than aborting recovery for the whole table). The caller decides what
    /// to do with each parsed WAL.
    ///
    /// Returns `Ok(empty)` if the WAL directory does not exist.
    ///
    /// # Errors
    ///
    /// Returns an error if the WAL directory exists but cannot be listed.
    pub async fn read_all_in(table_root: &Path) -> Result<Vec<(Self, PathBuf)>> {
        let wal_dir = table_root.join(PARTITIONED_WAL_DIR);
        let mut entries = match tokio::fs::read_dir(&wal_dir).await {
            Ok(e) => e,
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(Vec::new()),
            Err(e) => return Err(Error::IoError { source: e }),
        };

        let mut out = Vec::new();
        while let Some(entry) = entries.next_entry().await? {
            let path = entry.path();
            // Skip anything that isn't a regular file ending in `.json`.
            let is_file = entry.file_type().await?.is_file();
            let is_json = path.extension().and_then(|s| s.to_str()) == Some("json");
            if !(is_file && is_json) {
                continue;
            }

            match tokio::fs::read_to_string(&path).await {
                Ok(content) => match serde_json::from_str::<PartitionedWal>(&content) {
                    Ok(wal) => out.push((wal, path)),
                    Err(e) => {
                        tracing::warn!(
                            "Skipping unparseable partitioned WAL at {}: {e}",
                            path.display(),
                        );
                    }
                },
                Err(e) => {
                    tracing::warn!("Failed to read partitioned WAL at {}: {e}", path.display(),);
                }
            }
        }

        Ok(out)
    }
}

fn wal_path(table_root: &Path, commit_id: &str) -> PathBuf {
    table_root
        .join(PARTITIONED_WAL_DIR)
        .join(format!("{commit_id}.json"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn sample_wal() -> PartitionedWal {
        PartitionedWal::new(
            "01HX0000000000000000000000",
            "/data/table_root",
            vec![
                PartitionedWalEntry {
                    table_id: "01HY0000000000000000000001".to_string(),
                    staging_wal_path: Some("/data/p1/_staging/_wal.json".to_string()),
                },
                PartitionedWalEntry {
                    table_id: "01HY0000000000000000000002".to_string(),
                    staging_wal_path: None,
                },
            ],
        )
    }

    #[tokio::test]
    async fn write_then_read_roundtrip() {
        let tmp = TempDir::new().expect("tempdir");
        let wal = sample_wal();

        let path = wal.write_to(tmp.path()).await.expect("write");
        assert!(path.exists());
        assert_eq!(
            path,
            tmp.path()
                .join(PARTITIONED_WAL_DIR)
                .join(format!("{}.json", wal.commit_id))
        );

        let all = PartitionedWal::read_all_in(tmp.path()).await.expect("read");
        assert_eq!(all.len(), 1);
        let (parsed, parsed_path) = &all[0];
        assert_eq!(*parsed, wal);
        assert_eq!(*parsed_path, path);
    }

    #[tokio::test]
    async fn read_all_returns_empty_when_dir_absent() {
        let tmp = TempDir::new().expect("tempdir");
        // No WAL dir at all — recovery on a freshly-opened table.
        let all = PartitionedWal::read_all_in(tmp.path()).await.expect("read");
        assert!(all.is_empty());
    }

    #[tokio::test]
    async fn read_all_scans_many_wals_in_lex_order_agnostic() {
        let tmp = TempDir::new().expect("tempdir");
        let mut commits = Vec::new();
        for i in 0..5 {
            let mut w = sample_wal();
            w.commit_id = format!("01HX000000000000000000000{i}");
            w.write_to(tmp.path()).await.expect("write");
            commits.push(w.commit_id.clone());
        }
        let all = PartitionedWal::read_all_in(tmp.path()).await.expect("read");
        assert_eq!(all.len(), 5);

        // Order is filesystem-dependent — assert as a set instead.
        let mut got: Vec<_> = all.iter().map(|(w, _)| w.commit_id.clone()).collect();
        got.sort();
        let mut want = commits;
        want.sort();
        assert_eq!(got, want);
    }

    #[tokio::test]
    async fn read_all_skips_unparseable_files_with_warning() {
        let tmp = TempDir::new().expect("tempdir");
        let good = sample_wal();
        good.write_to(tmp.path()).await.expect("write good");

        // Plant a garbage file alongside the real one.
        let bad_path = tmp.path().join(PARTITIONED_WAL_DIR).join("not-a-uuid.json");
        tokio::fs::write(&bad_path, b"this is not json")
            .await
            .expect("write bad");

        let all = PartitionedWal::read_all_in(tmp.path()).await.expect("read");
        // Garbage file is skipped silently (logged as warn at runtime).
        assert_eq!(all.len(), 1);
        assert_eq!(all[0].0.commit_id, good.commit_id);
    }

    #[tokio::test]
    async fn read_all_ignores_non_json_files() {
        let tmp = TempDir::new().expect("tempdir");
        let good = sample_wal();
        good.write_to(tmp.path()).await.expect("write");

        // A stray non-json file (could be a future readme/marker; should not break recovery).
        tokio::fs::write(
            tmp.path().join(PARTITIONED_WAL_DIR).join("README.txt"),
            b"reserved for future use",
        )
        .await
        .expect("write txt");

        let all = PartitionedWal::read_all_in(tmp.path()).await.expect("read");
        assert_eq!(all.len(), 1);
        assert_eq!(all[0].0.commit_id, good.commit_id);
    }

    #[tokio::test]
    async fn remove_tolerates_not_found() {
        let tmp = TempDir::new().expect("tempdir");
        PartitionedWal::remove(tmp.path(), "01HX0000000000000000000000")
            .await
            .expect("idempotent remove on absent file");

        let wal = sample_wal();
        wal.write_to(tmp.path()).await.expect("write");

        PartitionedWal::remove(tmp.path(), &wal.commit_id)
            .await
            .expect("remove existing");
        // Second remove is a no-op.
        PartitionedWal::remove(tmp.path(), &wal.commit_id)
            .await
            .expect("idempotent");

        assert!(
            PartitionedWal::read_all_in(tmp.path())
                .await
                .expect("read after remove")
                .is_empty()
        );
    }
}
