/*
Copyright 2026 The Spice.ai OSS Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//! Top-level cross-partition commit WAL (issue #10125 §6.5).
//!
//! Each partition has its own per-partition staging WAL (see
//! [`super::staging_wal`]) that anchors single-partition crash recovery: WAL
//! file present ⇒ a per-partition append was interrupted between staging and
//! finalize. That is enough for the non-coordinated path, but the
//! cross-partition append coordinator (#10125 step 6) needs an additional
//! anchor: if the writer crashes mid-barrier with some partitions' files
//! moved and others not, we need to know *which set of partitions belongs
//! together* so recovery can either finish or roll back all of them
//! atomically.
//!
//! This module provides that anchor as a simple file at
//! `<table_root>/_partitioned_wal/<commit_uuid>.json`:
//!
//! 1. The coordinator generates a fresh `commit_id` (`UUIDv7`) and writes a
//!    [`PartitionedWal`] file *before* starting the per-partition
//!    `apply_under_barrier` loop.
//! 2. The coordinator runs the loop.
//! 3. On success, the coordinator removes the WAL file.
//!
//! A file under `_partitioned_wal/` after a process restart indicates a
//! coordinator that crashed mid-barrier; the per-partition staging WALs
//! that exist on disk correspond to partitions named in the top-level
//! record. **Today this file is a diagnostic / manual-recovery anchor**:
//! the existing per-partition `ensure_no_incomplete_write` check at table
//! open blocks subsequent writes until an operator clears the leftover
//! per-partition WALs. Wiring an automated replay-or-rollback driver into
//! `PartitionTableProvider::open` (or anywhere else upstream of those
//! checks) is a follow-up; the format and IO helpers in this module are
//! the load-bearing primitive that driver will consume.
//!
//! This module is intentionally just the format + IO primitives. Any
//! recovery logic would live where the coordinator does, because it needs
//! access to per-partition `CayenneTableProvider` handles.

use std::path::{Path, PathBuf};

use object_store::path::Path as ObjectStorePath;
use object_store::{ObjectStore, ObjectStoreExt};
use tokio::io::AsyncWriteExt;

use super::Result;
use crate::provider::Error;

/// Subdirectory name under a partitioned-table root that holds top-level
/// WAL files. Sits next to the per-partition data directories.
pub const PARTITIONED_WAL_DIR: &str = "_partitioned_wal";

/// On-disk record of a cross-partition commit that is in flight. Used to
/// drive recovery if the writer crashes before removing the file.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct PartitionedWal {
    /// `UUIDv7` generated by the coordinator. Used as the on-disk filename and
    /// as the linearization key for recovery (latest-by-time wins if two
    /// WALs ever exist for the same partition set).
    pub commit_id: String,
    /// Absolute path of the partitioned-table root, captured for diagnostic
    /// purposes (the file's own location is the authoritative root).
    pub table_root: String,
    /// Every partition participating in this commit.
    pub partitions: Vec<PartitionedWalEntry>,
    /// ISO-8601 timestamp when the WAL was written.
    pub created_at: String,
}

/// A single partition's reference inside a [`PartitionedWal`].
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct PartitionedWalEntry {
    /// The Cayenne catalog `table_id` for this partition (`UUIDv7`). Recovery
    /// uses this to find the partition's `CayenneTableProvider` in the
    /// already-loaded partition map.
    pub table_id: String,
    /// Absolute path of this partition's own per-partition staging WAL file,
    /// if it had one staged when the cross-partition WAL was written. May be
    /// `None` for partitions that were beyond the coordinator's prepare
    /// phase at the time of the crash.
    pub staging_wal_path: Option<String>,
}

impl PartitionedWal {
    /// Construct an in-memory record. Use [`Self::write_to`] to persist it.
    #[must_use]
    pub fn new(
        commit_id: impl Into<String>,
        table_root: impl Into<String>,
        partitions: Vec<PartitionedWalEntry>,
    ) -> Self {
        Self {
            commit_id: commit_id.into(),
            table_root: table_root.into(),
            partitions,
            created_at: chrono::Utc::now().to_rfc3339(),
        }
    }

    /// Ensure the `_partitioned_wal/` subdirectory exists.
    /// If we just created it, sync its parent (the table root) so the
    /// subdirectory entry itself is durable on local FS.
    ///
    /// This is required for the same reason as the parent-directory sync
    /// in `ensure_snapshot_dir_exists`: on POSIX, creating a subdirectory
    /// updates the parent's directory metadata. Without the parent sync,
    /// a crash can make the `_partitioned_wal/` directory "disappear" even
    /// though we are about to write a coordination record inside it.
    ///
    /// This is the last piece of the local-FS durability puzzle for the
    /// cross-partition coordination infrastructure (the write side of
    /// `PartitionedWal` now has the same treatment as the removal side
    /// and as all snapshot directory creation paths).
    ///
    /// Note for S3 tables: the `_partitioned_wal/` directory and the
    /// `PartitionedWal` JSON file are still local files on the writer's
    /// machine (coordination is local to the writer process). The per-
    /// partition "staging WAL" on S3 is an object in the staging prefix,
    /// and its removal is a best-effort object delete. The local FS
    /// durability fixes apply to the coordination records on the writer.
    async fn ensure_partitioned_wal_dir_and_sync_parent(
        table_root: &Path,
        wal_dir: &Path,
    ) -> Result<()> {
        match tokio::fs::create_dir(wal_dir).await {
            Ok(()) => {
                let parent = table_root.to_path_buf(); // the table root
                let table = table_root.display().to_string();

                // Sync the table root so the _partitioned_wal/ subdir entry is durable.
                tokio::task::spawn_blocking(move || std::fs::File::open(&parent)?.sync_all())
                    .await
                    .map_err(|source| Error::TaskPanicked { table, source })??;
            }
            Err(source) if source.kind() == std::io::ErrorKind::AlreadyExists => {}
            Err(source) => return Err(Error::IoError { source }),
        }

        Ok(())
    }

    /// Return the on-disk path for this WAL under the given table root.
    #[must_use]
    pub fn path_under(&self, table_root: &Path) -> PathBuf {
        wal_path(table_root, &self.commit_id)
    }

    /// Serialize this record and write it to
    /// `<table_root>/_partitioned_wal/<commit_id>.json`, creating the
    /// `_partitioned_wal/` directory if needed.
    ///
    /// Write is atomic and crash-safe:
    /// 1. Serialize to memory.
    /// 2. Write to `<commit_id>.json.tmp` and fsync the file.
    /// 3. `rename` the tmp file to the final path (atomic on POSIX local FS).
    /// 4. Fsync the parent directory so the rename itself is durable.
    ///
    /// A crash at any point either leaves no WAL (steps 1–3 incomplete) or
    /// a complete, parseable WAL — never a partial file that `read_all_in`
    /// would skip as unparseable and lose the recovery anchor for an
    /// in-flight barrier.
    ///
    /// # Errors
    ///
    /// Returns an error if the directory cannot be created, the file cannot
    /// be written, serialization fails, or the atomic rename / fsync fails.
    pub async fn write_to(&self, table_root: &Path) -> Result<PathBuf> {
        let wal_dir = table_root.join(PARTITIONED_WAL_DIR);

        // Ensure the _partitioned_wal/ subdirectory exists and, if we just
        // created it, sync its parent (the table root) so the subdirectory
        // entry itself is durable. This is the same durability requirement we
        // now enforce for new snapshot directories in ensure_snapshot_dir_exists.
        Self::ensure_partitioned_wal_dir_and_sync_parent(table_root, &wal_dir).await?;

        let wal_path = wal_dir.join(format!("{}.json", self.commit_id));
        let tmp_path = wal_dir.join(format!("{}.json.tmp", self.commit_id));

        // Compact serialization: this WAL is a machine-only coordination
        // marker written on every cross-partition commit. Pretty-printing
        // ~doubles the byte size and adds CPU time for whitespace formatting
        // — both pure overhead on the ingestion hot path. The JSON parser is
        // whitespace-tolerant, so any legacy pretty-printed WALs from older
        // builds still load correctly. Inspect with `jq` if needed.
        let content = serde_json::to_string(self).map_err(|e| Error::Internal {
            table: self.table_root.clone(),
            message: format!("Failed to serialize partitioned WAL: {e}"),
        })?;

        // Step 1: write to tmp file + fsync.
        //
        // Single open + write + fsync. The previous revision called
        // `tokio::fs::write` (open + write + drop fd) and then re-opened the
        // file to call `sync_all`, paying an extra `open(2)` per WAL write.
        // Using `OpenOptions` + `AsyncWriteExt::write_all` keeps the fd open
        // through the fsync, which is one fewer syscall per cross-partition
        // commit on the local-FS hot path.
        let mut tmp_file = tokio::fs::OpenOptions::new()
            .write(true)
            .create(true)
            .truncate(true)
            .open(&tmp_path)
            .await?;
        tmp_file.write_all(content.as_bytes()).await?;
        tmp_file.sync_all().await?;
        drop(tmp_file);

        // Step 2: atomic rename. POSIX rename within the same directory is
        // atomic and replaces any existing target. If the rename fails, do a
        // best-effort cleanup of the tmp file so we don't leave junk behind.
        if let Err(e) = tokio::fs::rename(&tmp_path, &wal_path).await {
            let _ = tokio::fs::remove_file(&tmp_path).await;
            return Err(Error::IoError { source: e });
        }

        // Step 3: fsync the parent dir so the rename is durable across a
        // power-loss restart.
        if let Ok(dir) = tokio::fs::File::open(&wal_dir).await
            && let Err(e) = dir.sync_all().await
        {
            // Directory fsync is best-effort: on some filesystems / OSes it
            // is a no-op anyway. Log the failure but don't abort — the WAL
            // file itself is already fsync'd and renamed.
            tracing::warn!(
                "Failed to fsync partitioned WAL parent dir {}: {e}",
                wal_dir.display(),
            );
        }

        tracing::debug!(
            "Wrote partitioned WAL at {} for {} partition(s)",
            wal_path.display(),
            self.partitions.len(),
        );

        Ok(wal_path)
    }

    /// S3/object-store equivalent of `write_to`.
    ///
    /// Writes the `PartitionedWal` JSON to a temporary object key first
    /// (`<prefix>/_partitioned_wal/<commit_id>.json.tmp`), then to the final
    /// key. This guarantees that any reader looking for the final key sees
    /// either a complete, previously-written document or nothing at all
    /// (never a torn/partial JSON), mirroring the local-FS tmp+rename+parent-
    /// dir-fsync pattern and the staging WAL S3 write discipline.
    ///
    /// Best-effort cleanup of the tmp object is performed after the final
    /// key is visible.
    ///
    /// # Errors
    ///
    /// Returns an error if the WAL cannot be serialized, uploaded to the
    /// temporary key, or copied to the final key. Temporary-key cleanup after
    /// publishing the final key is best-effort.
    pub async fn write_to_object_store(
        &self,
        store: &dyn ObjectStore,
        base_prefix: &ObjectStorePath,
    ) -> Result<ObjectStorePath> {
        let wal_dir = base_prefix.clone().join(PARTITIONED_WAL_DIR);
        let final_key = wal_dir.clone().join(format!("{}.json", self.commit_id));
        let tmp_key = wal_dir.join(format!("{}.json.tmp", self.commit_id));

        // Compact serialization: see comment in `write_to` for the local-FS
        // path; the S3 case has the same trade-offs plus a smaller PUT payload
        // and fewer bytes billed.
        let content = serde_json::to_string(self).map_err(|e| Error::Internal {
            table: self.table_root.clone(),
            message: format!("Failed to serialize partitioned WAL: {e}"),
        })?;

        // Phase 1: write to the tmp key (atomic for small objects on S3).
        store
            .put(&tmp_key, content.clone().into())
            .await
            .map_err(|e| Error::ObjectStore {
                operation: "write partitioned WAL (tmp)",
                table: self.table_root.clone(),
                source: e,
            })?;

        // Phase 2: publish to the final key.
        store
            .put(&final_key, content.into())
            .await
            .map_err(|e| Error::ObjectStore {
                operation: "write partitioned WAL (final)",
                table: self.table_root.clone(),
                source: e,
            })?;

        // Best-effort cleanup of the tmp object.
        let _ = store.delete(&tmp_key).await;

        tracing::debug!(
            "Wrote partitioned WAL (S3) at {} for {} partition(s)",
            final_key,
            self.partitions.len(),
        );

        Ok(final_key)
    }

    /// Remove the WAL file for the given commit id. Safe to call multiple
    /// times — a `NotFound` is treated as success.
    ///
    /// # Errors
    ///
    /// Returns an error if the file exists but cannot be removed.
    pub async fn remove(table_root: &Path, commit_id: &str) -> Result<()> {
        let path = wal_path(table_root, commit_id);
        match tokio::fs::remove_file(&path).await {
            Ok(()) => {
                tracing::debug!(
                    "Removed partitioned WAL at {} (commit {commit_id})",
                    path.display(),
                );

                // Best-effort directory sync so that the absence of the
                // cross-partition coordination marker is durable. This aligns
                // the removal of the top-level `PartitionedWal` with the
                // per-partition staging WAL removal (which now also syncs its
                // directory). A crash without this sync could leave the marker
                // visible, causing a conservative "incomplete cross-partition
                // commit" detection on the next open (safe, but noisy).
                // The actual data durability is already guaranteed by the
                // per-partition move + WAL removal steps that ran under the
                // held barrier before this call.
                let wal_dir = table_root.join(PARTITIONED_WAL_DIR);
                let wal_dir_display = wal_dir.display().to_string();
                match tokio::task::spawn_blocking(move || {
                    std::fs::File::open(&wal_dir).and_then(|f| f.sync_all())
                })
                .await
                {
                    Ok(Ok(())) => {}
                    Ok(Err(e)) => {
                        tracing::warn!(
                            "Failed to sync {} after removing PartitionedWal {} (data is safe; may see stale marker on restart): {e}",
                            wal_dir_display,
                            commit_id,
                        );
                    }
                    Err(join_err) => {
                        tracing::warn!(
                            "Join error while syncing {} after removing PartitionedWal {} (data is safe): {join_err}",
                            wal_dir_display,
                            commit_id,
                        );
                    }
                }

                Ok(())
            }
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(()),
            Err(e) => Err(Error::IoError { source: e }),
        }
    }

    /// Read every partitioned WAL file under `table_root/_partitioned_wal/`.
    ///
    /// Files that fail to parse are logged as warnings and skipped (rather
    /// than aborting recovery for the whole table). The caller decides what
    /// to do with each parsed WAL.
    ///
    /// Returns `Ok(empty)` if the WAL directory does not exist.
    ///
    /// # Errors
    ///
    /// Returns an error if the WAL directory exists but cannot be listed.
    pub async fn read_all_in(table_root: &Path) -> Result<Vec<(Self, PathBuf)>> {
        let wal_dir = table_root.join(PARTITIONED_WAL_DIR);
        let mut entries = match tokio::fs::read_dir(&wal_dir).await {
            Ok(e) => e,
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(Vec::new()),
            Err(e) => return Err(Error::IoError { source: e }),
        };

        let mut out = Vec::new();
        while let Some(entry) = entries.next_entry().await? {
            let path = entry.path();
            // Skip anything that isn't a regular file ending in `.json`.
            let is_file = entry.file_type().await?.is_file();
            let is_json = path.extension().and_then(|s| s.to_str()) == Some("json");
            if !(is_file && is_json) {
                continue;
            }

            match tokio::fs::read_to_string(&path).await {
                Ok(content) => match serde_json::from_str::<PartitionedWal>(&content) {
                    Ok(wal) => out.push((wal, path)),
                    Err(e) => {
                        tracing::warn!(
                            "Skipping unparseable partitioned WAL at {}: {e}",
                            path.display(),
                        );
                    }
                },
                Err(e) => {
                    tracing::warn!("Failed to read partitioned WAL at {}: {e}", path.display(),);
                }
            }
        }

        Ok(out)
    }
}

fn wal_path(table_root: &Path, commit_id: &str) -> PathBuf {
    table_root
        .join(PARTITIONED_WAL_DIR)
        .join(format!("{commit_id}.json"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn sample_wal() -> PartitionedWal {
        PartitionedWal::new(
            "01HX0000000000000000000000",
            "/data/table_root",
            vec![
                PartitionedWalEntry {
                    table_id: "01HY0000000000000000000001".to_string(),
                    staging_wal_path: Some(
                        "/data/p1/_staging/01HZ0000000000000000000000/_wal.json".to_string(),
                    ),
                },
                PartitionedWalEntry {
                    table_id: "01HY0000000000000000000002".to_string(),
                    staging_wal_path: None,
                },
            ],
        )
    }

    #[tokio::test]
    async fn write_then_read_roundtrip() {
        let tmp = TempDir::new().expect("tempdir");
        let wal = sample_wal();

        let path = wal.write_to(tmp.path()).await.expect("write");
        assert!(path.exists());
        assert_eq!(
            path,
            tmp.path()
                .join(PARTITIONED_WAL_DIR)
                .join(format!("{}.json", wal.commit_id))
        );

        let all = PartitionedWal::read_all_in(tmp.path()).await.expect("read");
        assert_eq!(all.len(), 1);
        let (parsed, parsed_path) = &all[0];
        assert_eq!(*parsed, wal);
        assert_eq!(*parsed_path, path);
    }

    #[tokio::test]
    async fn read_all_returns_empty_when_dir_absent() {
        let tmp = TempDir::new().expect("tempdir");
        // No WAL dir at all — recovery on a freshly-opened table.
        let all = PartitionedWal::read_all_in(tmp.path()).await.expect("read");
        assert!(all.is_empty());
    }

    #[tokio::test]
    async fn read_all_scans_many_wals_in_lex_order_agnostic() {
        let tmp = TempDir::new().expect("tempdir");
        let mut commits = Vec::new();
        for i in 0..5 {
            let mut w = sample_wal();
            w.commit_id = format!("01HX000000000000000000000{i}");
            w.write_to(tmp.path()).await.expect("write");
            commits.push(w.commit_id.clone());
        }
        let all = PartitionedWal::read_all_in(tmp.path()).await.expect("read");
        assert_eq!(all.len(), 5);

        // Order is filesystem-dependent — assert as a set instead.
        let mut got: Vec<_> = all.iter().map(|(w, _)| w.commit_id.clone()).collect();
        got.sort();
        let mut want = commits;
        want.sort();
        assert_eq!(got, want);
    }

    #[tokio::test]
    async fn read_all_skips_unparseable_files_with_warning() {
        let tmp = TempDir::new().expect("tempdir");
        let good = sample_wal();
        good.write_to(tmp.path()).await.expect("write good");

        // Plant a garbage file alongside the real one.
        let bad_path = tmp.path().join(PARTITIONED_WAL_DIR).join("not-a-uuid.json");
        tokio::fs::write(&bad_path, b"this is not json")
            .await
            .expect("write bad");

        let all = PartitionedWal::read_all_in(tmp.path()).await.expect("read");
        // Garbage file is skipped silently (logged as warn at runtime).
        assert_eq!(all.len(), 1);
        assert_eq!(all[0].0.commit_id, good.commit_id);
    }

    #[tokio::test]
    async fn read_all_ignores_non_json_files() {
        let tmp = TempDir::new().expect("tempdir");
        let good = sample_wal();
        good.write_to(tmp.path()).await.expect("write");

        // A stray non-json file (could be a future readme/marker; should not break recovery).
        tokio::fs::write(
            tmp.path().join(PARTITIONED_WAL_DIR).join("README.txt"),
            b"reserved for future use",
        )
        .await
        .expect("write txt");

        let all = PartitionedWal::read_all_in(tmp.path()).await.expect("read");
        assert_eq!(all.len(), 1);
        assert_eq!(all[0].0.commit_id, good.commit_id);
    }

    #[tokio::test]
    async fn remove_tolerates_not_found() {
        let tmp = TempDir::new().expect("tempdir");
        PartitionedWal::remove(tmp.path(), "01HX0000000000000000000000")
            .await
            .expect("idempotent remove on absent file");

        let wal = sample_wal();
        wal.write_to(tmp.path()).await.expect("write");

        PartitionedWal::remove(tmp.path(), &wal.commit_id)
            .await
            .expect("remove existing");
        // Second remove is a no-op.
        PartitionedWal::remove(tmp.path(), &wal.commit_id)
            .await
            .expect("idempotent");

        assert!(
            PartitionedWal::read_all_in(tmp.path())
                .await
                .expect("read after remove")
                .is_empty()
        );
    }

    #[tokio::test]
    async fn write_to_object_store_uses_tmp_then_final_key() {
        // S3 regression test for the tmp-object + final-key pattern on
        // the top-level cross-partition WAL (mirrors the staging WAL S3
        // discipline and the local-FS tmp+rename+parent-fsync pattern).
        use object_store::memory::InMemory;
        use object_store::path::Path as ObjectStorePath;

        let store = InMemory::new();
        let base = ObjectStorePath::from("table_root");

        let wal = sample_wal();
        let final_key = wal
            .write_to_object_store(&store, &base)
            .await
            .expect("write to InMemory (S3-like)");

        // The final key must exist and be parseable.
        let bytes = store
            .get(&final_key)
            .await
            .expect("get final key")
            .bytes()
            .await
            .expect("read final key bytes");
        let parsed: PartitionedWal = serde_json::from_slice(&bytes).expect("parse final key");
        assert_eq!(parsed.commit_id, wal.commit_id);

        // The tmp key for the same commit_id must be cleaned up after the final
        // key is published, so readers only ever see the committed WAL object.
        let tmp_key = base
            .join(PARTITIONED_WAL_DIR)
            .join(format!("{}.json.tmp", wal.commit_id));
        assert!(matches!(
            store.get(&tmp_key).await,
            Err(object_store::Error::NotFound { .. })
        ));
        store
            .get(&final_key)
            .await
            .expect("final key exists after WAL commit");
    }
}
