/*
Copyright 2026 The Spice.ai OSS Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//! Connector-owned durable write-back delivery for `PostgreSQL` (#11840).
//!
//! Delivery runs on a direct pool connection inside an explicit transaction so
//! the connector can stamp each delivery with its transaction id (`xid8`) and
//! register it before the `COMMIT`. The CDC pump later drops the echo of that
//! transaction by matching the id (a follow-up wires the pump; this module only
//! captures and persists the ids).
//!
//! The SQL is generated by the same `datafusion-table-providers` fork helpers the
//! `TableProvider` write path uses — [`InsertBuilder`] with an
//! [`OnConflict::Upsert`] target for the upsert leg, and
//! [`filters_to_sql`]/[`delete_statement`] for the absent-key delete leg — so the
//! bytes written match the path this replaces. Values are never interpolated by
//! hand.
//!
//! Ordering (see #11840): the accelerator sidecar that holds the registry and the
//! source transaction cannot commit atomically, so the xid is persisted **before**
//! the `COMMIT`. A `COMMIT` that then fails leaves a stale entry, which garbage
//! collection removes; a crash after `COMMIT` but before a late registration
//! would instead leak an unregistered echo.

use std::sync::Arc;

use arrow::array::{Array, ArrayRef};
use arrow::record_batch::RecordBatch;
use arrow_schema::SchemaRef;
use async_trait::async_trait;
use data_components::postgres_replication::XidRegistry;
use data_components::postgres_replication::slot::parse_lsn;
use data_connector_api::write_back::{DeliveryError, DeliveryResult, WriteBackDeliverer};
use datafusion::common::Constraints;
use datafusion::logical_expr::{Expr, col, lit};
use datafusion::scalar::ScalarValue;
use datafusion::sql::TableReference;
use datafusion_table_providers::sql::arrow_sql_gen::statement::{self, InsertBuilder};
use datafusion_table_providers::sql::db_connection_pool::postgrespool::PostgresConnectionPool;
use datafusion_table_providers::util::constraints::{
    UpsertOptions, validate_batch_with_constraints,
};
use datafusion_table_providers::util::dml::{delete_statement, filters_to_sql};
use datafusion_table_providers::util::on_conflict::OnConflict;
use tokio_postgres::{Client, Transaction};

/// Sidecar table, in the dataset's own accelerator, holding the serialized set of
/// outstanding write-back transaction ids. A sibling of the applied-LSN watermark
/// (`spice_sys_postgres_replication`), keyed by the same source identity.
pub(crate) const WRITE_BACK_XID_TABLE: &str = "spice_sys_postgres_write_back_xids";

/// The server version at or above which `pg_current_xact_id()` exists (PG13).
/// Below it, `txid_current()` returns the same epoch-qualified 64-bit id.
pub(crate) const PG13_SERVER_VERSION_NUM: i32 = 130_000;

/// Build the wrapped delivery error carrying an actionable message and its cause.
fn delivery_error(
    message: impl Into<String>,
    source: impl Into<Box<dyn std::error::Error + Send + Sync>>,
) -> DeliveryError {
    DeliveryError::Delivery {
        message: message.into(),
        source: source.into(),
    }
}

/// Which server function assigns and returns the delivery transaction's `xid8`.
/// Resolved once at deliverer setup from the server version, not re-decided per
/// pass.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum XidFunction {
    /// `pg_current_xact_id()` — PG13+.
    PgCurrentXactId,
    /// `txid_current()` — the PG10–12 equivalent (also epoch-qualified 64-bit).
    TxidCurrent,
}

impl XidFunction {
    /// The SQL function name to call.
    pub(crate) fn as_sql(self) -> &'static str {
        match self {
            Self::PgCurrentXactId => "pg_current_xact_id",
            Self::TxidCurrent => "txid_current",
        }
    }
}

impl From<i32> for XidFunction {
    /// `pg_current_xact_id()` is PG13+; `txid_current()` is its PG10–12
    /// equivalent.
    fn from(server_version_num: i32) -> Self {
        if server_version_num >= PG13_SERVER_VERSION_NUM {
            Self::PgCurrentXactId
        } else {
            Self::TxidCurrent
        }
    }
}

/// The upsert `INSERT ... ON CONFLICT (...) DO UPDATE` for one batch, generated by
/// the fork so values are never interpolated by hand. One statement per batch,
/// matching the fork's write path.
fn upsert_sql(
    table: &TableReference,
    batch: RecordBatch,
    on_conflict: &OnConflict,
    source_schema: &SchemaRef,
) -> statement::Result<String> {
    let batches = vec![batch];
    let sea_query_on_conflict = on_conflict.build_sea_query_on_conflict(source_schema);
    InsertBuilder::new(table, &batches).build_postgres(Some(sea_query_on_conflict))
}

/// Build `pk_col IN (values…)` from a decoded primary-key array, mirroring the
/// worker's absent-key filter so the delete SQL matches the path this replaces.
fn pk_in_filter(
    pk_col: &str,
    values: &ArrayRef,
) -> Result<Expr, Box<dyn std::error::Error + Send + Sync>> {
    let mut list: Vec<Expr> = Vec::with_capacity(values.len());
    for index in 0..values.len() {
        list.push(lit(ScalarValue::try_from_array(values.as_ref(), index)?));
    }
    Ok(col(pk_col).in_list(list, false))
}

/// Connector-owned durable write-back deliverer for a single `PostgreSQL` dataset.
///
/// Holds everything a delivery needs without another catalog round trip: the pool,
/// the target table, the source schema (for the upsert leg's conflict target and
/// for casting each accelerator batch onto it), the `ON CONFLICT` upsert target,
/// the outstanding-xid registry, and the version-gated transaction-id function.
pub(crate) struct PostgresWriteBackDeliverer {
    pool: Arc<PostgresConnectionPool>,
    table: TableReference,
    /// Source table schema, as the server reports it.
    schema: SchemaRef,
    on_conflict: OnConflict,
    /// The write path binds an empty constraint set on the source writer, so the
    /// per-batch constraint validation is a no-op here too — kept to match the
    /// path this replaces exactly.
    constraints: Constraints,
    registry: Arc<XidRegistry>,
    xid_fn: XidFunction,
}

impl std::fmt::Debug for PostgresWriteBackDeliverer {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("PostgresWriteBackDeliverer")
            .field("table", &self.table)
            .finish_non_exhaustive()
    }
}

impl PostgresWriteBackDeliverer {
    pub(crate) fn new(
        pool: Arc<PostgresConnectionPool>,
        table: TableReference,
        schema: SchemaRef,
        on_conflict: OnConflict,
        registry: Arc<XidRegistry>,
        xid_fn: XidFunction,
    ) -> Self {
        Self {
            pool,
            table,
            schema,
            on_conflict,
            constraints: Constraints::default(),
            registry,
            xid_fn,
        }
    }

    /// Assign and read the delivery transaction's `xid8` inside `tx`. Reading it
    /// through `::text` avoids needing a driver `FromSql` for the `xid8` type; the
    /// decimal value fits `u64` for both PG13+ and the PG10–12 fallback.
    async fn read_xid8(&self, tx: &Transaction<'_>) -> DeliveryResult<u64> {
        let sql = format!("SELECT {}()::text", self.xid_fn.as_sql());
        let row = tx.query_one(&sql, &[]).await.map_err(|e| {
            delivery_error(
                format!(
                    "Failed to read the delivery transaction id for durable write-back to table '{}'",
                    self.table
                ),
                e,
            )
        })?;
        let raw: String = row.get(0);
        raw.trim().parse::<u64>().map_err(|e| {
            delivery_error(
                format!(
                    "Failed to parse the delivery transaction id '{raw}' for durable write-back to table '{}'",
                    self.table
                ),
                e,
            )
        })
    }

    /// Resolve a committed / failed delivery: on an unambiguous server-side abort,
    /// unregister the entry eagerly (no echo will arrive); on an ambiguous failure
    /// (connection drop mid-`COMMIT`), leave it for startup garbage collection —
    /// the transaction may have committed, so removing it could re-admit its echo.
    /// On success, record the best-effort WAL upper bound on the same connection.
    async fn finish_commit(
        &self,
        client: &Client,
        xid8: u64,
        commit_result: Result<(), tokio_postgres::Error>,
    ) -> DeliveryResult {
        if let Err(e) = commit_result {
            // A server-reported error means the transaction definitely rolled
            // back; a transport error (no `DbError`) leaves the outcome unknown.
            if e.as_db_error().is_some() {
                self.registry.unregister(xid8).await;
                return Err(delivery_error(
                    format!(
                        "Failed to commit durable write-back to table '{}'; the source rolled the delivery back",
                        self.table
                    ),
                    e,
                ));
            }
            return Err(delivery_error(
                format!(
                    "Failed to commit durable write-back to table '{}'; the connection dropped and the delivery's outcome is unknown",
                    self.table
                ),
                e,
            ));
        }

        // Best-effort upper bound on the echo's commit LSN (for GC of a lost
        // unregister). A failure here is covered by GC, so it is logged, not
        // surfaced.
        match client
            .query_one("SELECT pg_current_wal_insert_lsn()::text", &[])
            .await
        {
            Ok(row) => {
                let raw: String = row.get(0);
                match parse_lsn(&raw) {
                    Ok(lsn) => self.registry.set_upper_bound(xid8, lsn).await,
                    Err(e) => tracing::warn!(
                        table = %self.table,
                        error = %e,
                        "durable write-back committed but the source WAL position could not be parsed, so no upper bound was recorded for change-echo cleanup; startup garbage collection still bounds the entry"
                    ),
                }
            }
            Err(e) => tracing::warn!(
                table = %self.table,
                error = %e,
                "durable write-back committed but the source WAL position could not be read, so no upper bound was recorded for change-echo cleanup; startup garbage collection still bounds the entry"
            ),
        }

        Ok(())
    }
}

#[async_trait]
impl WriteBackDeliverer for PostgresWriteBackDeliverer {
    async fn deliver_upserts(&self, rows: Vec<RecordBatch>) -> DeliveryResult {
        let mut db = self.pool.connect_direct().await.map_err(|e| {
            delivery_error(
                format!(
                    "Failed to open a connection for durable write-back to table '{}'",
                    self.table
                ),
                e,
            )
        })?;

        // One transaction covers every batch of the pass (the fork's `write_all`
        // opens one transaction for the whole upsert leg). The registration is
        // persisted before this transaction commits.
        let (xid8, commit_result) = {
            let tx = db.conn.transaction().await.map_err(|e| {
                delivery_error(
                    format!(
                        "Failed to begin the delivery transaction for durable write-back to table '{}'",
                        self.table
                    ),
                    e,
                )
            })?;

            let xid8 = self.read_xid8(&tx).await?;

            for batch in rows {
                if batch.num_rows() == 0 {
                    continue;
                }

                // Cast the accelerator's batch to the source table's own schema
                // (column order included) — a type or column difference between
                // the two is reconciled here rather than left to fail mid-delivery.
                let batch =
                    arrow_tools::record_batch::try_cast_to(batch, Arc::clone(&self.schema))
                        .map_err(|e| {
                            delivery_error(
                                format!(
                                    "Failed to cast rows to the source table's schema for durable write-back to table '{}'",
                                    self.table
                                ),
                                e,
                            )
                        })?;

                validate_batch_with_constraints(
                    vec![batch.clone()],
                    &self.constraints,
                    &UpsertOptions::default(),
                )
                .await
                .map_err(|e| {
                    delivery_error(
                        format!(
                            "Failed to validate rows for durable write-back to table '{}'",
                            self.table
                        ),
                        e,
                    )
                })?;

                let sql = upsert_sql(&self.table, batch, &self.on_conflict, &self.schema)
                    .map_err(|e| {
                        delivery_error(
                            format!(
                                "Failed to build the upsert statement for durable write-back to table '{}'",
                                self.table
                            ),
                            e,
                        )
                    })?;

                tx.execute(&sql, &[]).await.map_err(|e| {
                    delivery_error(
                        format!(
                            "Failed to upsert rows for durable write-back to table '{}'",
                            self.table
                        ),
                        e,
                    )
                })?;
            }

            // Persist the registration BEFORE issuing COMMIT (register returns only
            // once durable), so an echo arriving the instant COMMIT succeeds is
            // already suppressible. A register failure aborts the delivery: the
            // transaction is dropped (rolled back) rather than committed
            // unsuppressed.
            self.registry.register(xid8).await.map_err(|e| {
                delivery_error(
                    format!(
                        "Failed to register the delivery transaction for durable write-back to table '{}', so its change echo could not be suppressed; the delivery was aborted rather than risk re-applying it. See: https://spiceai.org/docs/components/data-connectors/postgres",
                        self.table
                    ),
                    e,
                )
            })?;

            let commit_result = tx.commit().await;
            (xid8, commit_result)
        };

        self.finish_commit(&db.conn, xid8, commit_result).await
    }

    async fn deliver_deletes(&self, keys: ArrayRef, pk_column: &str) -> DeliveryResult {
        if keys.is_empty() {
            return Ok(());
        }

        // The delete leg is its own transaction with identical xid bracketing —
        // register every xid (the fork also issues the delete in a separate source
        // transaction, so this matches current behavior).
        let mut db = self.pool.connect_direct().await.map_err(|e| {
            delivery_error(
                format!(
                    "Failed to open a connection for durable write-back delete to table '{}'",
                    self.table
                ),
                e,
            )
        })?;

        let (xid8, commit_result) = {
            let tx = db.conn.transaction().await.map_err(|e| {
                delivery_error(
                    format!(
                        "Failed to begin the delete transaction for durable write-back to table '{}'",
                        self.table
                    ),
                    e,
                )
            })?;

            let xid8 = self.read_xid8(&tx).await?;

            let filter = pk_in_filter(pk_column, &keys).map_err(|e| {
                delivery_error(
                    format!(
                        "Failed to build the delete filter for durable write-back to table '{}'",
                        self.table
                    ),
                    e,
                )
            })?;
            let where_sql = filters_to_sql(&[filter], None).map_err(|e| {
                delivery_error(
                    format!(
                        "Failed to build the delete statement for durable write-back to table '{}'",
                        self.table
                    ),
                    e,
                )
            })?;
            let sql = delete_statement(&self.table, Some(where_sql.as_str()));

            tx.execute(&sql, &[]).await.map_err(|e| {
                delivery_error(
                    format!(
                        "Failed to delete rows for durable write-back to table '{}'",
                        self.table
                    ),
                    e,
                )
            })?;

            self.registry.register(xid8).await.map_err(|e| {
                delivery_error(
                    format!(
                        "Failed to register the delete transaction for durable write-back to table '{}', so its change echo could not be suppressed; the delivery was aborted rather than risk re-applying it. See: https://spiceai.org/docs/components/data-connectors/postgres",
                        self.table
                    ),
                    e,
                )
            })?;

            let commit_result = tx.commit().await;
            (xid8, commit_result)
        };

        self.finish_commit(&db.conn, xid8, commit_result).await
    }
}

#[cfg(test)]
mod tests {
    use super::{PG13_SERVER_VERSION_NUM, XidFunction, pk_in_filter, upsert_sql};
    use arrow::array::{Int32Array, LargeStringArray, StringArray};
    use arrow::record_batch::RecordBatch;
    use arrow_schema::{DataType, Field, Schema, SchemaRef};
    use datafusion::sql::TableReference;
    use datafusion_table_providers::util::column_reference::ColumnReference;
    use datafusion_table_providers::util::on_conflict::OnConflict;
    use std::sync::Arc;

    fn source_schema() -> SchemaRef {
        Arc::new(Schema::new(vec![
            Field::new("id", DataType::Int32, false),
            Field::new("name", DataType::Utf8, true),
            Field::new("score", DataType::Int32, true),
        ]))
    }

    fn sample_batch() -> RecordBatch {
        RecordBatch::try_new(
            source_schema(),
            vec![
                Arc::new(Int32Array::from(vec![1, 2])),
                Arc::new(StringArray::from(vec![Some("a"), Some("b")])),
                Arc::new(Int32Array::from(vec![10, 20])),
            ],
        )
        .expect("sample batch builds")
    }

    #[test]
    fn version_gate_picks_pg_current_xact_id_on_pg13_plus() {
        assert_eq!(
            XidFunction::from(PG13_SERVER_VERSION_NUM),
            XidFunction::PgCurrentXactId,
            "PG13 exactly uses pg_current_xact_id()"
        );
        assert_eq!(XidFunction::from(160_000), XidFunction::PgCurrentXactId);
        assert_eq!(XidFunction::PgCurrentXactId.as_sql(), "pg_current_xact_id");
    }

    #[test]
    fn version_gate_falls_back_to_txid_current_below_pg13() {
        assert_eq!(
            XidFunction::from(PG13_SERVER_VERSION_NUM - 1),
            XidFunction::TxidCurrent,
            "PG12 and below use txid_current()"
        );
        assert_eq!(XidFunction::from(100_000), XidFunction::TxidCurrent);
        assert_eq!(XidFunction::TxidCurrent.as_sql(), "txid_current");
    }

    /// The upsert SQL must carry the `ON CONFLICT ("pk") DO UPDATE SET ...` suffix
    /// over every non-key column — the shape that makes a present-key delivery an
    /// atomic upsert rather than a delete-then-insert.
    #[test]
    fn upsert_sql_has_on_conflict_do_update_over_non_key_columns() {
        let on_conflict = OnConflict::Upsert(ColumnReference::new(vec!["id".to_string()]));
        let sql = upsert_sql(
            &TableReference::bare("orders"),
            sample_batch(),
            &on_conflict,
            &source_schema(),
        )
        .expect("upsert SQL builds");

        assert!(
            sql.contains("INSERT INTO"),
            "an insert statement is generated: {sql}"
        );
        assert!(
            sql.contains(r#"ON CONFLICT ("id") DO UPDATE SET"#),
            "conflict target is the primary key: {sql}"
        );
        assert!(
            sql.contains(r#""name" = EXCLUDED."name""#),
            "non-key column `name` is updated from the excluded row: {sql}"
        );
        assert!(
            sql.contains(r#""score" = EXCLUDED."score""#),
            "non-key column `score` is updated from the excluded row: {sql}"
        );
        assert!(
            !sql.contains(r#""id" = EXCLUDED."id""#),
            "the key column itself is not in the update set: {sql}"
        );
    }

    /// `deliver_upserts` casts each accelerator batch to the source schema via
    /// `arrow_tools::record_batch::try_cast_to` before building SQL. `PostgreSQL`
    /// treats `LargeUtf8` and `Utf8` as the same text type, so a `LargeUtf8`
    /// accelerator column must cast cleanly onto a `Utf8` source column rather
    /// than being rejected as a schema mismatch.
    #[test]
    fn large_utf8_batches_cast_cleanly_to_the_utf8_source_schema() {
        let accelerator_schema = Arc::new(Schema::new(vec![
            Field::new("id", DataType::Int32, false),
            Field::new("name", DataType::LargeUtf8, true),
        ]));
        let batch = RecordBatch::try_new(
            Arc::clone(&accelerator_schema),
            vec![
                Arc::new(Int32Array::from(vec![1, 2])),
                Arc::new(LargeStringArray::from(vec![Some("a"), Some("b")])),
            ],
        )
        .expect("accelerator batch builds");

        let source_schema: SchemaRef = Arc::new(Schema::new(vec![
            Field::new("id", DataType::Int32, false),
            Field::new("name", DataType::Utf8, true),
        ]));

        let cast = arrow_tools::record_batch::try_cast_to(batch, Arc::clone(&source_schema))
            .expect("LargeUtf8 casts onto Utf8");
        assert_eq!(cast.schema(), source_schema);
    }

    /// The delete filter renders as `pk IN (...)` over the supplied keys.
    #[test]
    fn pk_in_filter_builds_in_list_over_keys() {
        let keys: arrow::array::ArrayRef = Arc::new(Int32Array::from(vec![7, 9]));
        let expr = pk_in_filter("id", &keys).expect("filter builds");
        let rendered = format!("{expr}");
        assert!(rendered.contains("id"), "names the pk column: {rendered}");
        assert!(
            rendered.contains('7') && rendered.contains('9'),
            "lists the keys: {rendered}"
        );
    }
}
