[package]
name = "slq"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow.workspace = true
arrow_sql_gen = {path = "../crates/arrow_sql_gen"}
rusqlite.workspace = true
half = "2.4.1"
