LOAD DATA
INFILE 'lineitem.csv'
INTO TABLE TPCH_SF1.LINEITEM
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(
 L_ORDERKEY,
 L_PARTKEY,
 L_SUPPKEY,
 L_LINENUMBER,
 L_QUANTITY,
 L_EXTENDEDPRICE,
 L_DISCOUNT,
 L_TAX,
 L_RETURNFLAG,
 L_LINESTATUS,
 L_SHIPDATE      DATE "YYYY-MM-DD",
 L_COMMITDATE    DATE "YYYY-MM-DD",
 L_RECEIPTDATE   DATE "YYYY-MM-DD",
 L_SHIPINSTRUCT,
 L_SHIPMODE,
 L_COMMENT
)