LOAD DATA
INFILE 'orders.csv'
INTO TABLE TPCH_SF1.ORDERS
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(O_ORDERKEY, 
 O_CUSTKEY, 
 O_ORDERSTATUS, 
 O_TOTALPRICE, 
 O_ORDERDATE DATE "YYYY-MM-DD", 
 O_ORDERPRIORITY, 
 O_CLERK, 
 O_SHIPPRIORITY, 
 O_COMMENT)