-- Creates TPCH_SF1 schema and tables for TPC-H Benchmark Tests

SET DEFINE OFF
SET ECHO ON
SET SERVEROUTPUT ON

-- Recommended Oracle Precision and Scale:
-- - Keys, sizes, and priorities: NUMBER(10, 0)
-- - Quantities and monetary values: NUMBER(12, 2)
-- - Discounts and tax rates: NUMBER(4, 2)

-- Drop user if exists
BEGIN
  EXECUTE IMMEDIATE 'DROP USER TPCH_SF1 CASCADE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1918 THEN
      RAISE;
    END IF;
END;
/

-- Create user and grant privileges (replace placeholder with target password for the TPCH_SF1 user)
CREATE USER TPCH_SF1 IDENTIFIED BY "replace-me";
GRANT CONNECT, RESOURCE TO TPCH_SF1;
GRANT UNLIMITED TABLESPACE TO TPCH_SF1;

-- Create TPCH tables
CREATE TABLE TPCH_SF1.NATION (
    N_NATIONKEY   NUMBER(10, 0),
    N_NAME        VARCHAR2(25),
    N_REGIONKEY   NUMBER(10, 0),
    N_COMMENT     VARCHAR2(152)
);

CREATE TABLE TPCH_SF1.REGION (
    R_REGIONKEY   NUMBER(10, 0),
    R_NAME        VARCHAR2(25),
    R_COMMENT     VARCHAR2(152)
);

CREATE TABLE TPCH_SF1.PART (
    P_PARTKEY     NUMBER(10, 0),
    P_NAME        VARCHAR2(55),
    P_MFGR        VARCHAR2(25),
    P_BRAND       VARCHAR2(10),
    P_TYPE        VARCHAR2(25),
    P_SIZE        NUMBER(10, 0),
    P_CONTAINER   VARCHAR2(10),
    P_RETAILPRICE NUMBER(12, 2),
    P_COMMENT     VARCHAR2(23)
);

CREATE TABLE TPCH_SF1.SUPPLIER (
    S_SUPPKEY     NUMBER(10, 0),
    S_NAME        VARCHAR2(25),
    S_ADDRESS     VARCHAR2(40),
    S_NATIONKEY   NUMBER(10, 0),
    S_PHONE       VARCHAR2(15),
    S_ACCTBAL     NUMBER(12, 2),
    S_COMMENT     VARCHAR2(101)
);

CREATE TABLE TPCH_SF1.PARTSUPP (
    PS_PARTKEY    NUMBER(10, 0),
    PS_SUPPKEY    NUMBER(10, 0),
    PS_AVAILQTY   NUMBER(10, 0),
    PS_SUPPLYCOST NUMBER(12, 2),
    PS_COMMENT    VARCHAR2(199)
);

CREATE TABLE TPCH_SF1.CUSTOMER (
    C_CUSTKEY     NUMBER(10, 0),
    C_NAME        VARCHAR2(25),
    C_ADDRESS     VARCHAR2(40),
    C_NATIONKEY   NUMBER(10, 0),
    C_PHONE       VARCHAR2(15),
    C_ACCTBAL     NUMBER(12, 2),
    C_MKTSEGMENT  VARCHAR2(10),
    C_COMMENT     VARCHAR2(117)
);

CREATE TABLE TPCH_SF1.ORDERS (
    O_ORDERKEY      NUMBER(10, 0),
    O_CUSTKEY       NUMBER(10, 0),
    O_ORDERSTATUS   CHAR(1),
    O_TOTALPRICE    NUMBER(12, 2),
    O_ORDERDATE     DATE,
    O_ORDERPRIORITY VARCHAR2(15),
    O_CLERK         VARCHAR2(15),
    O_SHIPPRIORITY  NUMBER(10, 0),
    O_COMMENT       VARCHAR2(79)
);

CREATE TABLE TPCH_SF1.LINEITEM (
    L_ORDERKEY      NUMBER(10, 0),
    L_PARTKEY       NUMBER(10, 0),
    L_SUPPKEY       NUMBER(10, 0),
    L_LINENUMBER    NUMBER(10, 0),
    L_QUANTITY      NUMBER(12, 2),
    L_EXTENDEDPRICE NUMBER(12, 2),
    L_DISCOUNT      NUMBER(4, 2),
    L_TAX           NUMBER(4, 2),
    L_RETURNFLAG    CHAR(1),
    L_LINESTATUS    CHAR(1),
    L_SHIPDATE      DATE,
    L_COMMITDATE    DATE,
    L_RECEIPTDATE   DATE,
    L_SHIPINSTRUCT  VARCHAR2(25),
    L_SHIPMODE      VARCHAR2(10),
    L_COMMENT       VARCHAR2(44)
);