LOAD DATA
INFILE 'supplier.csv'
PRESERVE BLANKS
INTO TABLE TPCH_SF1.SUPPLIER
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(S_SUPPKEY, S_NAME, S_ADDRESS, S_NATIONKEY, S_PHONE, S_ACCTBAL, S_COMMENT)
