name: Setup spiced
description: 'composite action'

# Downloads the most recent spiced build from MinIO, within the last 10 commits
#
# Requires the MinIO CLI to be installed and configured to use this action
inputs:
  spiced_commit: # optionally override the commit to download
    description: 'spiced build commit'
    required: false
    type: string
  ref: # optionally override the branch to fetch latest 10 commits from
    description: 'target ref'
    required: false
    default: 'refs/heads/trunk'
    type: string
  with_odbc: # whether to download the ODBC-enabled binary
    description: 'download the ODBC-enabled spiced binary'
    required: false
    type: boolean
outputs:
  spiced_commit:
    value: ${{ steps.output_spiced_commit.outputs.spiced_commit }}
runs:
  using: 'composite'
  steps:
    - name: Find the latest built spiced commit
      if: ${{ !inputs.spiced_commit }}
      shell: bash
      run: |
        git fetch --depth=10 origin ${{ inputs.ref }}
        echo "Fetching latest 10 commits from ${{ inputs.ref }}"

        commit_hashes=($(git log FETCH_HEAD --pretty=format:"%H" -n 10))

        if [[ "${{ inputs.with_odbc }}" == "true" ]]; then
          features="odbc_models"
        else
          features="models"
        fi

        for hash in "${commit_hashes[@]}"; do
          echo "Checking $hash in MinIO"
          if mc stat spice-minio/artifacts/spiced/linux-x86_64/$hash/spiced_${features}_linux_x86_64.tar.gz; then
            echo "Found $hash in MinIO"
            echo "SPICED_COMMIT=$hash" >> $GITHUB_ENV
            exit 0
          fi
        done

        echo "Could not find any recently built spiced commit in MinIO"
        exit 1

    - name: Set SPICED_COMMIT from workflow input
      shell: bash
      if: ${{ inputs.spiced_commit }}
      run: |
        echo "SPICED_COMMIT=${{ inputs.spiced_commit }}" >> $GITHUB_ENV

    - name: Output SPICED_COMMIT
      id: output_spiced_commit
      shell: bash
      run: echo "SPICED_COMMIT=$SPICED_COMMIT" >> $GITHUB_OUTPUT

    - name: Download spiced from MinIO
      shell: bash
      run: |
        if [[ "${{ inputs.with_odbc }}" == "true" ]]; then
          features="odbc_models"
        else
          features="models"
        fi
        mc cp spice-minio/artifacts/spiced/linux-x86_64/$SPICED_COMMIT/spiced_${features}_linux_x86_64.tar.gz spiced_${features}_linux_x86_64.tar.gz
        tar -xzf spiced_${features}_linux_x86_64.tar.gz
        sudo cp ./spiced /usr/local/bin/spiced
