name: Sets up the Rust toolchain
description: 'composite action'
inputs:
  os:
    description: 'Operating system to set up the toolchain for'
    default: 'linux' # 'linux', 'darwin', 'windows'

runs:
  using: 'composite'
  steps:
    - name: Install Rust if not installed (Linux/macOS)
      if: inputs.os != 'windows'
      shell: bash
      run: |
        echo "${CARGO_HOME:-$HOME/.cargo}/bin" >> $GITHUB_PATH
        if [ -d $HOME/.cargo ]; then
          source $HOME/.cargo/env || true
        fi
        if ! command -v rustup &> /dev/null ; then
          curl --proto '=https' --tlsv1.2 --retry 10 --retry-connrefused -fsSL "https://sh.rustup.rs" | sh -s -- --default-toolchain none -y
          source $HOME/.cargo/env || true
        fi

    - name: Install Rust if not installed (Windows)
      if: inputs.os == 'windows'
      shell: pwsh
      run: |
        if( (-not (get-command rustup))) {
          # TODO: Install Rust on Windows
          throw "Rustup not found"
        }

    - name: Install latest Rust stable toolchain (Linux/macOS)
      if: inputs.os != 'windows'
      shell: bash
      run: |
        rustup toolchain install 1.82
        rustup default 1.82

    - name: Install latest Rust stable toolchain (Windows)
      if: inputs.os == 'windows'
      shell: pwsh
      run: |
        rustup toolchain install 1.82
        rustup default 1.82