global:
  scrape_interval: 10s
  scrape_timeout: 5s
  evaluation_interval: 10s

scrape_configs:
  - job_name: spice-cluster
    metrics_path: /
    params:
      scope:
        - cluster
    static_configs:
      - targets:
          - host.docker.internal:9090
