[package]
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license-file.workspace = true
name = "spiceschema"
publish.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
clap = { workspace = true, features = ["derive"] }
runtime = { path = "../../crates/runtime", features = [
    "openapi",
    "models",
    "mcp",
] }
serde_json.workspace = true
yaml = { path = "../../crates/yaml" }
