name: Setup testoperator
description: 'composite action'
inputs:
  query_set:
    description: 'Query set'
    required: true
    default: 'tpch'
    type: choice
    options:
      - 'tpch'
      - 'tpch[parameterized]'
      - 'tpcds'
      - 'clickbench'
      - 'bird-bench-small'

runs:
  using: 'composite'
  steps:
    - name: Prepare file-based data directory
      shell: bash
      run: |
        sudo rm -rf /opt/spiced/data
        sudo mkdir -p /opt/spiced/data
        sudo chown runner:runner -R /opt/spiced/data

    - name: Download DuckDB TPCH Data
      shell: bash
      if: (inputs.query_set == 'tpch' || inputs.query_set == 'tpch[parameterized]')
      run: |
        cd /opt/spiced/data
        mc cp spice-minio/benchmarks/tpch_sf1/tpch.db ./

    - name: Download DuckDB TPCDS Data
      shell: bash
      if: inputs.query_set == 'tpcds'
      run: |
        cd /opt/spiced/data
        mc cp spice-minio/benchmarks/tpcds_sf1/tpcds.db ./

    - name: Download File Connector TPCH Data
      shell: bash
      if: (inputs.query_set == 'tpch' || inputs.query_set == 'tpch[parameterized]')
      run: |
        cd /opt/spiced/data
        mc cp --recursive spice-minio/benchmarks/tpch_sf1/ ./

    - name: Download File Connector TPCDS Data
      shell: bash
      if: inputs.query_set == 'tpcds'
      run: |
        cd /opt/spiced/data
        mc cp --recursive spice-minio/benchmarks/tpcds_sf1/ ./
        mkdir ./sf0_01
        cd ./sf0_01
        mc cp --recursive spice-minio/benchmarks/tpcds_sf0_01/ ./

    - name: Download File Connector ClickBench Data
      shell: bash
      if: inputs.query_set == 'clickbench'
      run: |
        cd /opt/spiced/data
        mc cp spice-minio/benchmarks/clickbench/hits_0.parquet ./
        mc cp spice-minio/benchmarks/clickbench/hits.parquet ./

    - name: Checkout Bird-Bench Data
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      if: inputs.query_set == 'bird-bench-small'
      with:
        repository: spiceai/spice-bird-bench
        sparse-checkout: 'dev_20240627/'
        path: 'dev_20240627/'

    - name: Configure Bird-Bench Data
      if: inputs.query_set == 'bird-bench-small'
      shell: bash
      run: |
        ls -l $GITHUB_WORKSPACE/dev_20240627/
        ls -l $GITHUB_WORKSPACE/spice-bird-bench/
        ls -l $GITHUB_WORKSPACE/spice-bird-bench/dev_20240627/
        # Make queryset
        sudo apt install jq -y
        sudo bash -c 'jq -c ".[] | { sql: .SQL, question: .question}" spice-bird-bench/dev_20240627/dev.json > /opt/spiced/data/queryset.json'

        # Move data and spicepods appropriately
        mv spice-bird-bench/dev_20240627/ /opt/spiced/data/
        # Fix spicepod paths to be under `./data` directory.
        find /opt/spiced/data/spicepods -name "spicepod.yaml" -exec sudo sed -i 's|from: file:\./dev_databases/|from: file:./data/dev_databases/|g' {} \;
