name: Setup testoperator
description: 'composite action'
inputs:
  query_set:
    description: 'Query set'
    required: true
    default: 'tpch'
    type: choice
    options:
      - 'tpch'
      - 'tpch[parameterized]'
      - 'tpcds'
      - 'clickbench'

runs:
  using: 'composite'
  steps:
    - name: Prepare file-based data directory
      shell: bash
      run: |
        sudo rm -rf /opt/spiced/data
        sudo mkdir -p /opt/spiced/data
        sudo chown runner:runner -R /opt/spiced/data

    - name: Download DuckDB TPCH Data
      shell: bash
      if: (inputs.query_set == 'tpch' || inputs.query_set == 'tpch[parameterized]')
      run: |
        cd /opt/spiced/data
        mc cp spice-minio/benchmarks/tpch_sf1/tpch.db ./

    - name: Download DuckDB TPCDS Data
      shell: bash
      if: inputs.query_set == 'tpcds'
      run: |
        cd /opt/spiced/data
        mc cp spice-minio/benchmarks/tpcds_sf1/tpcds.db ./

    - name: Download File Connector TPCH Data
      shell: bash
      if: (inputs.query_set == 'tpch' || inputs.query_set == 'tpch[parameterized]')
      run: |
        cd /opt/spiced/data
        mc cp --recursive spice-minio/benchmarks/tpch_sf1/ ./

    - name: Download File Connector TPCDS Data
      shell: bash
      if: inputs.query_set == 'tpcds'
      run: |
        cd /opt/spiced/data
        mc cp --recursive spice-minio/benchmarks/tpcds_sf1/ ./
        mkdir ./sf0_01
        cd ./sf0_01
        mc cp --recursive spice-minio/benchmarks/tpcds_sf0_01/ ./

    - name: Download File Connector ClickBench Data
      shell: bash
      if: inputs.query_set == 'clickbench'
      run: |
        cd /opt/spiced/data
        mc cp spice-minio/benchmarks/clickbench/hits_0.parquet ./
        mc cp spice-minio/benchmarks/clickbench/hits.parquet ./
