FROM ubuntu:24.04

RUN apt-get update \
    && apt-get install --yes --no-install-recommends ca-certificates libssl3 \
    && rm -rf /var/lib/apt/lists/*

COPY .spiced-local-tmp /usr/local/bin/spiced

RUN chmod +x /usr/local/bin/spiced

EXPOSE 8090 50051

WORKDIR /app

ENTRYPOINT ["/usr/local/bin/spiced"]
