# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/common/v1/common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cproto/common/v1/common.proto\x12\x06\x63ommon\"\xf6\x02\n\x0bObservation\x12\x0c\n\x04time\x18\x01 \x01(\x03\x12\x39\n\x0bidentifiers\x18\x02 \x03(\x0b\x32$.common.Observation.IdentifiersEntry\x12;\n\x0cmeasurements\x18\x03 \x03(\x0b\x32%.common.Observation.MeasurementsEntry\x12\x37\n\ncategories\x18\x04 \x03(\x0b\x32#.common.Observation.CategoriesEntry\x12\x0c\n\x04tags\x18\x05 \x03(\t\x1a\x32\n\x10IdentifiersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\x33\n\x11MeasurementsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\x1a\x31\n\x0f\x43\x61tegoriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"Y\n\x0eInterpretation\x12\r\n\x05start\x18\x01 \x01(\x03\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x03\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0f\n\x07\x61\x63tions\x18\x04 \x03(\t\x12\x0c\n\x04tags\x18\x05 \x03(\t\"-\n\x15InterpretationIndices\x12\x14\n\x08indicies\x18\x01 \x03(\rB\x02\x10\x01\"\xd0\x01\n\x16IndexedInterpretations\x12/\n\x0finterpretations\x18\x01 \x03(\x0b\x32\x16.common.Interpretation\x12\x38\n\x05index\x18\x02 \x03(\x0b\x32).common.IndexedInterpretations.IndexEntry\x1aK\n\nIndexEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12,\n\x05value\x18\x02 \x01(\x0b\x32\x1d.common.InterpretationIndices:\x02\x38\x01\x42\x30Z.github.com/spiceai/spiceai/pkg/proto/common_pbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.common.v1.common_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z.github.com/spiceai/spiceai/pkg/proto/common_pb'
  _OBSERVATION_IDENTIFIERSENTRY._options = None
  _OBSERVATION_IDENTIFIERSENTRY._serialized_options = b'8\001'
  _OBSERVATION_MEASUREMENTSENTRY._options = None
  _OBSERVATION_MEASUREMENTSENTRY._serialized_options = b'8\001'
  _OBSERVATION_CATEGORIESENTRY._options = None
  _OBSERVATION_CATEGORIESENTRY._serialized_options = b'8\001'
  _INTERPRETATIONINDICES.fields_by_name['indicies']._options = None
  _INTERPRETATIONINDICES.fields_by_name['indicies']._serialized_options = b'\020\001'
  _INDEXEDINTERPRETATIONS_INDEXENTRY._options = None
  _INDEXEDINTERPRETATIONS_INDEXENTRY._serialized_options = b'8\001'
  _OBSERVATION._serialized_start=41
  _OBSERVATION._serialized_end=415
  _OBSERVATION_IDENTIFIERSENTRY._serialized_start=261
  _OBSERVATION_IDENTIFIERSENTRY._serialized_end=311
  _OBSERVATION_MEASUREMENTSENTRY._serialized_start=313
  _OBSERVATION_MEASUREMENTSENTRY._serialized_end=364
  _OBSERVATION_CATEGORIESENTRY._serialized_start=366
  _OBSERVATION_CATEGORIESENTRY._serialized_end=415
  _INTERPRETATION._serialized_start=417
  _INTERPRETATION._serialized_end=506
  _INTERPRETATIONINDICES._serialized_start=508
  _INTERPRETATIONINDICES._serialized_end=553
  _INDEXEDINTERPRETATIONS._serialized_start=556
  _INDEXEDINTERPRETATIONS._serialized_end=764
  _INDEXEDINTERPRETATIONS_INDEXENTRY._serialized_start=689
  _INDEXEDINTERPRETATIONS_INDEXENTRY._serialized_end=764
# @@protoc_insertion_point(module_scope)
