[package]
description = "Spice cache"
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "cache"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
ahash.workspace = true
arrow.workspace = true
async-openai.workspace = true
async-stream.workspace = true
async-trait.workspace = true
byte-unit.workspace = true
datafusion.workspace = true
fundu = { workspace = true }
futures.workspace = true
moka = { workspace = true, features = ["future"] }
parking_lot.workspace = true
pingora-lru.workspace = true
opentelemetry.workspace = true
snafu.workspace = true
spicepod = { path = "../spicepod" }
tokio.workspace = true
tracing.workspace = true
twox-hash = { workspace = true, optional = true }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports", "async_tokio"] }
rand = "0.8"
rstest = "0.25.0"
tokio = { workspace = true, features = ["rt-multi-thread"] }
twox-hash = { workspace = true }

[features]
default = []
xxhash = ["dep:twox-hash"]

[[bench]]
name = "cache_throughput"
harness = false
