use std::collections::HashMap;
use std::fs;
use std::path::Path;

fn main() {
    build_search_test_cases();
}

fn build_search_test_cases() {
    let dest_path = Path::new("tests/search/").join("generated_search_tests.rs");

    // Read YAML files to get available options
    // Generic
    let accelerations = serde_yaml::from_str::<HashMap<String, serde_yaml::Value>>(include_str!(
        "tests/search/acceleration.yaml"
    ))
    .expect("Failed to parse acceleration.yaml")
    .keys()
    .cloned()
    .collect::<Vec<String>>();
    let vector_store: Vec<String> = serde_yaml::from_str::<HashMap<String, serde_yaml::Value>>(
        include_str!("tests/search/vector_store.yaml"),
    )
    .expect("Failed to parse mega_science.yaml")
    .keys()
    .cloned()
    .collect();

    // MegaScience specific
    let column_configs: Vec<String> = serde_yaml::from_str::<HashMap<String, serde_yaml::Value>>(
        include_str!("tests/search/megascience/columns.yaml"),
    )
    .expect("Failed to parse megascience/columns.yaml")
    .keys()
    .cloned()
    .collect::<Vec<String>>();

    let search_tables: Vec<String> = serde_yaml::from_str::<HashMap<String, serde_yaml::Value>>(
        include_str!("tests/search/megascience/tables.yaml"),
    )
    .expect("Failed to parse megascience/tables.yaml")
    .keys()
    .cloned()
    .collect::<Vec<String>>();
    // panic!(
    //     r#"
    //     --- BUILDING SEARCH TEST CASES ---
    //     column_configs: {column_configs:#?}
    //     search_tables: {search_tables:#?}
    //     accelerations: {accelerations:#?}
    //     vector_store: {vector_store:#?}
    // "#
    // );

    let mut test_cases = vec![];
    for v in &vector_store {
        for a in &accelerations {
            for c in &column_configs {
                for t in &search_tables {
                    test_cases.push(format!("{a}-{v}-{t}-{c}"));
                }
            }
        }
    }
    let generated = format!(
        r"// DO NOT EDIT MANUALLY: this file is generated by `build.rs` (see `build_search_test_cases`).
generate_search_tests!([
{}
]);
",
        test_cases
            .into_iter()
            .map(|slug| format!("    \"{slug}\""))
            .collect::<Vec<_>>()
            .join(",\n")
    );
    fs::write(&dest_path, generated).unwrap_or_else(|_| {
        panic!(
            "Failed to write search test case file: '{}'",
            dest_path.display()
        )
    });

    // Tell Cargo to rerun if files change
    println!("cargo:rerun-if-changed=tests/search/acceleration.yaml");
    println!("cargo:rerun-if-changed=tests/search/vector_store.yaml");
    println!("cargo:rerun-if-changed=tests/search/generated_search_tests.rs");
    println!("cargo:rerun-if-changed=tests/search/megascience/columns.yaml");
    println!("cargo:rerun-if-changed=tests/search/megascience/tables.yaml");
    println!("cargo:rerun-if-changed=build.rs");
}
