use std::collections::HashMap;
use std::env;
use std::fs;
use std::path::Path;

fn main() {
    build_search_test_cases()
}

fn build_search_test_cases() {
    let dest_path = Path::new("tests/search/").join("generated_search_tests.rs");

    // Read YAML files to get available options
    let acceleration_yaml = include_str!("tests/search/acceleration.yaml");
    let column_configs_yaml = include_str!("tests/search/mega_science.yaml");

    let accelerations: HashMap<String, serde_yaml::Value> =
        serde_yaml::from_str(acceleration_yaml).expect("Failed to parse acceleration.yaml");
    let column_configs: HashMap<String, serde_yaml::Value> =
        serde_yaml::from_str(column_configs_yaml).expect("Failed to parse mega_science.yaml");

    // Read test patterns from file
    let patterns_file = include_str!("tests/search/test_patterns.txt");
    let patterns: Vec<(&str, &str, &str, &str)> = patterns_file
        .lines()
        .filter(|line| !line.trim().is_empty() && !line.trim().starts_with('#'))
        .map(|line| {
            let parts: Vec<&str> = line.split(',').map(|s| s.trim()).collect();
            if parts.len() != 4 {
                panic!("Invalid pattern line: '{}'. Expected format: engine,vector_engine,table_component,column_config", line);
            }
            (parts[0], parts[1], parts[2], parts[3])
        })
        .collect();

    let mut expanded = Vec::new();

    let all_accelerations = accelerations.keys().cloned().collect::<Vec<String>>();
    let all_column_configs = column_configs.keys().cloned().collect::<Vec<String>>();
    for (engine, vector_engine, table_component, column_config) in patterns {
        let engines: Vec<String> = if engine == "*" {
            all_accelerations.clone()
        } else {
            vec![engine.to_string()]
        };

        let column_configs: Vec<String> = if column_config == "*" {
            all_column_configs.clone()
        } else {
            vec![column_config.to_string()]
        };

        for e in &engines {
            for c in &column_configs {
                expanded.push(format!("{}-{}-{}-{}", e, vector_engine, table_component, c));
            }
        }
    }

    // Generate the Rust code
    let test_cases = expanded
        .iter()
        .map(|slug| format!("    \"{}\"", slug))
        .collect::<Vec<_>>()
        .join(",\n");

    let generated = format!(
        r#"// DO NOT EDIT MANUALLY: this file is generated by `build.rs` (see `build_search_test_cases`).
generate_search_tests!([
{}
]);
"#,
        test_cases
    );
    fs::write(&dest_path, generated).unwrap();

    // Tell Cargo to rerun if files change
    println!("cargo:rerun-if-changed=tests/search/acceleration.yaml");
    println!("cargo:rerun-if-changed=tests/search/mega_science.yaml");
    println!("cargo:rerun-if-changed=tests/search/test_patterns.txt");
    println!("cargo:rerun-if-changed=build.rs");
}
