use std::collections::HashMap;
use std::fs;
use std::path::Path;

fn main() {
    build_search_test_cases();
}

/// Function to programmatically generate all permutations of search test cases defined in [`crates/runtime/tests/search`].
///
/// Cannot have any dependencies on [`crates/runtime/tests/search`] since this is built prior. Although search tests allow for the arbitrary defining of new test datasets, this currently just loads [`tests/search/megascience/`].
fn build_search_test_cases() {
    println!("cargo:rerun-if-changed=build.rs");
    let dest_path = Path::new("tests/search/").join("generated_search_tests.rs");

    // Read YAML files to get available options
    // Generic
    let accelerations = parse_yaml_keys("tests/search/acceleration.yaml");
    let vector_store = parse_yaml_keys("tests/search/vector_store.yaml");

    // MegaScience specific
    let column_configs = parse_yaml_keys("tests/search/megascience/columns.yaml");
    let search_tables = parse_yaml_keys("tests/search/megascience/tables.yaml");

    let mut test_cases = vec![];
    for v in &vector_store {
        for a in &accelerations {
            for c in &column_configs {
                for t in &search_tables {
                    test_cases.push(format!("{a}-{v}-{t}-{c}"));
                }
            }
        }
    }
    test_cases.sort();
    let generated = format!(
        r"// DO NOT EDIT MANUALLY: this file is generated by `build.rs` (see `build_search_test_cases`).
generate_search_tests!([
{}
]);
",
        test_cases
            .into_iter()
            .map(|slug| format!("    \"{slug}\""))
            .collect::<Vec<_>>()
            .join(",\n")
    );
    fs::write(&dest_path, generated).unwrap_or_else(|_| {
        panic!(
            "Failed to write search test case file: '{}'",
            dest_path.display()
        )
    });
    println!("cargo:rerun-if-changed=tests/search/generated_search_tests.rs");
}

/// Return the YAML keys at the first level of depth.
///
/// Also adds a `cargo:rerun-if-changed=` directive for the given file path.
///
/// Panics if the file cannot be opened or parsed.
fn parse_yaml_keys(s: &str) -> Vec<String> {
    let v = serde_yaml::from_reader::<_, HashMap<String, serde_yaml::Value>>(
        fs::File::open(s).unwrap_or_else(|_| panic!("Failed to open YAML file {s}.")),
    )
    .unwrap_or_else(|_| panic!("Failed to parse YAML file {s}"))
    .keys()
    .cloned()
    .collect::<Vec<String>>();
    println!("cargo:rerun-if-changed={s}");
    v
}
