[package]
name = "distributed"
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
ansi_colors = { path = "../../crates/ansi_colors" }
anyhow.workspace = true
chrono = { version = "0.4", features = ["serde"] }
clap = { workspace = true, features = ["derive"] }
dirs = "6.0.0"
reqwest = { version = "0.12", features = ["json"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
sysinfo = "0.33"
tokio = { workspace = true, features = ["full"] }

[target.'cfg(unix)'.dependencies]
nix = { version = "0.29", features = ["signal"] }

[dev-dependencies]
tempfile = "3.8"
