[package]
name = "distributed"
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license-file.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
ansi_colors = { path = "../../crates/ansi_colors" }
anyhow.workspace = true
chrono = { workspace = true, features = ["serde"] }
clap = { workspace = true, features = ["derive"] }
dirs = "6.0.0"
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
sysinfo.workspace = true
tokio = { workspace = true, features = ["full"] }

[target.'cfg(unix)'.dependencies]
nix = { workspace = true, features = ["signal"] }

[dev-dependencies]
tempfile.workspace = true
