[package]
name = "arrow_sql_gen"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing.workspace = true
arrow.workspace = true
sea-query = {version = "0.30.7" , features = ["with-rust_decimal", "with-bigdecimal", "with-time"]}
rust_decimal = "1.34.3"
snafu.workspace = true
postgres = {version = "0.19.7", features = ["with-chrono-0_4"]}
bigdecimal = "0.3.0"
time = "0.3.34"