[package]
name = "arrow_sql_gen"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing.workspace = true
arrow.workspace = true
sea-query = {version = "0.30.7" , features = ["backend-sqlite", "backend-postgres", "postgres-array", "with-rust_decimal", "with-bigdecimal", "with-time"]}
snafu.workspace = true
tokio-postgres = {version = "0.7.10", features = ["with-chrono-0_4"]}
bigdecimal_0_3_0 = { package = "bigdecimal", version = "0.3.0"}
time = "0.3.34"
bigdecimal = "0.4.3"
tokio.workspace = true
rusqlite.workspace = true
chrono = "0.4.35"
