[package]
name = "arrow_sql_gen"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing.workspace = true
arrow.workspace = true
sea-query = "0.30.7"
arrow-flight.workspace = true
arrow-ipc = "49.0.0"
arrow-json = "49.0.0"
postgres = "0.19.7"
tokio-postgres = "0.7.10"
arrow-schema = "50.0.0"
datafusion.workspace = true
tokio.workspace = true
snafu.workspace = true
postgres-types = "0.2.6"
