---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "spiceai.labels" . | indent 4 }}
    app: {{ .Release.Name }}
  name: {{ template "spiceai.fullname" .  }}
  namespace: {{ template "spiceai.namespace" . }}
  {{- if .Values.service.additionalAnnotations }}
  annotations:
  {{- .Values.service.additionalAnnotations | toYaml | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.service.type }}
  type: {{ .Values.service.type }}
  {{- end }}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{ toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  ports:
    {{- if .Values.service.ports }}
    {{- toYaml .Values.service.ports | nindent 4 }}
    {{- else }}
    - port: 8090
      name: http
    - port: 9090
      name: metrics
    - port: 50051
      name: flight
    - port: 50052
      name: otel
    {{- end }}
  selector:
    {{- if .Values.service.selector }}
    {{- toYaml .Values.service.selector | nindent 4 }}
    {{- else }}
    {{- include "spiceai.labels" . | indent 4 }}
    app: {{ .Release.Name }}
    {{- end }}