name: 'Add benchmark snapshots to PR'
description: 'Commits and pushes any updated benchmark snapshots to the current branch.'
inputs:
  token:
    description: 'GitHub token with permissions to push to the repository'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install GH CLI if not installed
      shell: bash
      run: |
        if ! command -v gh &> /dev/null; then
          (type -p wget >/dev/null || (sudo apt update && sudo apt install wget -y)) \
            && sudo mkdir -p -m 755 /etc/apt/keyrings \
            && out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
            && cat $out | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
            && sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
            && sudo mkdir -p -m 755 /etc/apt/sources.list.d \
            && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
            && sudo apt update \
            && sudo apt install gh -y
        else
          echo "GH CLI is already installed"
        fi
    - name: Upload benchmark snapshots to branch
      shell: bash
      run: |
        BRANCH_ID=${{ github.run_id }}
        BRANCH_NAME="snapshot-update/${BRANCH_ID}"

        git config --global user.name 'Spice Snapshot Update Bot'
        git config --global user.email 'spiceaibot@spice.ai'
        git checkout -b ${BRANCH_NAME}
        git add '*.snap'
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "fix: Update the test snapshots"
          if git ls-remote --exit-code --heads origin ${BRANCH_NAME}; then
            git pull --rebase origin ${BRANCH_NAME}
          fi
          git push origin ${BRANCH_NAME}

          PR_URL="$(gh pr list --head "${BRANCH_NAME}" --state open --json url --jq .[].url)"
          if [[ -n "${PR_URL}" ]]; then
            echo "PR already exists -> ${PR_URL}"
            exit 0
          else
            gh pr create --title "fix: Update test snapshots" --body "Updates some test snapshots" --base trunk --head ${BRANCH_NAME} --label kind/bug
          fi
        fi
      env:
        GH_TOKEN: ${{ inputs.token }}