[package]
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license-file.workspace = true
name = "token_provider"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
chrono.workspace = true
jsonwebtoken = { version = "10.3.0", features = ["aws_lc_rs"] }
reqwest = { workspace = true, features = ["form"] }
secrecy = { workspace = true, features = ["serde"] }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
snafu.workspace = true
tokio.workspace = true
tracing.workspace = true
util = { path = "../util" }

[dev-dependencies]
base64.workspace = true
tokio = { workspace = true, features = ["net"] }

[lints]
workspace = true
