[package]
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license-file.workspace = true
name = "util"
publish.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
arrow.workspace = true
arrow-schema.workspace = true
backoff = { version = "0.4.0", features = ["futures", "tokio"] }
chrono.workspace = true
ctrlc = "3.5"
datafusion = { workspace = true, optional = true }
futures.workspace = true
http-body = { version = "1.0.1", optional = true }
humantime.workspace = true
parking_lot.workspace = true
pin-project = { workspace = true, optional = true }
rand.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["sync", "time"] }
tokio-util = { workspace = true, optional = true }
tracing = { workspace = true }
tracing-subscriber.workspace = true

[features]
datafusion = ["dep:datafusion"]
default = ["datafusion"]
http = ["dep:http-body", "dep:pin-project", "dep:tokio-util"]
