[package]
description = "Delta Lake data connector for Spice.ai runtime"
edition.workspace = true
license-file.workspace = true
name = "connector-delta-lake"
publish.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
async-trait.workspace = true
aws-sdk-credential-bridge = { path = "../../aws-sdk-credential-bridge" }
data_components = { path = "../../data_components", features = ["delta_lake"] }
datafusion.workspace = true
linkme.workspace = true
paste.workspace = true
runtime = { path = "../../runtime" }
secrecy.workspace = true
snafu.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true
