/*
Copyright 2026 The Spice.ai OSS Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

use std::path::PathBuf;

use clap::Parser;
use test_framework::anyhow;

use super::CommonArgs;
use crate::commands::streaming::querysets::QuerySetType;

/// Arguments for `DynamoDB` streaming ingestion benchmarks (single config).
///
/// This command runs a benchmark from an existing snapshot created by `dispatch-dynamodb`:
/// 1. Starts Spice from snapshot
/// 2. Inserts marker records
/// 3. Waits for markers to be ingested
/// 4. Reports results with telemetry
///
/// **Prerequisites:** Run `dispatch-dynamodb` first to create tables, insert data,
/// and capture snapshots. Use the same `--run-id` that was generated by dispatch.
///
/// ## Environment Variables
///
/// ### AWS `DynamoDB`
/// - `DYNAMODB_AWS_REGION`: AWS region (required)
/// - `DYNAMODB_AWS_ACCESS_KEY_ID`: AWS access key ID (required)
/// - `DYNAMODB_AWS_SECRET_ACCESS_KEY`: AWS secret access key (required)
/// - `DYNAMODB_AWS_ENDPOINT_URL`: Custom endpoint URL (optional, for `LocalStack`)
///
/// ### Snapshot Storage (required)
/// - `SNAPSHOT_S3_LOCATION`: S3 location for snapshots (e.g., `s3://bucket/snapshots/`)
/// - `SNAPSHOT_S3_ACCESS_KEY_ID`: S3 access key ID (optional)
/// - `SNAPSHOT_S3_SECRET_ACCESS_KEY`: S3 secret access key (optional)
/// - `SNAPSHOT_S3_REGION`: S3 region (optional)
#[derive(Parser, Debug, Clone)]
pub struct StreamingDynamodbTestArgs {
    /// Common arguments (spicepod path, spiced path, metrics, etc.)
    #[command(flatten)]
    pub common: CommonArgs,

    /// Query set type (e.g., tpch-lineitem). Determines which datasets to load.
    #[arg(long, value_enum)]
    pub queryset: QuerySetType,

    /// Scale factor for data generation (e.g., 0.01, 0.1, 1.0)
    #[arg(long, default_value = "1")]
    pub scale_factor: f64,

    /// Enable health monitoring during ingestion (tracks latency and failures)
    #[arg(long)]
    pub enable_liveness: bool,

    /// Run TPCH queries to verify data integrity after ingestion
    #[arg(long)]
    pub verify: bool,

    /// Enable query liveness monitoring (runs COUNT(*) queries and tracks latency)
    #[arg(long)]
    pub enable_query_liveness: bool,

    /// Poll interval for query liveness checks in milliseconds
    #[arg(long, default_value = "500")]
    pub query_liveness_interval_ms: u64,

    /// Run ID that identifies the `DynamoDB` tables and snapshot location
    /// created by a previous dispatch-dynamodb run. Required.
    #[arg(long)]
    pub run_id: String,
}

/// Arguments for `DynamoDB` streaming dispatch (multi-config benchmarks).
///
/// This command ingests data once and runs multiple benchmark configurations:
/// 1. Creates tables and inserts initial data
/// 2. Captures checkpoint snapshots for ALL configs (sequential)
/// 3. Inserts remaining data
/// 4. Runs benchmark for EACH config from its snapshot (sequential)
/// 5. Reports comparison results
///
/// This is more cost-effective than running separate `streaming-dynamodb`
/// commands when comparing multiple acceleration configurations.
///
/// ## Environment Variables
///
/// ### AWS `DynamoDB`
/// - `DYNAMODB_AWS_REGION`: AWS region (required)
/// - `DYNAMODB_AWS_ACCESS_KEY_ID`: AWS access key ID (required)
/// - `DYNAMODB_AWS_SECRET_ACCESS_KEY`: AWS secret access key (required)
/// - `DYNAMODB_AWS_ENDPOINT_URL`: Custom endpoint URL (optional, for `LocalStack`)
///
/// ### Snapshot Storage (required)
/// - `SNAPSHOT_S3_LOCATION`: S3 location for snapshots (e.g., `s3://bucket/snapshots/`)
/// - `SNAPSHOT_S3_ACCESS_KEY_ID`: S3 access key ID (optional)
/// - `SNAPSHOT_S3_SECRET_ACCESS_KEY`: S3 secret access key (optional)
/// - `SNAPSHOT_S3_REGION`: S3 region (optional)
#[derive(Parser, Debug, Clone)]
#[expect(clippy::struct_excessive_bools)]
pub struct StreamingDynamodbDispatchArgs {
    /// Directory containing spicepod YAML files to benchmark.
    /// All .yaml and .yml files in this directory will be discovered and processed.
    #[arg(short('p'), long)]
    pub path: PathBuf,

    /// Path to the spiced binary
    #[arg(short, long, default_value = "spiced")]
    pub spiced_path: String,

    /// The number of seconds to wait for the spiced instance to become ready
    #[arg(long, default_value = "30")]
    pub ready_wait: u64,

    /// An optional data directory, to symlink into the spiced instance
    #[arg(short, long)]
    pub data_dir: Option<PathBuf>,

    /// Query set type (e.g., tpch-lineitem). Determines which datasets to load.
    #[arg(long, value_enum)]
    pub queryset: QuerySetType,

    /// Scale factor for data generation (e.g., 0.01, 0.1, 1.0)
    #[arg(long, default_value = "0.01")]
    pub scale_factor: f64,

    /// Enable health monitoring during ingestion (tracks latency and failures)
    #[arg(long)]
    pub enable_liveness: bool,

    /// Run TPCH queries to verify data integrity after ingestion
    #[arg(long)]
    pub verify: bool,

    // Query liveness monitoring arguments
    /// Enable query liveness monitoring (runs COUNT(*) queries and tracks latency)
    #[arg(long)]
    pub enable_query_liveness: bool,

    /// Poll interval for query liveness checks in milliseconds
    #[arg(long, default_value = "500")]
    pub query_liveness_interval_ms: u64,

    // Mutation testing arguments (for CDC testing)
    /// Ratio of rows to mutate (0.0-1.0). When > 0, selected rows are split 50/50:
    /// - Half go through: INSERT (wrong) → UPDATE (correct)
    /// - Half go through: INSERT (wrong) → DELETE → INSERT (correct)
    ///
    /// Remaining rows are inserted directly with final values.
    #[arg(long, default_value = "0.0")]
    pub mutation_ratio: f64,

    /// Random seed for reproducible mutation row selection
    #[arg(long, default_value = "42")]
    pub mutation_seed: u64,

    /// Number of records to insert per dataset before capturing checkpoint snapshots.
    /// These records allow Spice to infer schema before the main data insertion.
    #[arg(long, default_value = "10")]
    pub checkpoint_records: usize,

    // GitHub workflow dispatch arguments
    /// GitHub workflow file name (e.g., "streaming-benchmark.yml").
    /// If set, dispatch will trigger GitHub workflows instead of running benchmarks locally.
    #[arg(long)]
    pub workflow: Option<String>,

    /// GitHub repository (e.g., "spiceai/spiceai"). Defaults to current repository.
    #[arg(long)]
    pub repo: Option<String>,

    /// Git ref to run workflow on. Defaults to current branch.
    #[arg(long, name = "ref")]
    pub git_ref: Option<String>,

    /// Wait for each workflow to complete before starting the next.
    /// If false, workflows are dispatched sequentially but without waiting for completion.
    #[arg(long)]
    pub wait_for_workflows: bool,
}

impl StreamingDynamodbDispatchArgs {
    /// Discover all spicepod YAML files in the configured directory.
    ///
    /// # Errors
    ///
    /// Returns an error if the directory cannot be read or contains no YAML files.
    pub fn all_spicepod_paths(&self) -> anyhow::Result<Vec<PathBuf>> {
        let mut paths = Vec::new();

        for entry in std::fs::read_dir(&self.path)? {
            let entry = entry?;
            let path = entry.path();
            if path.is_file()
                && let Some(ext) = path.extension()
                && (ext == "yaml" || ext == "yml")
            {
                paths.push(path);
            }
        }

        // Sort for deterministic ordering
        paths.sort();

        if paths.is_empty() {
            anyhow::bail!("No YAML files found in {}", self.path.display());
        }

        Ok(paths)
    }

    /// Get the spiced path as a `PathBuf`.
    #[must_use]
    pub fn spiced_path_buf(&self) -> PathBuf {
        PathBuf::from(&self.spiced_path)
    }
}
