allow-expect-in-tests = true
disallowed-macros = [
    { path = "std::assert", reason = "Prefer returning concrete errors instead of assertion panics. If code is truly unreachable, use `unreachable!()` macro." },
    { path = "std::assert_eq", reason = "Prefer returning concrete errors instead of assertion panics. If code is truly unreachable, use `unreachable!()` macro." },
    { path = "std::assert_ne", reason = "Prefer returning concrete errors instead of assertion panics. If code is truly unreachable, use `unreachable!()` macro." },
]
future-size-threshold = 45520 # Large futures are in tests
