[package]
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license-file.workspace = true
name = "dynamodb-streams"
publish.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
aws-config.workspace = true
aws-sdk-dynamodb.workspace = true
aws-sdk-dynamodbstreams.workspace = true
futures.workspace = true
humantime.workspace = true
serde.workspace = true
snafu.workspace = true
tokio.workspace = true
tracing.workspace = true
util = { path = "../util", features = ["datafusion"] }

[dev-dependencies]
serde_json.workspace = true
