[package]
description = "SQL filter pushdown from DataFusion into Elasticsearch query DSL"
edition.workspace = true
homepage.workspace = true
license-file.workspace = true
name = "elasticsearch_datafusion_filter"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
arrow.workspace = true
datafusion.workspace = true
serde_json.workspace = true
snafu.workspace = true

[lints]
workspace = true
