/*
Copyright 2024-2025 The Spice.ai OSS Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//! Spicepod JSON Schema Generator
//!
//! This tool generates a JSON Schema for the Spicepod specification, enriched with
//! connector-specific parameter schemas for data connectors, accelerators, and
//! catalog connectors.

mod collector;
mod enricher;
mod transform;

use collector::{
    collect_catalog_connectors, collect_data_accelerators, collect_data_connectors,
    collect_model_sources,
};
use enricher::enrich_params_schema;
use schemars::schema_for;
use serde_json::{Map, Value};
use spicepod::spec::SpicepodDefinition;
use std::env;
use std::fs::File;
use std::io::Write;

/// Serde `#[serde(alias = "...")]` attributes are not reflected in the JSON
/// schema generated by `schemars`, which causes editors to flag valid spicepod
/// YAML (that uses an alias name) as an "unknown property" when the containing
/// struct uses `#[serde(deny_unknown_fields)]`.
///
/// This table lists the serde aliases we want to expose in the JSON schema so
/// that editors accept them. Each entry is
/// `(canonical_field_name, alias_field_name, ref_of_value_schema)`.
///
/// The `ref_of_value_schema` is matched against the `$ref` of the canonical
/// property so that unrelated fields sharing the same name (e.g. a different
/// struct with its own `access` field) are not accidentally rewritten.
const FIELD_ALIASES: &[(&str, &str, &str)] = &[
    // `#[serde(alias = "mode")] pub access: AccessMode` on `Dataset` and the
    // private `DatasetDeserializer`.
    ("access", "mode", "#/$defs/AccessMode"),
    // `#[serde(alias = "eviction_policy")] pub caching_policy: CachingPolicy`
    // on `CacheConfig`, `SQLResultsCacheConfig`, and `ResultsCache`.
    ("caching_policy", "eviction_policy", "#/$defs/CachingPolicy"),
];

/// Recursively walks the schema and, for every `properties` object that has a
/// property whose name and `$ref` match an entry in `FIELD_ALIASES`, injects
/// an alias property pointing at the same schema value.
fn inject_field_aliases(value: &mut Value) {
    match value {
        Value::Object(map) => {
            inject_into_object(map);
        }
        Value::Array(items) => {
            for v in items {
                inject_field_aliases(v);
            }
        }
        _ => {}
    }
}

fn inject_into_object(map: &mut Map<String, Value>) {
    if let Some(Value::Object(properties)) = map.get_mut("properties") {
        for (canonical, alias, ref_target) in FIELD_ALIASES {
            if properties.contains_key(*alias) {
                continue;
            }
            let Some(canonical_value) = properties.get(*canonical) else {
                continue;
            };
            let Some(Value::String(ref_str)) =
                canonical_value.as_object().and_then(|o| o.get("$ref"))
            else {
                continue;
            };
            if ref_str != *ref_target {
                continue;
            }
            let cloned = canonical_value.clone();
            properties.insert((*alias).to_string(), cloned);
        }
    }
    for v in map.values_mut() {
        inject_field_aliases(v);
    }
}

fn main() {
    let args: Vec<String> = env::args().collect();

    if args.len() != 2 {
        eprintln!("Usage: {} <output_filename>", args[0]);
        std::process::exit(1);
    }

    let output_filename = &args[1];

    // Generate base schema from SpicepodDefinition
    let mut schema = schema_for!(SpicepodDefinition);

    // Collect parameter specs from all registered connectors, accelerators, and model sources
    let data_connectors = collect_data_connectors();
    let data_accelerators = collect_data_accelerators();
    let catalog_connectors = collect_catalog_connectors();
    let model_sources = collect_model_sources();

    // Log what we collected
    eprintln!(
        "Collected {} data connectors, {} data accelerators, {} catalog connectors, {} model sources",
        data_connectors.len(),
        data_accelerators.len(),
        catalog_connectors.len(),
        model_sources.len()
    );

    // Enrich the schema with connector-specific parameter definitions
    enrich_params_schema(
        &mut schema,
        &data_connectors,
        &data_accelerators,
        &catalog_connectors,
        &model_sources,
    );

    // Inject schema-level aliases for serde `#[serde(alias = "...")]` fields.
    if let Some(schema_obj) = schema.as_object_mut() {
        inject_into_object(schema_obj);
    }

    // Serialize to JSON
    let Ok(json_schema) = serde_json::to_string_pretty(&schema) else {
        eprintln!("Unable to serialize schema");
        std::process::exit(1);
    };

    // Write to file
    let Ok(mut file) = File::create(output_filename) else {
        eprintln!("Unable to create file {output_filename}");
        std::process::exit(1);
    };

    if file.write_all(json_schema.as_bytes()).is_err() {
        eprintln!("Unable to write to file {output_filename}");
        std::process::exit(1);
    }

    eprintln!("Schema written to {output_filename}");
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    /// Helper that wraps a set of `properties` into a minimal object schema so
    /// tests can exercise `inject_into_object` directly.
    fn object_with_properties(properties: Value) -> Map<String, Value> {
        let mut obj = Map::new();
        obj.insert("type".to_string(), Value::String("object".to_string()));
        obj.insert("properties".to_string(), properties);
        obj
    }

    #[test]
    fn injects_alias_when_ref_matches() {
        let mut obj = object_with_properties(json!({
            "access": { "$ref": "#/$defs/AccessMode" }
        }));

        inject_into_object(&mut obj);

        let props = obj
            .get("properties")
            .and_then(Value::as_object)
            .expect("properties present");
        assert_eq!(
            props
                .get("mode")
                .and_then(|v| v.get("$ref"))
                .and_then(Value::as_str),
            Some("#/$defs/AccessMode"),
            "alias `mode` should be injected with the same $ref as `access`"
        );
        assert!(
            props.contains_key("access"),
            "canonical property must be preserved"
        );
    }

    #[test]
    fn does_not_inject_when_ref_mismatches() {
        // A different `access` field (not pointing at AccessMode) must not be rewritten.
        let mut obj = object_with_properties(json!({
            "access": { "$ref": "#/$defs/SomeOtherType" }
        }));

        inject_into_object(&mut obj);

        let props = obj
            .get("properties")
            .and_then(Value::as_object)
            .expect("properties");
        assert!(
            !props.contains_key("mode"),
            "alias must not be injected when $ref does not match the configured target"
        );
    }

    #[test]
    fn does_not_overwrite_existing_alias() {
        let mut obj = object_with_properties(json!({
            "access": { "$ref": "#/$defs/AccessMode" },
            "mode": { "type": "string", "description": "pre-existing" }
        }));

        inject_into_object(&mut obj);

        let props = obj
            .get("properties")
            .and_then(Value::as_object)
            .expect("properties");
        let mode = props.get("mode").expect("mode preserved");
        assert_eq!(
            mode.get("description").and_then(Value::as_str),
            Some("pre-existing"),
            "existing alias property must not be overwritten"
        );
    }

    #[test]
    fn injects_recursively_into_nested_definitions() {
        // Simulates a schema with `$defs` that contain object schemas needing aliases.
        let mut root = Map::new();
        root.insert(
            "$defs".to_string(),
            json!({
                "CacheConfig": {
                    "type": "object",
                    "properties": {
                        "caching_policy": { "$ref": "#/$defs/CachingPolicy" }
                    }
                }
            }),
        );

        inject_into_object(&mut root);

        let defs = root.get("$defs").and_then(Value::as_object).expect("$defs");
        let cache = defs
            .get("CacheConfig")
            .and_then(Value::as_object)
            .expect("CacheConfig");
        let props = cache
            .get("properties")
            .and_then(Value::as_object)
            .expect("properties");
        assert!(
            props.contains_key("eviction_policy"),
            "nested alias must be injected recursively"
        );
    }

    #[test]
    fn noop_when_canonical_missing() {
        let mut obj = object_with_properties(json!({
            "unrelated": { "type": "string" }
        }));
        let before = Value::Object(obj.clone());

        inject_into_object(&mut obj);

        assert_eq!(
            Value::Object(obj),
            before,
            "schema without any matching canonical fields must be unchanged"
        );
    }
}
