[package]
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license-file.workspace = true
name = "spidapter"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
arrow-flight = { workspace = true, features = ["flight-sql-experimental"] }
arrow.workspace = true
anyhow.workspace = true
async-trait.workspace = true
aws-config.workspace = true
aws-sdk-dynamodb.workspace = true
aws-sdk-ec2.workspace = true
base64.workspace = true
clap.workspace = true
dirs = "6"
regex.workspace = true
reqwest.workspace = true
runtime-secrets = { path = "../../crates/runtime-secrets", default-features = false }
spice-cloud-client.workspace = true
serde.workspace = true
serde_json.workspace = true
spicepod = { path = "../../crates/spicepod", default-features = false }
system-adapter-protocol.workspace = true
uuid.workspace = true
yaml = { path = "../../crates/yaml" }
rustls.workspace = true
tokio.workspace = true
tokio-postgres.workspace = true
urlencoding = "2"
tonic.workspace = true
url.workspace = true

[dev-dependencies]
tempfile.workspace = true
tokio = { workspace = true, features = ["macros"] }