apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redpanda.name }}
  labels:
    {{- include "chbench-debezium.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ .Values.redpanda.name }}
spec:
  type: ClusterIP
  ports:
    - name: kafka
      port: 9092
      targetPort: kafka
      protocol: TCP
    - name: admin
      port: 9644
      targetPort: admin
      protocol: TCP
    - name: schema
      port: 8081
      targetPort: schema
      protocol: TCP
  selector:
    {{- include "chbench-debezium.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/name: {{ .Values.redpanda.name }}
