[package]
name = "datafusion_udf"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[dependencies]
datafusion.workspace = true
arrow.workspace = true
