[package]
name = "connector-imap"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license-file.workspace = true
description = "IMAP data connector for Spice.ai runtime"

[dependencies]
arrow.workspace = true
async-trait.workspace = true
charset.workspace = true
chrono.workspace = true
data-connector-api = { path = "../../data-connector-api" }
data_components = { path = "../../data_components" }
datafusion.workspace = true
imap.workspace = true
mailparse.workspace = true
linkme.workspace = true
paste.workspace = true
regex.workspace = true
runtime-component = { path = "../../runtime-component" }
runtime-parameters = { path = "../../runtime-parameters" }
secrecy.workspace = true
snafu.workspace = true

[dev-dependencies]
runtime = { path = "../../runtime" }

[lints]
workspace = true
