[package]
description = "IMAP data connector for Spice.ai runtime"
edition.workspace = true
license-file.workspace = true
name = "connector-imap"
publish.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
async-trait.workspace = true
data_components = { path = "../../data_components", features = ["imap"] }
datafusion.workspace = true
imap.workspace = true
linkme.workspace = true
paste.workspace = true
regex.workspace = true
runtime = { path = "../../runtime" }
secrecy.workspace = true
snafu.workspace = true
