[package]
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license-file.workspace = true
name = "runtime-search"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
app = { path = "../app" }
arrow.workspace = true
arrow-schema = { workspace = true, features = ["serde"] }
arrow_tools = { path = "../arrow_tools" }
chunking = { path = "../chunking" }
async-openai.workspace = true
async-stream.workspace = true
async-trait.workspace = true
cache = { path = "../cache" }
data_components = { path = "../data_components" }
datafusion.workspace = true
datafusion-federation = { workspace = true }
datafusion-expr.workspace = true
datafusion-functions-json = { workspace = true }
futures.workspace = true
itertools.workspace = true
llms = { path = "../llms", default-features = false }
runtime-datafusion = { path = "../runtime-datafusion" }
runtime-datafusion-index = { path = "../runtime-datafusion-index" }
runtime-datafusion-udfs = { path = "../runtime-datafusion-udfs" }
runtime-proto = { path = "../runtime-proto" }
runtime-query-engine = { path = "../runtime-query-engine" }
runtime-request-context = { path = "../runtime-request-context" }
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
search = { path = "../search", default-features = false }
snafu.workspace = true
spicepod = { path = "../spicepod" }
rayon = "1.11.0"
moka.workspace = true
telemetry = { path = "../telemetry" }
tokio.workspace = true
tonic.workspace = true
utoipa = { version = "5", optional = true }
util = { path = "../util" }
tracing.workspace = true

[features]
default = []
duckdb = ["search/duckdb"]
elasticsearch = ["search/elasticsearch"]
models = []
openapi = ["dep:utoipa"]
s3_vectors = ["search/s3_vectors"]

[dev-dependencies]
insta.workspace = true
