[package]
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license-file.workspace = true
name = "runtime-datafusion-udfs"
publish.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
ahash.workspace = true
arrow.workspace = true
arrow-schema.workspace = true
async-openai.workspace = true
async-trait.workspace = true
datafusion.workspace = true
datafusion-datasource.workspace = true
futures.workspace = true
llms = { path = "../llms", default-features = false, optional = true }
opentelemetry.workspace = true
reqwest.workspace = true
runtime-auth = { path = "../runtime-auth" }
runtime-rate-control = { path = "../runtime-rate-control" }
runtime-request-context = { path = "../runtime-request-context" }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
simsimd = "6.5"
snafu.workspace = true
spicepod = { path = "../spicepod", default-features = false }
tokio.workspace = true
tracing.workspace = true
url.workspace = true
util = { path = "../util" }

[dev-dependencies]
async-stream.workspace = true
axum.workspace = true
governor.workspace = true
insta.workspace = true
tracing-subscriber.workspace = true
tracing-test = "0.2"

[features]
models = ["dep:llms"]
