[package]
name = "llms"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snafu.workspace = true

dirs = "5.0.1"
serde_json.workspace = true
async-openai = "0.21.0"
async-trait.workspace = true
tracing.workspace = true
serde = { workspace = true, features = ["derive"] }

## `candle` feature packages
candle-core = {version= "0.5.0", optional = true}
candle-examples = {version= "0.5.0", optional = true}
candle-transformers = {version= "0.5.0", optional = true}
tokenizers = {version= "0.19.1", optional = true}

## `mistralrs` feature packages
mistralrs = { git = "https://github.com/spiceai/mistral.rs", rev = "243bbd5c765a22a11b0270c83664c9060a30caf8", optional=true }
mistralrs-core = { git = "https://github.com/spiceai/mistral.rs", rev = "243bbd5c765a22a11b0270c83664c9060a30caf8", optional=true, package="mistralrs-core" }
candle-core-rs = { package="candle-core", git = "https://github.com/spiceai/candle.git", rev = "38f8d9e01f8684d4fa4ee171bdde3f1a89f41c54", optional=true }
tokio = { workspace = true, optional=true }

[features]
default = []
candle = ["dep:candle-core", "dep:candle-examples", "dep:candle-transformers", "dep:tokenizers"]
mistralrs = ["dep:mistralrs", "dep:candle-core-rs", "dep:mistralrs-core", "dep:tokio"]
metal = ["mistralrs-core/metal"]