# link-dead-code is required for duckdb-rs to work with motherduck extension
# this can be removed once the issue is fixed in duckdb-rs: https://github.com/duckdb/duckdb-rs/issues/252
[build]
rustflags = ["-C", "link-dead-code"]

[target.'cfg(all(windows, target_env = "msvc"))']
rustflags = ["-C", "target-feature=+crt-static", "-C", "link-dead-code"]