[package]
description = "Tools for the Spice runtime"
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license.workspace = true
name = "tools"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
async-trait.workspace = true
rmcp = { git = "https://github.com/spiceai/modelcontextprotocol-rust-sdk.git", rev = "f9a32b0d7bf35400467a2965bd10e90a0d877d0e", optional = true }
serde_json.workspace = true

[features]
mcp = ["dep:rmcp"]
