name: Run Integration Tests
description: Runs `/crates/llms/tests` integration tests.
inputs:
  model_allowlist:
    description: "Comma-separated list of allowed models for the integration test."
    required: true
  networked:
    description: "Indicates if the test is networked and requires .env setup."
    required: false
    default: "false"
outputs: {}
runs:
  using: "composite"
  steps:
    - name: Set up Rust
      uses: ./.github/actions/setup-rust
      with:
        os: "linux"

    - name: Download test binary
      uses: actions/download-artifact@v4
      with:
        name: llms-integration-test-binary
        path: ./integration_test

    - name: Mark test binary as executable
      shell: bash
      run: chmod +x ./integration_test/llms_integration_test

    - name: Run integration test
      shell: bash
      run: |
        if [ "${{ inputs.networked }}" == "true" ]; then
          if [ -z "$SPICE_SECRET_OPENAI_API_KEY" ]; then
            echo "Error: OpenAI API key is not defined."
            exit 1
          fi
          if [ -z "$SPICE_SECRET_ANTHROPIC_API_KEY" ]; then
            echo "Error: Anthropic API key is not defined."
            exit 1
          fi
          if [ -z "$SPICE_SECRET_XAI_API_KEY" ]; then
            echo "Error: xAI API key is not defined."
            exit 1
          fi
        fi

        export MODEL_ALLOWLIST="${{ inputs.model_allowlist }}"
        INSTA_WORKSPACE_ROOT="${PWD}" CARGO_MANIFEST_DIR="${PWD}" ./integration_test/llms_integration_test --nocapture
