[package]
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license-file.workspace = true
name = "datafusion-optimizer-rules"
publish.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
arrow = { workspace = true }
async-stream.workspace = true
async-trait.workspace = true
cache = { path = "../cache" }
chrono = { workspace = true }
data_components = { path = "../data_components", features = ["flightsql"] }
datafusion.workspace = true
datafusion-datasource = { workspace = true }
datafusion-expr.workspace = true
datafusion-federation.workspace = true
datafusion-table-providers.workspace = true
duckdb = { optional = true, workspace = true }
flight_client = { path = "../flight_client" }
futures.workspace = true
itertools = { workspace = true }
object_store = { workspace = true }
r2d2 = { optional = true, workspace = true }
snafu.workspace = true
tokio.workspace = true
tracing.workspace = true
url = { workspace = true }

[dev-dependencies]
arrow-flight.workspace = true
insta.workspace = true
reqwest.workspace = true
tonic.workspace = true


[features]
duckdb = ["datafusion-table-providers/duckdb", "dep:duckdb", "dep:r2d2"]
