# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/runtime/v1/runtime.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/runtime/v1/runtime.proto',
  package='runtime',
  syntax='proto3',
  serialized_options=b'Z/github.com/spiceai/spiceai/pkg/proto/runtime_pb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1eproto/runtime/v1/runtime.proto\x12\x07runtime\"2\n\x0b\x45xportModel\x12\x11\n\tdirectory\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\"=\n\x0bImportModel\x12\x0b\n\x03pod\x18\x01 \x01(\t\x12\x0b\n\x03tag\x18\x02 \x01(\t\x12\x14\n\x0c\x61rchive_path\x18\x03 \x01(\t\"\xdb\x01\n\x07\x45pisode\x12\x0f\n\x07\x65pisode\x18\x01 \x01(\x04\x12\r\n\x05start\x18\x02 \x01(\x03\x12\x0b\n\x03\x65nd\x18\x03 \x01(\x03\x12\r\n\x05score\x18\x04 \x01(\x01\x12\x39\n\ractions_taken\x18\x05 \x03(\x0b\x32\".runtime.Episode.ActionsTakenEntry\x12\r\n\x05\x65rror\x18\x06 \x01(\t\x12\x15\n\rerror_message\x18\x07 \x01(\t\x1a\x33\n\x11\x41\x63tionsTakenEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x04:\x02\x38\x01\"H\n\x06\x46light\x12\r\n\x05start\x18\x01 \x01(\x03\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x03\x12\"\n\x08\x65pisodes\x18\x03 \x03(\x0b\x32\x10.runtime.Episode\"T\n\x03Pod\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x15\n\rmanifest_path\x18\x02 \x01(\t\x12\x14\n\x0cmeasurements\x18\x03 \x03(\t\x12\x12\n\ncategories\x18\x04 \x03(\t\"A\n\nTrainModel\x12\x1a\n\x12learning_algorithm\x18\x01 \x01(\t\x12\x17\n\x0fnumber_episodes\x18\x02 \x01(\x03\x42\x31Z/github.com/spiceai/spiceai/pkg/proto/runtime_pbb\x06proto3'
)




_EXPORTMODEL = _descriptor.Descriptor(
  name='ExportModel',
  full_name='runtime.ExportModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='directory', full_name='runtime.ExportModel.directory', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='filename', full_name='runtime.ExportModel.filename', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=93,
)


_IMPORTMODEL = _descriptor.Descriptor(
  name='ImportModel',
  full_name='runtime.ImportModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pod', full_name='runtime.ImportModel.pod', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tag', full_name='runtime.ImportModel.tag', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='archive_path', full_name='runtime.ImportModel.archive_path', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=156,
)


_EPISODE_ACTIONSTAKENENTRY = _descriptor.Descriptor(
  name='ActionsTakenEntry',
  full_name='runtime.Episode.ActionsTakenEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='runtime.Episode.ActionsTakenEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='runtime.Episode.ActionsTakenEntry.value', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=327,
  serialized_end=378,
)

_EPISODE = _descriptor.Descriptor(
  name='Episode',
  full_name='runtime.Episode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='episode', full_name='runtime.Episode.episode', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start', full_name='runtime.Episode.start', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end', full_name='runtime.Episode.end', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='score', full_name='runtime.Episode.score', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='actions_taken', full_name='runtime.Episode.actions_taken', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='runtime.Episode.error', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error_message', full_name='runtime.Episode.error_message', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_EPISODE_ACTIONSTAKENENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=378,
)


_FLIGHT = _descriptor.Descriptor(
  name='Flight',
  full_name='runtime.Flight',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='runtime.Flight.start', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end', full_name='runtime.Flight.end', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='episodes', full_name='runtime.Flight.episodes', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=380,
  serialized_end=452,
)


_POD = _descriptor.Descriptor(
  name='Pod',
  full_name='runtime.Pod',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='runtime.Pod.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='manifest_path', full_name='runtime.Pod.manifest_path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='measurements', full_name='runtime.Pod.measurements', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='categories', full_name='runtime.Pod.categories', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=454,
  serialized_end=538,
)


_TRAINMODEL = _descriptor.Descriptor(
  name='TrainModel',
  full_name='runtime.TrainModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='learning_algorithm', full_name='runtime.TrainModel.learning_algorithm', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='number_episodes', full_name='runtime.TrainModel.number_episodes', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=540,
  serialized_end=605,
)

_EPISODE_ACTIONSTAKENENTRY.containing_type = _EPISODE
_EPISODE.fields_by_name['actions_taken'].message_type = _EPISODE_ACTIONSTAKENENTRY
_FLIGHT.fields_by_name['episodes'].message_type = _EPISODE
DESCRIPTOR.message_types_by_name['ExportModel'] = _EXPORTMODEL
DESCRIPTOR.message_types_by_name['ImportModel'] = _IMPORTMODEL
DESCRIPTOR.message_types_by_name['Episode'] = _EPISODE
DESCRIPTOR.message_types_by_name['Flight'] = _FLIGHT
DESCRIPTOR.message_types_by_name['Pod'] = _POD
DESCRIPTOR.message_types_by_name['TrainModel'] = _TRAINMODEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExportModel = _reflection.GeneratedProtocolMessageType('ExportModel', (_message.Message,), {
  'DESCRIPTOR' : _EXPORTMODEL,
  '__module__' : 'proto.runtime.v1.runtime_pb2'
  # @@protoc_insertion_point(class_scope:runtime.ExportModel)
  })
_sym_db.RegisterMessage(ExportModel)

ImportModel = _reflection.GeneratedProtocolMessageType('ImportModel', (_message.Message,), {
  'DESCRIPTOR' : _IMPORTMODEL,
  '__module__' : 'proto.runtime.v1.runtime_pb2'
  # @@protoc_insertion_point(class_scope:runtime.ImportModel)
  })
_sym_db.RegisterMessage(ImportModel)

Episode = _reflection.GeneratedProtocolMessageType('Episode', (_message.Message,), {

  'ActionsTakenEntry' : _reflection.GeneratedProtocolMessageType('ActionsTakenEntry', (_message.Message,), {
    'DESCRIPTOR' : _EPISODE_ACTIONSTAKENENTRY,
    '__module__' : 'proto.runtime.v1.runtime_pb2'
    # @@protoc_insertion_point(class_scope:runtime.Episode.ActionsTakenEntry)
    })
  ,
  'DESCRIPTOR' : _EPISODE,
  '__module__' : 'proto.runtime.v1.runtime_pb2'
  # @@protoc_insertion_point(class_scope:runtime.Episode)
  })
_sym_db.RegisterMessage(Episode)
_sym_db.RegisterMessage(Episode.ActionsTakenEntry)

Flight = _reflection.GeneratedProtocolMessageType('Flight', (_message.Message,), {
  'DESCRIPTOR' : _FLIGHT,
  '__module__' : 'proto.runtime.v1.runtime_pb2'
  # @@protoc_insertion_point(class_scope:runtime.Flight)
  })
_sym_db.RegisterMessage(Flight)

Pod = _reflection.GeneratedProtocolMessageType('Pod', (_message.Message,), {
  'DESCRIPTOR' : _POD,
  '__module__' : 'proto.runtime.v1.runtime_pb2'
  # @@protoc_insertion_point(class_scope:runtime.Pod)
  })
_sym_db.RegisterMessage(Pod)

TrainModel = _reflection.GeneratedProtocolMessageType('TrainModel', (_message.Message,), {
  'DESCRIPTOR' : _TRAINMODEL,
  '__module__' : 'proto.runtime.v1.runtime_pb2'
  # @@protoc_insertion_point(class_scope:runtime.TrainModel)
  })
_sym_db.RegisterMessage(TrainModel)


DESCRIPTOR._options = None
_EPISODE_ACTIONSTAKENENTRY._options = None
# @@protoc_insertion_point(module_scope)
