[package]
name = "snowflake_adbc"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
arrow = { workspace = true }
arrow-schema = { workspace = true }
arrow-array = { workspace = true }
arrow-ipc = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true, features = ["rt", "sync"] }
reqwest = { workspace = true, features = ["json", "stream"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
snafu = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
base64 = "0.22"
futures = { workspace = true }
once_cell = "1.21.3"
jsonwebtoken = "9"
rsa = "0.9"
spki = { version = "0.7", features = ["std"] }
pkcs8 = { version = "0.10", features = ["pem"] }
sha2 = "0.10"
hex = "0.4"
bytes = "1.0"
uuid = { workspace = true, features = ["v4"] }
