CREATE INDEX idx_customer_mktsegment          ON customer     (c_mktsegment);
CREATE INDEX idx_orders_cust_orderdate        ON orders       (o_custkey, o_orderdate);
CREATE INDEX idx_lineitem_order_shipdate      ON lineitem     (l_orderkey, l_shipdate);
CREATE INDEX idx_customer_nation_custkey      ON customer     (c_nationkey, c_custkey);
CREATE INDEX idx_orders_cust_orderdate_key    ON orders       (o_custkey, o_orderdate, o_orderkey);
CREATE INDEX idx_lineitem_order_supp           ON lineitem     (l_orderkey, l_suppkey);
CREATE INDEX idx_supplier_supp_nation         ON supplier     (s_suppkey, s_nationkey);
CREATE INDEX idx_nation_key_name              ON nation       (n_nationkey, n_name);
CREATE INDEX idx_part_type_partkey            ON part         (p_type, p_partkey);
CREATE INDEX idx_orders_orderdate_key         ON orders       (o_orderdate, o_orderkey);
CREATE INDEX idx_lineitem_part_supp_order     ON lineitem     (l_partkey, l_suppkey, l_orderkey);
CREATE INDEX idx_partsupp_part_supp_cost      ON partsupp     (ps_partkey, ps_suppkey, ps_supplycost);
CREATE INDEX idx_supplier_nationkey_suppkey   ON supplier     (s_nationkey, s_suppkey);
CREATE INDEX idx_nation_name_key              ON nation       (n_name, n_nationkey);
CREATE INDEX idx_orders_cust_comment          ON orders       (o_custkey, o_comment, o_orderkey);
CREATE INDEX idx_part_type_cover ON part(p_type, p_partkey, p_name);
CREATE INDEX idx_supplier_nation_suppkey    ON supplier (s_nationkey, s_suppkey);
CREATE INDEX idx_lineitem_supp_order_commit ON lineitem (l_suppkey, l_orderkey, l_commitdate, l_receiptdate);
CREATE INDEX idx_orders_status_orderkey     ON orders (o_orderstatus, o_orderkey);
CREATE INDEX idx_nation_name_nationkey      ON nation (n_name, n_nationkey);