[package]
name = "runtime-parameters"
description = "Runtime parameters management for the workspace."
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license-file.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
itertools.workspace = true
runtime-parameter-spec = { path = "../runtime-parameter-spec" }
runtime-parameters-derive = { path = "../runtime-parameters-derive" }
runtime-secrets = { path = "../runtime-secrets", default-features = false }
secrecy.workspace = true
snafu.workspace = true
tokio = { workspace = true, features = ["sync"] }
tracing.workspace = true
util = { path = "../util" }

[dev-dependencies]
async-trait.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "sync", "time"] }

[lints]
workspace = true
