[package]
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license-file.workspace = true
name = "arrow_tools"
publish.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
arrow.workspace = true
arrow-cast.workspace = true
arrow-schema.workspace = true
datafusion.workspace = true
snafu.workspace = true
tracing.workspace = true

[dev-dependencies]
arrow-json.workspace = true
insta = { workspace = true, features = ["json"] }
serde_json.workspace = true
criterion = { version = "0.7", features = ["html_reports"] }

[[bench]]
name = "truncate"
harness = false
