[package]
name = "runtime-status"
description = "Runtime component status tracking for the Spice runtime"
edition.workspace = true
homepage.workspace = true
license-file.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
datafusion.workspace = true
opentelemetry.workspace = true
runtime-api-types = { path = "../runtime-api-types" }
runtime-datafusion = { path = "../runtime-datafusion" }
runtime-metrics = { path = "../runtime-metrics" }
tokio = { workspace = true, features = ["sync", "time"] }
tokio-util = { workspace = true, features = ["rt"] }
util = { path = "../util", features = ["datafusion"] }

[lints]
workspace = true
