/*
Copyright 2024-2026 The Spice.ai OSS Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//! `MySQL` TPC-C transaction implementations — a mirror of the Postgres
//! transactions in the sibling modules, adapted for `mysql_async`.
//!
//! Unlike the Postgres path, there is no `PreparedStatements` struct: `mysql_async`
//! auto-prepares and caches statements per connection when a `&str` is passed to
//! the `exec_*` family, so every transaction issues its SQL text directly.
//!
//! TPC-C logic, RNG call order, transaction boundaries, and the rows
//! read/locked/written match the Postgres implementations in [`super::prepared`]
//! and siblings, so a given seed produces a comparable workload. The *statement
//! shapes* deliberately do not: to cut client-server round trips — the dominant
//! cost for this driver — per-line-item reads are batched into `IN`-list
//! SELECTs and consecutive writes share a round trip as `;`-separated
//! multi-statement batches (`mysql_async` always negotiates
//! `CLIENT_MULTI_STATEMENTS`).
//!
//! Every mutating statement also binds a `_bench_ts` stamp generated by the
//! driver ([`BenchTs`]), and each transaction folds that stamp into the shared
//! [`Watermarks`] after its COMMIT succeeds — this is what lets the staleness
//! probe read `MAX(_bench_ts)` as an atomic load instead of a table scan.

use std::collections::HashMap;
use std::fmt::Write as _;

use ::rand::{Rng, RngExt};
use mysql_async::prelude::Queryable;
use mysql_async::{Row, Value};
use rust_decimal::Decimal;

use super::TerminalAssignment;
use crate::Result;
use crate::rand as tpcc_rand;
use crate::watermark::{BenchTs, MutatedTable, Touched, Watermarks};

/// Current wall-clock time as a UTC-naive datetime.
///
/// The terminal's `MySQL` session is pinned to UTC (see `set_mysql_utc` in `lib.rs`),
/// so binding a `NaiveDateTime` writes UTC wall-clock time, matching how the CDC
/// path and `max_bench_ts` interpret the `DATETIME` columns.
fn now_naive() -> chrono::NaiveDateTime {
    chrono::Utc::now().naive_utc()
}

/// Execute one TPC-C transaction of the given type against a `MySQL` connection.
///
/// # Errors
///
/// Returns an error if the transaction fails.
pub async fn execute(
    conn: &mut mysql_async::Conn,
    rng: &mut impl ::rand::Rng,
    txn_type: super::TxnType,
    assignment: &super::TerminalAssignment,
    watermarks: &Watermarks,
) -> crate::Result<()> {
    match txn_type {
        super::TxnType::NewOrder => run_new_order(conn, rng, assignment, watermarks).await,
        super::TxnType::Payment => run_payment(conn, rng, assignment, watermarks).await,
        super::TxnType::Delivery => {
            run_delivery(conn, rng, assignment.num_warehouses, watermarks).await
        }
        super::TxnType::OrderStatus => run_order_status(conn, rng, assignment.num_warehouses).await,
        super::TxnType::StockLevel => run_stock_level(conn, rng, assignment.num_warehouses).await,
    }
}

/// TPC-C `NewOrder` transaction (45% default mix).
///
/// Inserts an order with 5-15 line items. Updates `district.d_next_o_id` and stock
/// quantities. Mirrors [`super::new_order::run`].
async fn run_new_order(
    conn: &mut mysql_async::Conn,
    rng: &mut impl Rng,
    assignment: &TerminalAssignment,
    watermarks: &Watermarks,
) -> Result<()> {
    // Collected write data from Phase 1.
    struct LineWrite {
        s_quantity: i32,
        ol_quantity: i32,
        remote: i32,
        ol_i_id: i32,
        ol_supply_w_id: i32,
        ol_number: i32,
        ol_amount: Decimal,
        ol_dist_info: String,
    }

    let w_id = assignment.home_w_id;
    let d_id = rng.random_range(assignment.district_lo..=assignment.district_hi);
    let c_id = tpcc_rand::rand_customer_id(rng);
    let ol_cnt = rng.random_range(5..=15);
    let rbk = rng.random_range(1..=100);

    // Generate order items
    #[expect(clippy::cast_sign_loss)]
    let mut items: Vec<(i32, i32, i32, i32)> = Vec::with_capacity(ol_cnt as usize); // (ol_i_id, ol_supply_w_id, ol_quantity, remote)
    let mut all_local = 1i32;

    for i in 0..ol_cnt {
        let ol_i_id = if i == ol_cnt - 1 && rbk == 1 {
            // 1% rollback: invalid item ID
            -1
        } else {
            rng.random_range(1..=100_000)
        };

        let (ol_supply_w_id, remote) =
            if assignment.num_warehouses == 1 || rng.random_range(1..=100) != 1 {
                (w_id, 0)
            } else {
                let mut other = rng.random_range(1..=assignment.num_warehouses);
                while other == w_id {
                    other = rng.random_range(1..=assignment.num_warehouses);
                }
                all_local = 0;
                (other, 1)
            };

        let ol_quantity = rng.random_range(1..=10);
        items.push((ol_i_id, ol_supply_w_id, ol_quantity, remote));
    }

    let mut tx = conn
        .start_transaction(mysql_async::TxOpts::default())
        .await
        .map_err(|source| crate::Error::MySql {
            action: "begin new_order transaction".into(),
            source,
        })?;

    // 1. SELECT customer + warehouse info
    let customer_row: Option<(Decimal, String, String, Decimal)> = tx
        .exec_first(
            "SELECT c_discount, c_last, c_credit, w_tax \
             FROM customer, warehouse \
             WHERE w_id = ? AND c_w_id = w_id AND c_d_id = ? AND c_id = ?",
            (w_id, d_id, c_id),
        )
        .await
        .map_err(|source| crate::Error::MySql {
            action: "new_order: select customer".into(),
            source,
        })?;
    let Some((c_discount, _c_last, _c_credit, w_tax)) = customer_row else {
        return Err(crate::Error::Arrow {
            action: "new_order".into(),
            message: "customer row not found".into(),
        });
    };

    // 2. SELECT district FOR UPDATE
    let district_row: Option<(i32, Decimal)> = tx
        .exec_first(
            "SELECT d_next_o_id, d_tax FROM district \
             WHERE d_id = ? AND d_w_id = ? FOR UPDATE",
            (d_id, w_id),
        )
        .await
        .map_err(|source| crate::Error::MySql {
            action: "new_order: select district".into(),
            source,
        })?;
    let Some((d_next_o_id, d_tax)) = district_row else {
        return Err(crate::Error::Arrow {
            action: "new_order".into(),
            message: "district row not found".into(),
        });
    };

    // One stamp per transaction, captured after the initial reads and bound
    // into every write below; folded into the watermarks only after COMMIT.
    let bench_ts = BenchTs::now_mysql();

    // 3. UPDATE district d_next_o_id
    tx.exec_drop(
        "UPDATE district SET d_next_o_id = ? + 1, _bench_ts = ? WHERE d_id = ? AND d_w_id = ?",
        (d_next_o_id, bench_ts.mysql_value(), d_id, w_id),
    )
    .await
    .map_err(|source| crate::Error::MySql {
        action: "new_order: update district".into(),
        source,
    })?;

    let o_id = d_next_o_id;
    let now = now_naive();

    // 4. INSERT oorder
    tx.exec_drop(
        "INSERT INTO oorder (o_id, o_d_id, o_w_id, o_c_id, o_entry_d, o_ol_cnt, o_all_local, _bench_ts) \
         VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
        (o_id, d_id, w_id, c_id, now, ol_cnt, all_local, bench_ts.mysql_value()),
    )
    .await
    .map_err(|source| crate::Error::MySql {
        action: "new_order: insert oorder".into(),
        source,
    })?;

    // 5. INSERT new_order
    tx.exec_drop(
        "INSERT INTO new_order (no_o_id, no_d_id, no_w_id, _bench_ts) VALUES (?, ?, ?, ?)",
        (o_id, d_id, w_id, bench_ts.mysql_value()),
    )
    .await
    .map_err(|source| crate::Error::MySql {
        action: "new_order: insert new_order".into(),
        source,
    })?;

    // 6-9. Process order lines in two phases (similar to BenchBase-style batching):
    //   Phase 1: Batched reads — one item SELECT for all lines, one stock
    //            SELECT ... FOR UPDATE per supply warehouse (a single one in the
    //            ~99% all-local case) — instead of two round trips per line.
    //   Phase 2: Batched writes — all stock UPDATEs in one multi-statement round
    //            trip, then one multi-row order_line INSERT.
    #[expect(clippy::cast_sign_loss)]
    let mut writes: Vec<LineWrite> = Vec::with_capacity(ol_cnt as usize);

    // The stock district column (s_dist_01..s_dist_10) selected depends on d_id.
    let s_dist_col = format!("s_dist_{d_id:02}");

    // 1% rollback case (spec 2.4.1.4): the last line carries an invalid item id.
    // Detected up front now that reads are batched (the per-line read loop used
    // to hit it mid-loop). Roll back explicitly — mysql_async does not issue a
    // ROLLBACK when a transaction handle is merely dropped, so relying on drop
    // could leave the transaction open on the connection.
    if items.iter().any(|&(ol_i_id, ..)| ol_i_id < 0) {
        tx.rollback().await.map_err(|source| crate::Error::MySql {
            action: "new_order: rollback".into(),
            source,
        })?;
        return Ok(());
    }

    // Phase 1a: one round trip fetches every item of the order. Duplicate ids
    // inside IN (...) are harmless — the server returns each matching row once.
    // i_name/i_data are selected and discarded, as TPC-C requires reading them.
    let placeholders = vec!["?"; items.len()].join(", ");
    let item_sql =
        format!("SELECT i_id, i_price, i_name, i_data FROM item WHERE i_id IN ({placeholders})");
    let item_params: Vec<Value> = items.iter().map(|&(id, ..)| Value::from(id)).collect();
    let item_rows: Vec<(i32, Decimal, String, String)> = tx
        .exec(&item_sql, item_params)
        .await
        .map_err(|source| crate::Error::MySql {
            action: "new_order: select items".into(),
            source,
        })?;
    let prices: HashMap<i32, Decimal> = item_rows
        .into_iter()
        .map(|(i_id, i_price, _i_name, _i_data)| (i_id, i_price))
        .collect();

    // Phase 1b: one round trip locks and reads every stock row of the order —
    // local and remote alike — via a row-constructor IN list, which MySQL 8.0
    // executes as range accesses on the (s_w_id, s_i_id) primary key
    // (EXPLAIN: type=range, key=PRIMARY). Locks are taken in PK scan order,
    // unlike the per-line loop, which acquired them in random line order — the
    // more deadlock-prone pattern. Grouping items by warehouse into per-warehouse
    // single-column IN statements measured the same tpmC (within run noise) and
    // needs ~15 more lines, so the uniform single statement wins.
    // s_data is selected and discarded, as TPC-C requires reading it.
    let placeholders = vec!["(?, ?)"; items.len()].join(", ");
    let stock_sql = format!(
        "SELECT s_w_id, s_i_id, s_quantity, s_data, {s_dist_col} FROM stock \
         WHERE (s_w_id, s_i_id) IN ({placeholders}) FOR UPDATE"
    );
    let stock_params: Vec<Value> = items
        .iter()
        .flat_map(|&(ol_i_id, ol_supply_w_id, _, _)| {
            [Value::from(ol_supply_w_id), Value::from(ol_i_id)]
        })
        .collect();
    let stock_rows: Vec<(i32, i32, i32, String, String)> = tx
        .exec(&stock_sql, stock_params)
        .await
        .map_err(|source| crate::Error::MySql {
            action: "new_order: select stock".into(),
            source,
        })?;
    let stock: HashMap<(i32, i32), (i32, String)> = stock_rows
        .into_iter()
        .map(|(s_w_id, s_i_id, s_quantity, _s_data, ol_dist_info)| {
            ((s_w_id, s_i_id), (s_quantity, ol_dist_info))
        })
        .collect();

    for (ol_number_0, &(ol_i_id, ol_supply_w_id, ol_quantity, remote)) in items.iter().enumerate() {
        let ol_number = i32::try_from(ol_number_0).unwrap_or(0) + 1;

        let Some(&i_price) = prices.get(&ol_i_id) else {
            return Err(crate::Error::Arrow {
                action: "new_order".into(),
                message: "item row not found".into(),
            });
        };
        // Duplicate line items see the same pre-transaction stock value, exactly
        // as the per-line reads did (all reads preceded all writes already).
        let Some(&(base_s_quantity, ref ol_dist_info)) = stock.get(&(ol_supply_w_id, ol_i_id))
        else {
            return Err(crate::Error::Arrow {
                action: "new_order".into(),
                message: "stock row not found".into(),
            });
        };

        let mut s_quantity = base_s_quantity - ol_quantity;
        if s_quantity < 10 {
            s_quantity += 91;
        }

        // Exact decimal arithmetic; MySQL rounds to DECIMAL(6,2) on store.
        let ol_amount = Decimal::from(ol_quantity)
            * i_price
            * (Decimal::ONE + w_tax + d_tax)
            * (Decimal::ONE - c_discount);

        writes.push(LineWrite {
            s_quantity,
            ol_quantity,
            remote,
            ol_i_id,
            ol_supply_w_id,
            ol_number,
            ol_amount,
            ol_dist_info: ol_dist_info.clone(),
        });
    }

    // Phase 2: writes. All stock UPDATEs share one round trip as a
    // multi-statement batch (mysql_async always negotiates
    // CLIENT_MULTI_STATEMENTS). Every interpolated value is an integer or the
    // driver-generated fixed-format _bench_ts literal, so literal SQL carries
    // no quoting concerns. The write order (all stock UPDATEs, then the
    // order_line INSERT) matches the Postgres path.
    let bench_ts_literal = bench_ts.mysql_literal();
    let mut stock_batch = String::with_capacity(writes.len() * 200);
    for w in &writes {
        if let Err(e) = write!(
            &mut stock_batch,
            "UPDATE stock SET s_quantity = {}, s_ytd = s_ytd + {}, \
             s_order_cnt = s_order_cnt + 1, s_remote_cnt = s_remote_cnt + {}, \
             _bench_ts = {bench_ts_literal} \
             WHERE s_i_id = {} AND s_w_id = {};",
            w.s_quantity, w.ol_quantity, w.remote, w.ol_i_id, w.ol_supply_w_id,
        ) {
            eprintln!("Failed to format stock UPDATE batch SQL: {e}");
        }
    }
    tx.query_iter(&stock_batch)
        .await
        .map_err(|source| crate::Error::MySql {
            action: "new_order: update stock".into(),
            source,
        })?
        // Every statement's result set must be drained before the connection is
        // reusable; drop_result drains all of them.
        .drop_result()
        .await
        .map_err(|source| crate::Error::MySql {
            action: "new_order: drain stock update results".into(),
            source,
        })?;

    // Single INSERT with all order-line rows (one INSERT with N value tuples),
    // mirroring the Postgres batched multi-row INSERT.
    let mut insert_sql = String::with_capacity(writes.len() * 44 + 128);
    insert_sql.push_str(
        "INSERT INTO order_line \
         (ol_o_id, ol_d_id, ol_w_id, ol_number, ol_i_id, ol_supply_w_id, \
          ol_quantity, ol_amount, ol_dist_info, _bench_ts) VALUES ",
    );
    let mut params: Vec<Value> = Vec::with_capacity(writes.len() * 10);
    for (i, w) in writes.iter().enumerate() {
        if i > 0 {
            insert_sql.push(',');
        }
        // Placeholder count per row: 10. Overall placeholder count: 10 * writes.len().
        if let Err(e) = write!(&mut insert_sql, "(?, ?, ?, ?, ?, ?, ?, ?, ?, ?)") {
            eprintln!("Failed to format order_line VALUES SQL: {e}");
        }
        params.push(o_id.into());
        params.push(d_id.into());
        params.push(w_id.into());
        params.push(w.ol_number.into());
        params.push(w.ol_i_id.into());
        params.push(w.ol_supply_w_id.into());
        params.push(w.ol_quantity.into());
        params.push(w.ol_amount.into());
        params.push(w.ol_dist_info.clone().into());
        params.push(bench_ts.mysql_value().into());
    }

    tx.exec_drop(&insert_sql, params)
        .await
        .map_err(|source| crate::Error::MySql {
            action: "new_order: insert order_line".into(),
            source,
        })?;

    tx.commit().await.map_err(|source| crate::Error::MySql {
        action: "new_order: commit".into(),
        source,
    })?;

    // Every commit-path new_order writes all five tables. new_order itself is
    // delete-bearing and never served from the watermark, but recording it is
    // harmless and keeps the bookkeeping uniform.
    let mut touched = Touched::new();
    touched.add(MutatedTable::District);
    touched.add(MutatedTable::Oorder);
    touched.add(MutatedTable::NewOrder);
    touched.add(MutatedTable::Stock);
    touched.add(MutatedTable::OrderLine);
    watermarks.record(touched, bench_ts);

    Ok(())
}

/// TPC-C Payment transaction (43% default mix).
///
/// Updates warehouse/district/customer balances and inserts a history record.
/// Mirrors [`super::payment::run`].
async fn run_payment(
    conn: &mut mysql_async::Conn,
    rng: &mut impl Rng,
    assignment: &TerminalAssignment,
    watermarks: &Watermarks,
) -> Result<()> {
    let w_id = assignment.home_w_id;
    let d_id = rng.random_range(assignment.district_lo..=assignment.district_hi);
    // Exact cents/100 (same i32 RNG draw as before). c_ytd_payment is DOUBLE, so
    // it needs an f64 bind; the DECIMAL columns take the Decimal.
    let h_cents: i32 = rng.random_range(100..=500_000);
    let h_amount = Decimal::new(i64::from(h_cents), 2);
    let h_amount_f64 = f64::from(h_cents) / 100.0;

    // 60% by last name, 40% by customer ID (spec 2.5.1.2)
    let by_name = rng.random_range(0..100) < 60;
    let c_last = if by_name {
        let c_load: usize = rng.random_range(0..256);
        Some(tpcc_rand::rand_c_last(rng, c_load))
    } else {
        None
    };
    let mut c_id = if by_name {
        0
    } else {
        tpcc_rand::rand_customer_id(rng)
    };

    // 85% local, 15% remote (spec 2.5.1.2)
    let (customer_wh, customer_dist) =
        if assignment.num_warehouses == 1 || rng.random_range(0..100) < 85 {
            (w_id, d_id)
        } else {
            let mut other = rng.random_range(1..=assignment.num_warehouses);
            while other == w_id {
                other = rng.random_range(1..=assignment.num_warehouses);
            }
            (other, rng.random_range(1..=10))
        };

    let mut tx = conn
        .start_transaction(mysql_async::TxOpts::default())
        .await
        .map_err(|source| crate::Error::MySql {
            action: "begin payment transaction".into(),
            source,
        })?;

    // One stamp per transaction, bound into every write below; folded into the
    // watermarks only after COMMIT.
    let bench_ts = BenchTs::now_mysql();
    let bench_ts_literal = bench_ts.mysql_literal();

    // 1. UPDATE warehouse + district YTD in one multi-statement round trip
    //    (mysql_async always negotiates CLIENT_MULTI_STATEMENTS). Warehouse
    //    before district, preserving the per-statement lock order. h_amount is
    //    an exact Decimal that formats as a plain numeric literal, the ids are
    //    integers, and the stamp is the driver-generated fixed-format datetime
    //    literal — so literal SQL carries no quoting concerns.
    let ytd_batch = format!(
        "UPDATE warehouse SET w_ytd = w_ytd + {h_amount}, _bench_ts = {bench_ts_literal} \
         WHERE w_id = {w_id};\
         UPDATE district SET d_ytd = d_ytd + {h_amount}, _bench_ts = {bench_ts_literal} \
         WHERE d_w_id = {w_id} AND d_id = {d_id}"
    );
    tx.query_iter(&ytd_batch)
        .await
        .map_err(|source| crate::Error::MySql {
            action: "payment: update warehouse and district ytd".into(),
            source,
        })?
        .drop_result()
        .await
        .map_err(|source| crate::Error::MySql {
            action: "payment: drain ytd update results".into(),
            source,
        })?;

    // 2. SELECT warehouse + district display fields in one joined round trip.
    //    The street/city/state/zip fields are read and discarded, as TPC-C
    //    requires reading them. Decoded as a typed tuple (like the trunk
    //    per-table reads) so a column-list drift fails loudly instead of
    //    silently yielding a wrong or empty name.
    #[expect(clippy::type_complexity)]
    let wd_row: Option<(
        String,
        String,
        String,
        String,
        String,
        String,
        String,
        String,
        String,
        String,
        String,
        String,
    )> = tx
        .exec_first(
            "SELECT w_street_1, w_street_2, w_city, w_state, w_zip, w_name, \
                    d_street_1, d_street_2, d_city, d_state, d_zip, d_name \
             FROM warehouse, district \
             WHERE w_id = ? AND d_w_id = w_id AND d_id = ?",
            (w_id, d_id),
        )
        .await
        .map_err(|source| crate::Error::MySql {
            action: "payment: select warehouse and district".into(),
            source,
        })?;
    let Some((_, _, _, _, _, w_name, _, _, _, _, _, d_name)) = wd_row else {
        return Err(crate::Error::Arrow {
            action: "payment".into(),
            message: "warehouse/district row not found".into(),
        });
    };

    // 5. Resolve customer ID if by last name
    if by_name {
        let rows: Vec<Row> = tx
            .exec(
                "SELECT c_id FROM customer \
                 WHERE c_w_id = ? AND c_d_id = ? AND c_last = ? ORDER BY c_first",
                (customer_wh, customer_dist, c_last.as_deref().unwrap_or("")),
            )
            .await
            .map_err(|source| crate::Error::MySql {
                action: "payment: select customer by last name".into(),
                source,
            })?;

        if rows.is_empty() {
            // Customer not found — skip (can happen with random data)
            tx.commit().await.map_err(|source| crate::Error::MySql {
                action: "payment: commit (no customer)".into(),
                source,
            })?;
            // Only the YTD updates committed on this path.
            let mut touched = Touched::new();
            touched.add(MutatedTable::Warehouse);
            touched.add(MutatedTable::District);
            watermarks.record(touched, bench_ts);
            return Ok(());
        }

        // Pick the middle customer (spec 2.5.2.2)
        let idx = rows.len().div_ceil(2) - 1;
        c_id = rows[idx].get(0).unwrap_or(0);
    }

    // 6. SELECT customer FOR UPDATE
    let c_row: Option<Row> = tx
        .exec_first(
            "SELECT c_first, c_middle, c_last, c_street_1, c_street_2, c_city, c_state, \
             c_zip, c_phone, c_credit, c_credit_lim, c_discount, c_balance, c_since \
             FROM customer WHERE c_w_id = ? AND c_d_id = ? AND c_id = ? FOR UPDATE",
            (customer_wh, customer_dist, c_id),
        )
        .await
        .map_err(|source| crate::Error::MySql {
            action: "payment: select customer for update".into(),
            source,
        })?;
    let Some(c_row) = c_row else {
        return Err(crate::Error::Arrow {
            action: "payment".into(),
            message: "customer row not found".into(),
        });
    };

    let c_credit: String = c_row.get(9).unwrap_or_default();

    // 7-8. Update customer (with data for "BC" credit)
    if c_credit.trim() == "BC" {
        let c_data_row: Option<(String,)> = tx
            .exec_first(
                "SELECT c_data FROM customer WHERE c_w_id = ? AND c_d_id = ? AND c_id = ?",
                (customer_wh, customer_dist, c_id),
            )
            .await
            .map_err(|source| crate::Error::MySql {
                action: "payment: select customer data".into(),
                source,
            })?;
        let Some((old_data,)) = c_data_row else {
            return Err(crate::Error::Arrow {
                action: "payment".into(),
                message: "customer data row not found".into(),
            });
        };

        let now_secs = std::time::SystemTime::now()
            .duration_since(std::time::SystemTime::UNIX_EPOCH)
            .unwrap_or_default()
            .as_secs();
        let new_prefix = format!(
            "| {c_id:4} {customer_dist:2} {customer_wh:4} {d_id:2} {w_id:4} ${h_amount:7.2} {now_secs}"
        );
        let mut new_data = new_prefix;
        let remaining = 500 - new_data.len().min(500);
        if remaining > 0 {
            let end = remaining.min(old_data.len());
            new_data.push_str(&old_data[..end]);
        }

        tx.exec_drop(
            "UPDATE customer SET c_balance = c_balance - ?, c_ytd_payment = c_ytd_payment + ?, \
             c_payment_cnt = c_payment_cnt + 1, c_data = ?, _bench_ts = ? \
             WHERE c_w_id = ? AND c_d_id = ? AND c_id = ?",
            (
                h_amount,
                h_amount_f64,
                new_data,
                bench_ts.mysql_value(),
                customer_wh,
                customer_dist,
                c_id,
            ),
        )
        .await
        .map_err(|source| crate::Error::MySql {
            action: "payment: update customer with data".into(),
            source,
        })?;
    } else {
        tx.exec_drop(
            "UPDATE customer SET c_balance = c_balance - ?, c_ytd_payment = c_ytd_payment + ?, \
             c_payment_cnt = c_payment_cnt + 1, _bench_ts = ? \
             WHERE c_w_id = ? AND c_d_id = ? AND c_id = ?",
            (
                h_amount,
                h_amount_f64,
                bench_ts.mysql_value(),
                customer_wh,
                customer_dist,
                c_id,
            ),
        )
        .await
        .map_err(|source| crate::Error::MySql {
            action: "payment: update customer".into(),
            source,
        })?;
    }

    // 9. INSERT history
    let history_data = format!("{w_name:>10}    {d_name:>10}");
    let history_ts = now_naive();
    tx.exec_drop(
        "INSERT INTO history (h_c_d_id, h_c_w_id, h_c_id, h_d_id, h_w_id, h_date, h_amount, h_data, _bench_ts) \
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)",
        (
            customer_dist,
            customer_wh,
            c_id,
            d_id,
            w_id,
            history_ts,
            h_amount,
            history_data,
            bench_ts.mysql_value(),
        ),
    )
    .await
    .map_err(|source| crate::Error::MySql {
        action: "payment: insert history".into(),
        source,
    })?;

    tx.commit().await.map_err(|source| crate::Error::MySql {
        action: "payment: commit".into(),
        source,
    })?;

    let mut touched = Touched::new();
    touched.add(MutatedTable::Warehouse);
    touched.add(MutatedTable::District);
    touched.add(MutatedTable::Customer);
    touched.add(MutatedTable::History);
    watermarks.record(touched, bench_ts);

    Ok(())
}

/// TPC-C Delivery transaction (4% default mix).
///
/// Delivers the oldest pending order for each of 10 districts.
/// Mirrors [`super::delivery::run`].
async fn run_delivery(
    conn: &mut mysql_async::Conn,
    rng: &mut impl Rng,
    warehouses: i32,
    watermarks: &Watermarks,
) -> Result<()> {
    let w_id = rng.random_range(1..=warehouses);
    let o_carrier_id = rng.random_range(1..=10);

    // One stamp per transaction; only districts that actually had a pending
    // order contribute writes, so the touched set is built as the loop runs.
    let bench_ts = BenchTs::now_mysql();
    let mut touched = Touched::new();

    let mut tx = conn
        .start_transaction(mysql_async::TxOpts::default())
        .await
        .map_err(|source| crate::Error::MySql {
            action: "begin delivery transaction".into(),
            source,
        })?;

    for d_id in 1..=10i32 {
        // 1. Find oldest undelivered order
        let rows: Vec<Row> = tx
            .exec(
                "SELECT no_o_id FROM new_order WHERE no_w_id = ? AND no_d_id = ? ORDER BY no_o_id ASC LIMIT 1 FOR UPDATE",
                (w_id, d_id),
            )
            .await
            .map_err(|source| crate::Error::MySql {
                action: "delivery: select new_order".into(),
                source,
            })?;

        if rows.is_empty() {
            continue;
        }

        let no_o_id: i32 = rows[0].get(0).unwrap_or(0);

        // 2. DELETE from new_order
        tx.exec_drop(
            "DELETE FROM new_order WHERE no_w_id = ? AND no_d_id = ? AND no_o_id = ?",
            (w_id, d_id, no_o_id),
        )
        .await
        .map_err(|source| crate::Error::MySql {
            action: "delivery: delete new_order".into(),
            source,
        })?;

        // 3. UPDATE orders with carrier
        tx.exec_drop(
            "UPDATE oorder SET o_carrier_id = ?, _bench_ts = ? WHERE o_w_id = ? AND o_d_id = ? AND o_id = ?",
            (o_carrier_id, bench_ts.mysql_value(), w_id, d_id, no_o_id),
        )
        .await
        .map_err(|source| crate::Error::MySql {
            action: "delivery: update oorder".into(),
            source,
        })?;
        touched.add(MutatedTable::Oorder);

        // 4. Get customer ID for this order
        let o_row: Option<(i32,)> = tx
            .exec_first(
                "SELECT o_c_id FROM oorder WHERE o_w_id = ? AND o_d_id = ? AND o_id = ?",
                (w_id, d_id, no_o_id),
            )
            .await
            .map_err(|source| crate::Error::MySql {
                action: "delivery: select oorder c_id".into(),
                source,
            })?;
        let Some((o_c_id,)) = o_row else {
            return Err(crate::Error::Arrow {
                action: "delivery".into(),
                message: "oorder row not found".into(),
            });
        };

        // 5. UPDATE order_line delivery date
        let delivery_d = now_naive();
        tx.exec_drop(
            "UPDATE order_line SET ol_delivery_d = ?, _bench_ts = ? WHERE ol_w_id = ? AND ol_d_id = ? AND ol_o_id = ?",
            (delivery_d, bench_ts.mysql_value(), w_id, d_id, no_o_id),
        )
        .await
        .map_err(|source| crate::Error::MySql {
            action: "delivery: update order_line".into(),
            source,
        })?;
        touched.add(MutatedTable::OrderLine);

        // 6. SUM order_line amounts
        let sum_row: Option<(Decimal,)> = tx
            .exec_first(
                "SELECT COALESCE(SUM(ol_amount), 0) FROM order_line WHERE ol_w_id = ? AND ol_d_id = ? AND ol_o_id = ?",
                (w_id, d_id, no_o_id),
            )
            .await
            .map_err(|source| crate::Error::MySql {
                action: "delivery: sum order_line amount".into(),
                source,
            })?;
        let Some((total_amount,)) = sum_row else {
            return Err(crate::Error::Arrow {
                action: "delivery".into(),
                message: "order_line sum row not found".into(),
            });
        };

        // 7. UPDATE customer balance
        tx.exec_drop(
            "UPDATE customer SET c_balance = c_balance + ?, c_delivery_cnt = c_delivery_cnt + 1, _bench_ts = ? WHERE c_w_id = ? AND c_d_id = ? AND c_id = ?",
            (total_amount, bench_ts.mysql_value(), w_id, d_id, o_c_id),
        )
        .await
        .map_err(|source| crate::Error::MySql {
            action: "delivery: update customer".into(),
            source,
        })?;
        touched.add(MutatedTable::Customer);
    }

    tx.commit().await.map_err(|source| crate::Error::MySql {
        action: "delivery: commit".into(),
        source,
    })?;

    // The new_order DELETE writes no stamp, and a delivery whose ten districts
    // were all empty wrote nothing at all — record only what was written.
    if !touched.is_empty() {
        watermarks.record(touched, bench_ts);
    }

    Ok(())
}

/// TPC-C `OrderStatus` transaction (4% default mix).
///
/// Read-only: look up the most recent order for a customer.
/// Mirrors [`super::order_status::run`].
async fn run_order_status(
    conn: &mut mysql_async::Conn,
    rng: &mut impl Rng,
    warehouses: i32,
) -> Result<()> {
    let w_id = rng.random_range(1..=warehouses);
    let d_id = rng.random_range(1..=10);

    // 60% by last name, 40% by customer ID (spec 2.6.1.2)
    let by_name = rng.random_range(0..100) < 60;
    let c_load: usize = rng.random_range(0..256);

    // Read-only in Postgres: no explicit transaction is used, so run directly on conn.
    let c_id: i32 = if by_name {
        let c_last = tpcc_rand::rand_c_last(rng, c_load);

        // Get count for name
        let cnt_row: Option<(i64,)> = conn
            .exec_first(
                "SELECT count(c_id) FROM customer WHERE c_w_id = ? AND c_d_id = ? AND c_last = ?",
                (w_id, d_id, c_last.clone()),
            )
            .await
            .map_err(|source| crate::Error::MySql {
                action: "order_status: count customer by last".into(),
                source,
            })?;
        let Some((name_cnt,)) = cnt_row else {
            return Err(crate::Error::Arrow {
                action: "order_status".into(),
                message: "customer count row not found".into(),
            });
        };
        let mut target = name_cnt;
        if target % 2 == 1 {
            target += 1;
        }

        let rows: Vec<Row> = conn
            .exec(
                "SELECT c_balance, c_first, c_middle, c_id FROM customer WHERE c_w_id = ? AND c_d_id = ? AND c_last = ? ORDER BY c_first",
                (w_id, d_id, c_last),
            )
            .await
            .map_err(|source| crate::Error::MySql {
                action: "order_status: select customer by last".into(),
                source,
            })?;

        if rows.is_empty() {
            return Ok(());
        }

        #[expect(clippy::cast_possible_truncation, clippy::cast_sign_loss)]
        let idx = ((target / 2) as usize).min(rows.len()) - 1;
        rows[idx.min(rows.len().saturating_sub(1))]
            .get(3)
            .unwrap_or(0)
    } else {
        tpcc_rand::rand_customer_id(rng)
    };

    // SELECT customer
    let _c_row: Option<Row> = conn
        .exec_first(
            "SELECT c_balance, c_first, c_middle, c_last FROM customer WHERE c_w_id = ? AND c_d_id = ? AND c_id = ?",
            (w_id, d_id, c_id),
        )
        .await
        .map_err(|source| crate::Error::MySql {
            action: "order_status: select customer by id".into(),
            source,
        })?;

    // SELECT latest order
    let o_row: Option<Row> = conn
        .exec_first(
            "SELECT o_id, o_carrier_id, o_entry_d FROM oorder WHERE o_w_id = ? AND o_d_id = ? AND o_c_id = ? ORDER BY o_id DESC LIMIT 1",
            (w_id, d_id, c_id),
        )
        .await
        .map_err(|source| crate::Error::MySql {
            action: "order_status: select latest order".into(),
            source,
        })?;

    if let Some(o_row) = o_row {
        let o_id: i32 = o_row.get(0).unwrap_or(0);

        // SELECT order lines
        let _ol_rows: Vec<Row> = conn
            .exec(
                "SELECT ol_i_id, ol_supply_w_id, ol_quantity, ol_amount, ol_delivery_d FROM order_line WHERE ol_w_id = ? AND ol_d_id = ? AND ol_o_id = ?",
                (w_id, d_id, o_id),
            )
            .await
            .map_err(|source| crate::Error::MySql {
                action: "order_status: select order_line".into(),
                source,
            })?;
    }

    Ok(())
}

/// TPC-C `StockLevel` transaction (4% default mix).
///
/// Read-only: count distinct items in recent orders with stock below threshold.
/// Mirrors [`super::stock_level::run`].
async fn run_stock_level(
    conn: &mut mysql_async::Conn,
    rng: &mut impl Rng,
    warehouses: i32,
) -> Result<()> {
    let w_id = rng.random_range(1..=warehouses);
    let d_id = rng.random_range(1..=10);
    let threshold = rng.random_range(10..=20);

    // Read-only in Postgres: no explicit transaction is used, so run directly on conn.

    // SELECT d_next_o_id
    let d_row: Option<(i32,)> = conn
        .exec_first(
            "SELECT d_next_o_id FROM district WHERE d_w_id = ? AND d_id = ?",
            (w_id, d_id),
        )
        .await
        .map_err(|source| crate::Error::MySql {
            action: "stock_level: select district".into(),
            source,
        })?;
    let Some((o_id,)) = d_row else {
        return Err(crate::Error::Arrow {
            action: "stock_level".into(),
            message: "district row not found".into(),
        });
    };

    // Count low-stock items in last 20 orders
    let _count_row: Option<(i64,)> = conn
        .exec_first(
            "SELECT COUNT(DISTINCT s_i_id) FROM order_line, stock WHERE ol_w_id = ? AND ol_d_id = ? AND ol_o_id < ? AND ol_o_id >= ? - 20 AND s_w_id = ? AND s_i_id = ol_i_id AND s_quantity < ?",
            (w_id, d_id, o_id, o_id, w_id, threshold),
        )
        .await
        .map_err(|source| crate::Error::MySql {
            action: "stock_level: count low stock".into(),
            source,
        })?;

    Ok(())
}
