[package]
name = "spice-cloud-client"
description = "HTTP client for the Spice Cloud API"
edition.workspace = true
homepage.workspace = true
license-file.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
snafu.workspace = true
url.workspace = true
