[package]
name = "spice-cloud-client"
description = "HTTP client for the Spice Cloud API"
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
snafu.workspace = true

[dev-dependencies]
insta = { workspace = true, features = ["filters", "json"] }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
uuid = { version = "1", features = ["v4"] }
