[package]
name = "chbench-driver"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true

[dependencies]
async-trait = { workspace = true }
chrono = { workspace = true }
rand = { workspace = true }
snafu = "0.8"
tokio = { workspace = true, features = ["macros", "rt", "time"] }
tokio-postgres = { workspace = true }
tokio-util = { workspace = true }
