[package]
name = "chbench-driver"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
publish = false

[dependencies]
arrow = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
datafusion-table-providers = { workspace = true, features = ["postgres", "mysql"] }
futures = { workspace = true }
governor = { workspace = true, features = ["std"] }
mysql_async = { workspace = true, features = ["rust_decimal"] }
rand = { workspace = true }
rust_decimal = { workspace = true, features = ["db-tokio-postgres"] }
secrecy = { workspace = true }
snafu = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["fs", "macros", "rt", "time"] }
tokio-postgres = { workspace = true }
tokio-util = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread"] }

[lints]
workspace = true
