[package]
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license-file.workspace = true
name = "db_connection_pool"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
arrow.workspace = true
async-stream = { workspace = true, optional = true }
async-trait.workspace = true
datafusion.workspace = true
datafusion-table-providers = { workspace = true }
futures.workspace = true
pkcs8 = { version = "0.10.2", features = [
  "encryption",
  "pem",
  "3des",
], optional = true }
secrecy.workspace = true
serde_json = { workspace = true, optional = true }
snafu.workspace = true
snowflake-api = { workspace = true, optional = true }
tokio = { workspace = true, optional = true, features = ["rt"] }
tokio-util = { workspace = true }
tracing.workspace = true
util = { path = "../util", features = ["datafusion"] }

[dev-dependencies]
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[features]
duckdb = [
  "datafusion-table-providers/duckdb",
  "datafusion-table-providers/duckdb-federation",
]
mysql = ["datafusion-table-providers/mysql"]
postgres = [
  "dep:tokio",
  "dep:async-stream",
  "datafusion-table-providers/postgres",
  "datafusion-table-providers/postgres-federation",
]
snowflake = [
  "dep:snowflake-api",
  "dep:pkcs8",
  "dep:serde_json",
]
sqlite = [
  "datafusion-table-providers/sqlite",
  "datafusion-table-providers/sqlite-federation",
]

[lints]
workspace = true
