[package]
name = "db_connection_pool"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[dependencies]
duckdb = { workspace = true,  features = ["bundled", "r2d2", "vtab", "vtab-arrow"] }
datafusion.workspace = true
async-trait.workspace = true
r2d2.workspace = true
snafu.workspace = true
tracing.workspace = true
futures.workspace = true
bb8.workspace = true
bb8-postgres.workspace = true
arrow_sql_gen = { path = "../arrow_sql_gen" }
arrow.workspace = true

[dev-dependencies]
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }