[package]
name = "duration-parse"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
publish.workspace = true
description = "Human-readable duration parsing and formatting for Spice.ai"

[dependencies]
snafu.workspace = true

[dev-dependencies]
