[package]
description = "Iceberg Hadoop Catalog"
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "hadoop_catalog"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
async-trait = { workspace = true }
futures = { workspace = true }
iceberg = { workspace = true }
opendal = "0.53.0"
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
arrow = { workspace = true, features = ["prettyprint"] }
arrow-array = { workspace = true }
ctor = "0.2.8"
insta = { version = "1.43" }
iceberg_test_utils = { version = "0.5.1", features = ["tests"] }

[features]