CREATE TABLE test_mysql_table (
  id SERIAL PRIMARY KEY,
  col_bit BIT(1),
  col_tiny TINYINT,
  col_short SMALLINT,
  col_long INT,
  col_longlong BIGINT,
  col_float FLOAT,
  col_double DOUBLE,
  col_timestamp TIMESTAMP,
  col_date DATE,
  col_time TIME,
  col_blob BLOB,
  col_varchar VARCHAR(255),
  col_string TEXT,
  col_var_string VARCHAR(255),
  col_decimal DECIMAL(10, 2),
  col_unsigned_int INT UNSIGNED,
  col_char CHAR(3),
  col_enum ENUM('option1', 'option2', 'option3'),
  col_set SET('apple', 'banana', 'cherry'),
  col_json JSON
);

INSERT INTO test_mysql_table (
  col_bit,
  col_tiny,
  col_short,
  col_long,
  col_longlong,
  col_float,
  col_double,
  col_timestamp,
  col_date,
  col_time,
  col_blob,
  col_varchar,
  col_string,
  col_var_string,
  col_decimal,
  col_unsigned_int,
  col_char,
  col_enum,
  col_set,
  col_json
) VALUES (
  1,
  1,
  1,
  1,
  1,
  1.1,
  1.1,
  '2019-01-01 00:00:00',
  '2019-01-01',
  '12:34:56',
  'blob',
  'varchar',
  'string',
  'var_string',
  1.11,
  10,
  'USA',
  'option1',
  'apple,banana',
  '{"name": "John", "age": 30, "is_active": true, "balance": 1234.56}'
);

INSERT INTO test_mysql_table (
  col_bit,
  col_tiny,
  col_short,
  col_long,
  col_longlong,
  col_float,
  col_double,
  col_timestamp,
  col_date,
  col_time,
  col_blob,
  col_varchar,
  col_string,
  col_var_string,
  col_decimal,
  col_unsigned_int,
  col_char,
  col_enum,
  col_list_string,
  col_list_int,
  col_json
) VALUES (
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
);
