-- TODO: Add Postgres BOOLEAN[] type back when DucKDB support accelerating Arrow Boolean List Type
-- Issue: https://github.com/spiceai/spiceai/issues/3138
CREATE TABLE test_postgresql_table (
  id SERIAL PRIMARY KEY,
  int2_column SMALLINT,
  int4_column INTEGER,
  int8_column BIGINT,
  float4_column REAL,
  float8_column DOUBLE PRECISION,
  text_column TEXT,
  varchar_column VARCHAR,
  bpchar_column BPCHAR,
  bool_column BOOLEAN,
  numeric_column NUMERIC,
  timestamp_column TIMESTAMP,
  date_column DATE,
  int2_array_column SMALLINT[],
  int4_array_column INTEGER[],
  int8_array_column BIGINT[],
  float4_array_column REAL[],
  float8_array_column DOUBLE PRECISION[],
  text_array_column TEXT[]
);

INSERT INTO test_postgresql_table (
  int2_column, 
  int4_column, 
  int8_column, 
  float4_column, 
  float8_column, 
  text_column, 
  varchar_column, 
  bpchar_column, 
  bool_column, 
  numeric_column, 
  timestamp_column, 
  date_column, 
  int2_array_column, 
  int4_array_column, 
  int8_array_column, 
  float4_array_column, 
  float8_array_column, 
  text_array_column
) VALUES 
-- First test row
(
  1, 
  2, 
  3, 
  4.0, 
  5.0, 
  'test', 
  'test', 
  'test', 
  true, 
  6.0, 
  CURRENT_TIMESTAMP, 
  CURRENT_DATE, 
  ARRAY[1, 2], 
  ARRAY[3, 4], 
  ARRAY[5, 6], 
  ARRAY[7.0, 8.0], 
  ARRAY[9.0, 10.0], 
  ARRAY['test1', 'test2']
), 
-- Second test row with NULLs
(
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL, 
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
),
-- Third test row
(
  10, 
  1000, 
  100000, 
  10.5, 
  20.25, 
  'row3_test', 
  'row3_varchar', 
  'row3_bpchar', 
  false, 
  123.45, 
  CURRENT_TIMESTAMP - INTERVAL '1 day', 
  CURRENT_DATE - INTERVAL '1 day', 
  ARRAY[10, 20, 30], 
  ARRAY[100, 200, 300], 
  ARRAY[1000, 2000, 3000], 
  ARRAY[10.1, 20.2, 30.3], 
  ARRAY[100.1, 200.2, 300.3], 
  ARRAY['value1', 'value2', 'value3']
);
