-- TODO: Add MySQL enum type back when DucKDB & SQLite accelerator support accelerating arrow dictionary type
-- https://github.com/spiceai/spiceai/issues/2891
-- https://github.com/spiceai/spiceai/issues/2889
CREATE TABLE test_mysql_table (
  ID SERIAL PRIMARY KEY,
  col_Bit BIT(1),
  col_Tiny TINYINT,
  col_Short SMALLINT,
  col_Long INT,
  col_Longlong BIGINT,
  col_Float FLOAT,
  col_Double DOUBLE,
  col_Timestamp TIMESTAMP,
  col_Date DATE,
  col_Time TIME,
  col_Blob BLOB,
  col_Varchar VARCHAR(255),
  col_String TEXT,
  col_Var_string VARCHAR(255),
  col_Decimal DECIMAL(10, 2),
  col_Unsigned_int INT UNSIGNED,
  col_Char CHAR(3),
  col_Set SET('apple', 'banana', 'cherry'),
  col_Json JSON
);

INSERT INTO test_mysql_table (
  col_Bit,
  col_Tiny,
  col_Short,
  col_Long,
  col_Longlong,
  col_Float,
  col_Double,
  col_Timestamp,
  col_Date,
  col_Time,
  col_Blob,
  col_Varchar,
  col_String,
  col_Var_string,
  col_Decimal,
  col_Unsigned_int,
  col_Char,
  col_Set,
  col_Json
) VALUES 
-- First test row
(
  1,
  1,
  1,
  1,
  1,
  1.1,
  1.1,
  '2019-01-01 00:00:00',
  '2019-01-01',
  '12:34:56',
  'blob',
  'varchar',
  'string',
  'var_string',
  1.11,
  10,
  'USA',
  'apple,banana',
  '{"name": "John", "age": 30, "is_active": true, "balance": 1234.56}'
), 
-- Second test row with NULLs
(
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
),
-- Third test row
(
  0,
  -5,
  32767,
  -2147483648,
  9223372036854775807,
  3.14,
  2.71828,
  '2029-01-01 00:00:00',
  '2029-01-01',
  '23:59:59',
  'binary_blob_test',
  'varchar_value',
  'longer_text_string_example',
  'short_var',
  99.99,
  12345,
  'CAN',
  'cherry',
  '{"product": "Laptop", "price": 999.99, "in_stock": false}'
);
