[package]
description = "Pushes Spice runtime metrics to an OpenTelemetry collector over gRPC or HTTP."
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license-file.workspace = true
name = "runtime-otel-push"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
opentelemetry-otlp.workspace = true
opentelemetry_sdk.workspace = true
reqwest.workspace = true
snafu.workspace = true
spicepod = { path = "../spicepod" }
tonic.workspace = true
tracing.workspace = true

[dev-dependencies]
tokio.workspace = true

[lints]
workspace = true
