name: Setup ODBC
description: 'composite action'

runs:
  using: 'composite'
  steps:
    - name: Install Databricks ODBC driver
      shell: bash
      run: |
        sudo apt-get install unixodbc unixodbc-dev unzip libsasl2-modules-gssapi-mit -y
        wget https://databricks-bi-artifacts.s3.us-east-2.amazonaws.com/simbaspark-drivers/odbc/2.8.2/SimbaSparkODBC-2.8.2.1013-Debian-64bit.zip
        unzip SimbaSparkODBC-2.8.2.1013-Debian-64bit.zip
        sudo dpkg -i simbaspark_2.8.2.1013-2_amd64.deb
        ls -lh /opt/simba/spark/lib/64/
        cat <<EOF > /tmp/odbcinst.ini
        [Databricks ODBC Driver]
        Description=Databricks ODBC Driver
        Driver=/opt/simba/spark/lib/64/libsparkodbc_sb64.so
        Setup=/opt/simba/spark/lib/64/libsparkodbc_sb64.so
        EOF
        sudo cp /tmp/odbcinst.ini /etc/odbcinst.ini

    - name: Install Athena ODBC driver
      shell: bash
      run: |
        sudo apt-get install alien -y
        wget https://downloads.athena.us-east-1.amazonaws.com/drivers/ODBC/v2.0.3.0/Linux/AmazonAthenaODBC-2.0.3.0.rpm
        sudo alien -i AmazonAthenaODBC-2.0.3.0.rpm
        ls -lh /opt/athena/odbc/lib/
        cat <<EOF > /tmp/odbcinst.ini
        [Amazon Athena ODBC Driver]
        Description=Amazon Athena ODBC Driver
        Driver=/opt/athena/odbc/lib/libathena-odbc.so
        Setup=/opt/athena/odbc/lib/libathena-odbc.so
        EOF
        cat /tmp/odbcinst.ini | sudo tee -a /etc/odbcinst.ini