/*
Copyright 2026 The Spice.ai OSS Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//! Safe Rust bindings to libnfs C library for NFS client operations.
//!
//! This crate provides a safe wrapper around the libnfs C library, enabling
//! NFS client operations in Rust applications.
//!
//! # Example
//! ```ignore
//! use libnfs::{Nfs, EntryType};
//! use nix::fcntl::OFlag;
//! use std::path::Path;
//!
//! let mut nfs = Nfs::new()?;
//! nfs.mount("server.example.com", "/export")?;
//!
//! let dir = nfs.opendir(Path::new("/"))?;
//! for entry in dir {
//!     let entry = entry?;
//!     println!("{}: {:?}", entry.path.display(), entry.d_type);
//! }
//! ```

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(unsafe_code)]
// Allow unsafe extern blocks from bindgen-generated code
#![allow(unsafe_op_in_unsafe_fn)]

// libnfs bindings target 64-bit platforms; refuse to compile on narrower pointer widths.
#[cfg(not(target_pointer_width = "64"))]
compile_error!("libnfs bindings require a 64-bit target pointer width");

mod sys {
    //! Raw FFI bindings generated by bindgen.
    // Allow deprecated items from generated bindings
    #![allow(deprecated)]
    #![allow(dead_code)]
    #![allow(clippy::upper_case_acronyms)]
    #![allow(clippy::pub_underscore_fields)]
    #![allow(clippy::struct_field_names)]
    // Bindgen generates #[allow(...)] attributes which violate allow_attributes lint
    #![allow(clippy::allow_attributes)]
    // SAFETY: The bindings are generated by bindgen from the libnfs C headers.
    // All extern functions are inherently unsafe as they call into C code.
    // Bindgen currently generates `extern "C"` blocks that are compatible with
    // Rust 2021; under Rust 2024 these are treated equivalently to
    // `unsafe extern "C"`, and we only call them from within explicit `unsafe`
    // blocks in this crate's safe wrapper APIs.
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

use nix::fcntl::OFlag;
use nix::sys::stat::Mode;
use snafu::{ResultExt, Snafu};

use std::ffi::{CStr, CString, NulError, c_char};
use std::mem::zeroed;
use std::os::unix::ffi::OsStrExt;
use std::path::{Path, PathBuf};
use std::ptr::{self, NonNull};
use std::rc::Rc;

pub use sys::{AUTH, nfs_stat_64, statvfs, timeval};

/// Error type for NFS operations.
#[derive(Debug, Snafu)]
#[snafu(visibility(pub))]
pub enum Error {
    /// Failed to initialize NFS context.
    #[snafu(display("Failed to initialize NFS context"))]
    ContextInitFailed,

    /// NFS operation failed with an error from the server.
    #[snafu(display("NFS operation failed: {message}"))]
    NfsOperationFailed { message: String },

    /// Path contains invalid characters (interior NUL byte).
    #[snafu(display("Invalid path: contains NUL byte"))]
    InvalidPath { source: NulError },

    /// Unknown or unsupported file type encountered.
    #[snafu(display("Unknown file type: {file_type}"))]
    UnknownFileType { file_type: u32 },
}

/// Result type for NFS operations.
pub type Result<T, E = Error> = std::result::Result<T, E>;

/// Smart pointer wrapper for the NFS context that handles cleanup on drop.
#[derive(Clone)]
struct NfsPtr(*mut sys::nfs_context);

impl Drop for NfsPtr {
    fn drop(&mut self) {
        if !self.0.is_null() {
            unsafe {
                sys::nfs_destroy_context(self.0);
            }
        }
    }
}

/// Check if a pointer is null and return an appropriate error.
fn check_mut_ptr<T>(ptr: *mut T) -> Result<*mut T> {
    if ptr.is_null() {
        ContextInitFailedSnafu.fail()
    } else {
        Ok(ptr)
    }
}

/// Check the return code from an NFS operation and convert errors.
fn check_retcode(ctx: *mut sys::nfs_context, code: i32) -> Result<()> {
    if code < 0 {
        unsafe {
            let err_str = sys::nfs_get_error(ctx);
            let message = if err_str.is_null() {
                // Defensive fallback: avoid undefined behavior if libnfs ever returns null
                "Unknown NFS error (libnfs returned null error string)".to_string()
            } else {
                CStr::from_ptr(err_str).to_string_lossy().into_owned()
            };
            NfsOperationFailedSnafu { message }.fail()
        }
    } else {
        Ok(())
    }
}

/// The main NFS client handle.
///
/// # Thread Safety
///
/// This type uses `Rc` for reference counting and is **not** thread-safe.
/// It does not implement `Send` or `Sync`. All operations on an `Nfs` handle
/// and its derived types (`NfsFile`, `NfsDirectory`) must occur on the same thread.
///
/// When using with async runtimes like Tokio, wrap NFS operations in
/// `tokio::task::spawn_blocking` to confine them to a single blocking thread.
#[derive(Clone)]
pub struct Nfs {
    context: Rc<NfsPtr>,
}

/// Represents the type of a directory entry.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum EntryType {
    Block,
    Character,
    Directory,
    File,
    NamedPipe,
    Symlink,
    Socket,
}

impl EntryType {
    fn from_ftype3(t: sys::ftype3) -> Result<Self> {
        match t {
            sys::ftype3_NF3BLK => Ok(Self::Block),
            sys::ftype3_NF3CHR => Ok(Self::Character),
            sys::ftype3_NF3DIR => Ok(Self::Directory),
            sys::ftype3_NF3REG => Ok(Self::File),
            sys::ftype3_NF3FIFO => Ok(Self::NamedPipe),
            sys::ftype3_NF3LNK => Ok(Self::Symlink),
            sys::ftype3_NF3SOCK => Ok(Self::Socket),
            _ => UnknownFileTypeSnafu { file_type: t }.fail(),
        }
    }
}

/// Information about a directory entry.
#[derive(Debug, Clone)]
pub struct DirEntry {
    pub path: PathBuf,
    pub inode: u64,
    pub d_type: EntryType,
    pub mode: Mode,
    pub size: u64,
    pub atime: sys::timeval,
    pub mtime: sys::timeval,
    pub ctime: sys::timeval,
    pub uid: u32,
    pub gid: u32,
    pub nlink: u32,
    pub dev: u64,
    pub rdev: u64,
    pub blksize: u64,
    pub blocks: u64,
    pub used: u64,
    pub atime_nsec: u32,
    pub mtime_nsec: u32,
    pub ctime_nsec: u32,
}

/// Handle to an open NFS directory for iteration.
///
/// # Thread Safety
///
/// This type uses `Rc` for reference counting and is **not** thread-safe.
/// See [`Nfs`] documentation for details on thread safety constraints.
#[derive(Clone)]
pub struct NfsDirectory {
    nfs: Rc<NfsPtr>,
    handle: *mut sys::nfsdir,
}

impl Drop for NfsDirectory {
    fn drop(&mut self) {
        if !self.handle.is_null() {
            unsafe {
                sys::nfs_closedir(self.nfs.0, self.handle);
            }
        }
    }
}

/// Handle to an open NFS file.
///
/// # Thread Safety
///
/// This type uses `Rc` for reference counting and is **not** thread-safe.
/// See [`Nfs`] documentation for details on thread safety constraints.
#[derive(Clone)]
pub struct NfsFile {
    nfs: Rc<NfsPtr>,
    handle: *mut sys::nfsfh,
}

impl Drop for NfsFile {
    fn drop(&mut self) {
        if !self.handle.is_null() {
            unsafe {
                sys::nfs_close(self.nfs.0, self.handle);
            }
        }
    }
}

impl Nfs {
    /// Create a new NFS client context.
    ///
    /// # Errors
    /// Returns an error if the NFS context cannot be initialized.
    pub fn new() -> Result<Self> {
        unsafe {
            let ctx = check_mut_ptr(sys::nfs_init_context())?;
            Ok(Self {
                context: Rc::new(NfsPtr(ctx)),
            })
        }
    }

    /// Set the NFS protocol version to use (3 or 4).
    ///
    /// # Errors
    /// Returns an error if setting the version fails.
    pub fn set_version(&self, version: i32) -> Result<()> {
        unsafe {
            check_retcode(
                self.context.0,
                sys::nfs_set_version(self.context.0, version),
            )?;
            Ok(())
        }
    }

    /// Set the UID to use for NFS operations.
    ///
    /// # Errors
    ///
    /// This function always succeeds on supported platforms.
    pub fn set_uid(&self, uid: i32) {
        unsafe {
            sys::nfs_set_uid(self.context.0, uid);
        }
    }

    /// Set the GID to use for NFS operations.
    ///
    /// # Errors
    ///
    /// This function always succeeds on supported platforms.
    pub fn set_gid(&self, gid: i32) {
        unsafe {
            sys::nfs_set_gid(self.context.0, gid);
        }
    }

    /// Enable debug logging at the specified level.
    ///
    /// # Errors
    ///
    /// This function always succeeds on supported platforms.
    pub fn set_debug(&self, level: i32) {
        unsafe {
            sys::nfs_set_debug(self.context.0, level);
        }
    }

    /// Set the number of TCP SYN retries.
    ///
    /// # Errors
    ///
    /// This function always succeeds on supported platforms.
    pub fn set_tcp_syncnt(&self, syncnt: i32) {
        unsafe {
            sys::nfs_set_tcp_syncnt(self.context.0, syncnt);
        }
    }

    /// Set the authentication context.
    ///
    /// # Errors
    ///
    /// This function always succeeds on supported platforms.
    pub fn set_auth(&self, auth: &mut AUTH) {
        unsafe {
            sys::nfs_set_auth(self.context.0, auth);
        }
    }

    /// Mount an NFS share.
    ///
    /// # Arguments
    /// * `server` - The NFS server hostname or IP address
    /// * `export_name` - The export path on the server
    ///
    /// # Errors
    /// Returns an error if the mount operation fails.
    pub fn mount(&self, server: &str, export_name: &str) -> Result<()> {
        let server = CString::new(server.as_bytes()).context(InvalidPathSnafu)?;
        let export = CString::new(export_name.as_bytes()).context(InvalidPathSnafu)?;
        unsafe {
            check_retcode(
                self.context.0,
                sys::nfs_mount(self.context.0, server.as_ptr(), export.as_ptr()),
            )?;
            Ok(())
        }
    }

    /// Open a directory for iteration.
    ///
    /// # Errors
    /// Returns an error if the directory cannot be opened.
    pub fn opendir(&self, path: &Path) -> Result<NfsDirectory> {
        let path = CString::new(path.as_os_str().as_bytes()).context(InvalidPathSnafu)?;
        unsafe {
            let mut dir_handle: *mut sys::nfsdir = ptr::null_mut();
            check_retcode(
                self.context.0,
                sys::nfs_opendir(self.context.0, path.as_ptr(), &raw mut dir_handle),
            )?;
            Ok(NfsDirectory {
                nfs: Rc::clone(&self.context),
                handle: dir_handle,
            })
        }
    }

    /// Open a file with the specified flags.
    ///
    /// # Supported flags
    /// * `O_APPEND`
    /// * `O_RDONLY`
    /// * `O_WRONLY`
    /// * `O_RDWR`
    /// * `O_SYNC`
    /// * `O_TRUNC` (only valid with `O_RDWR` or `O_WRONLY`)
    ///
    /// # Errors
    /// Returns an error if the file cannot be opened.
    pub fn open(&self, path: &Path, flags: OFlag) -> Result<NfsFile> {
        let path = CString::new(path.as_os_str().as_bytes()).context(InvalidPathSnafu)?;
        unsafe {
            let mut file_handle: *mut sys::nfsfh = ptr::null_mut();
            check_retcode(
                self.context.0,
                sys::nfs_open(
                    self.context.0,
                    path.as_ptr(),
                    flags.bits(),
                    &raw mut file_handle,
                ),
            )?;
            Ok(NfsFile {
                nfs: Rc::clone(&self.context),
                handle: file_handle,
            })
        }
    }

    /// Create a new file with the specified mode.
    ///
    /// This is a thin wrapper around the `libnfs` `nfs_creat` call, which only
    /// accepts a POSIX mode and does not support `OFlag`-style open flags. If you
    /// need to control flags such as `O_TRUNC`, `O_EXCL`, or `O_SYNC`, use
    /// [`Nfs::open`] with the desired [`OFlag`]s instead of this method.
    ///
    /// # Errors
    /// Returns an error if the file cannot be created.
    pub fn create(&self, path: &Path, mode: Mode) -> Result<NfsFile> {
        let path = CString::new(path.as_os_str().as_bytes()).context(InvalidPathSnafu)?;
        unsafe {
            let mut file_handle: *mut sys::nfsfh = ptr::null_mut();
            // mode_t is u16 on macOS, u32 on Linux; convert to i32 for the C API
            #[cfg(target_os = "macos")]
            let mode_i32 = i32::from(mode.bits());
            #[cfg(not(target_os = "macos"))]
            #[expect(clippy::cast_possible_wrap)]
            let mode_i32 = mode.bits() as i32;
            check_retcode(
                self.context.0,
                sys::nfs_creat(
                    self.context.0,
                    path.as_ptr(),
                    mode_i32,
                    &raw mut file_handle,
                ),
            )?;
            Ok(NfsFile {
                nfs: Rc::clone(&self.context),
                handle: file_handle,
            })
        }
    }

    /// Get file statistics (64-bit version).
    ///
    /// # Errors
    /// Returns an error if the stat operation fails.
    pub fn stat64(&self, path: &Path) -> Result<nfs_stat_64> {
        let path = CString::new(path.as_os_str().as_bytes()).context(InvalidPathSnafu)?;
        unsafe {
            let mut stat_buf: nfs_stat_64 = zeroed();
            check_retcode(
                self.context.0,
                sys::nfs_stat64(self.context.0, path.as_ptr(), &raw mut stat_buf),
            )?;
            Ok(stat_buf)
        }
    }

    /// Get symlink file statistics (64-bit version).
    ///
    /// # Errors
    /// Returns an error if the lstat operation fails.
    pub fn lstat64(&self, path: &Path) -> Result<nfs_stat_64> {
        let path = CString::new(path.as_os_str().as_bytes()).context(InvalidPathSnafu)?;
        unsafe {
            let mut stat_buf: nfs_stat_64 = zeroed();
            check_retcode(
                self.context.0,
                sys::nfs_lstat64(self.context.0, path.as_ptr(), &raw mut stat_buf),
            )?;
            Ok(stat_buf)
        }
    }

    /// Get filesystem statistics.
    ///
    /// # Errors
    /// Returns an error if the statvfs operation fails.
    pub fn statvfs(&self, path: &Path) -> Result<statvfs> {
        let path = CString::new(path.as_os_str().as_bytes()).context(InvalidPathSnafu)?;
        unsafe {
            let mut stat_buf: statvfs = zeroed();
            check_retcode(
                self.context.0,
                sys::nfs_statvfs(self.context.0, path.as_ptr(), &raw mut stat_buf),
            )?;
            Ok(stat_buf)
        }
    }

    /// Create a directory.
    ///
    /// # Errors
    /// Returns an error if the directory cannot be created.
    pub fn mkdir(&self, path: &Path) -> Result<()> {
        let path = CString::new(path.as_os_str().as_bytes()).context(InvalidPathSnafu)?;
        unsafe {
            check_retcode(
                self.context.0,
                sys::nfs_mkdir(self.context.0, path.as_ptr()),
            )?;
            Ok(())
        }
    }

    /// Remove a directory.
    ///
    /// # Errors
    /// Returns an error if the directory cannot be removed.
    pub fn rmdir(&self, path: &Path) -> Result<()> {
        let path = CString::new(path.as_os_str().as_bytes()).context(InvalidPathSnafu)?;
        unsafe {
            check_retcode(
                self.context.0,
                sys::nfs_rmdir(self.context.0, path.as_ptr()),
            )?;
            Ok(())
        }
    }

    /// Remove a file.
    ///
    /// # Errors
    /// Returns an error if the file cannot be removed.
    pub fn unlink(&self, path: &Path) -> Result<()> {
        let path = CString::new(path.as_os_str().as_bytes()).context(InvalidPathSnafu)?;
        unsafe {
            check_retcode(
                self.context.0,
                sys::nfs_unlink(self.context.0, path.as_ptr()),
            )?;
            Ok(())
        }
    }

    /// Rename a file or directory.
    ///
    /// # Errors
    /// Returns an error if the rename operation fails.
    pub fn rename(&self, oldpath: &Path, newpath: &Path) -> Result<()> {
        let old_path = CString::new(oldpath.as_os_str().as_bytes()).context(InvalidPathSnafu)?;
        let new_path = CString::new(newpath.as_os_str().as_bytes()).context(InvalidPathSnafu)?;
        unsafe {
            check_retcode(
                self.context.0,
                sys::nfs_rename(self.context.0, old_path.as_ptr(), new_path.as_ptr()),
            )?;
            Ok(())
        }
    }

    /// Create a symbolic link.
    ///
    /// # Errors
    /// Returns an error if the symlink cannot be created.
    pub fn symlink(&self, oldpath: &Path, newpath: &Path) -> Result<()> {
        let old_path = CString::new(oldpath.as_os_str().as_bytes()).context(InvalidPathSnafu)?;
        let new_path = CString::new(newpath.as_os_str().as_bytes()).context(InvalidPathSnafu)?;
        unsafe {
            check_retcode(
                self.context.0,
                sys::nfs_symlink(self.context.0, old_path.as_ptr(), new_path.as_ptr()),
            )?;
            Ok(())
        }
    }

    /// Create a hard link.
    ///
    /// # Errors
    /// Returns an error if the link cannot be created.
    pub fn link(&self, oldpath: &Path, newpath: &Path) -> Result<()> {
        let old_path = CString::new(oldpath.as_os_str().as_bytes()).context(InvalidPathSnafu)?;
        let new_path = CString::new(newpath.as_os_str().as_bytes()).context(InvalidPathSnafu)?;
        unsafe {
            check_retcode(
                self.context.0,
                sys::nfs_link(self.context.0, old_path.as_ptr(), new_path.as_ptr()),
            )?;
            Ok(())
        }
    }

    /// Read the target of a symbolic link.
    ///
    /// # Errors
    /// Returns an error if the readlink operation fails.
    pub fn readlink(&self, path: &Path, buf: &mut [u8]) -> Result<()> {
        let path = CString::new(path.as_os_str().as_bytes()).context(InvalidPathSnafu)?;
        // SAFETY: We target 64-bit minimum platforms; buffer size is reasonably small for symlinks.
        // Clamp to i32::MAX to avoid truncation on platforms where usize could exceed i32 range.
        #[expect(clippy::cast_possible_truncation, clippy::cast_possible_wrap)]
        let buf_len = buf.len().min(i32::MAX as usize) as i32;
        unsafe {
            check_retcode(
                self.context.0,
                sys::nfs_readlink(
                    self.context.0,
                    path.as_ptr(),
                    buf.as_mut_ptr().cast::<c_char>(),
                    buf_len,
                ),
            )?;
            Ok(())
        }
    }

    /// Change file mode.
    ///
    /// # Errors
    /// Returns an error if the chmod operation fails.
    pub fn chmod(&self, path: &Path, mode: Mode) -> Result<()> {
        let path = CString::new(path.as_os_str().as_bytes()).context(InvalidPathSnafu)?;
        // mode_t is u16 on macOS, u32 on Linux; convert to i32 for the C API
        #[cfg(target_os = "macos")]
        let mode_i32 = i32::from(mode.bits());
        #[cfg(not(target_os = "macos"))]
        #[expect(clippy::cast_possible_wrap)]
        let mode_i32 = mode.bits() as i32;
        unsafe {
            check_retcode(
                self.context.0,
                sys::nfs_chmod(self.context.0, path.as_ptr(), mode_i32),
            )?;
            Ok(())
        }
    }

    /// Change file ownership.
    ///
    /// # Errors
    /// Returns an error if the chown operation fails.
    pub fn chown(&self, path: &Path, uid: i32, gid: i32) -> Result<()> {
        let path = CString::new(path.as_os_str().as_bytes()).context(InvalidPathSnafu)?;
        unsafe {
            check_retcode(
                self.context.0,
                sys::nfs_chown(self.context.0, path.as_ptr(), uid, gid),
            )?;
            Ok(())
        }
    }

    /// Truncate a file to a specified length.
    ///
    /// # Errors
    /// Returns an error if the truncate operation fails.
    pub fn truncate(&self, path: &Path, len: u64) -> Result<()> {
        let path = CString::new(path.as_os_str().as_bytes()).context(InvalidPathSnafu)?;
        unsafe {
            check_retcode(
                self.context.0,
                sys::nfs_truncate(self.context.0, path.as_ptr(), len),
            )?;
            Ok(())
        }
    }

    /// Set the file creation mask.
    ///
    /// Returns the previous umask value.
    #[must_use]
    pub fn umask(&self, mask: u16) -> u16 {
        unsafe { sys::nfs_umask(self.context.0, mask) }
    }

    /// Set file access and modification times.
    ///
    /// # Errors
    /// Returns an error if the utimes operation fails.
    pub fn utimes(&self, path: &Path, times: &mut [timeval; 2]) -> Result<()> {
        let path = CString::new(path.as_os_str().as_bytes()).context(InvalidPathSnafu)?;
        unsafe {
            check_retcode(
                self.context.0,
                sys::nfs_utimes(self.context.0, path.as_ptr(), times.as_mut_ptr()),
            )?;
            Ok(())
        }
    }

    /// Check file access permissions.
    ///
    /// # Errors
    /// Returns an error if access is denied or the check fails.
    pub fn access(&self, path: &Path, mode: i32) -> Result<()> {
        let path = CString::new(path.as_os_str().as_bytes()).context(InvalidPathSnafu)?;
        unsafe {
            check_retcode(
                self.context.0,
                sys::nfs_access(self.context.0, path.as_ptr(), mode),
            )?;
            Ok(())
        }
    }

    /// Get the current working directory.
    ///
    /// # Errors
    ///
    /// Returns an error if libnfs fails to provide the current working directory.
    pub fn getcwd(&self) -> Result<PathBuf> {
        let mut cwd: *const c_char = ptr::null();
        unsafe {
            sys::nfs_getcwd(self.context.0, &raw mut cwd);
            let cwd = NonNull::new(cwd.cast_mut()).ok_or_else(|| Error::NfsOperationFailed {
                message: "libnfs returned a null working directory".to_string(),
            })?;
            let path_tmp = CStr::from_ptr(cwd.as_ptr()).to_string_lossy().into_owned();
            Ok(PathBuf::from(path_tmp))
        }
    }

    /// Change the current working directory.
    ///
    /// # Errors
    /// Returns an error if the directory change fails.
    pub fn chdir(&self, path: &Path) -> Result<()> {
        let path = CString::new(path.as_os_str().as_bytes()).context(InvalidPathSnafu)?;
        unsafe {
            check_retcode(
                self.context.0,
                sys::nfs_chdir(self.context.0, path.as_ptr()),
            )?;
            Ok(())
        }
    }

    /// Get the maximum read size supported by the server.
    ///
    /// Returns the maximum number of bytes that can be read in a single operation.
    #[must_use]
    pub fn get_readmax(&self) -> u64 {
        // nfs_get_readmax returns size_t which is u64 on Linux, usize on macOS.
        // Cast to u64 is lossless on 64-bit platforms.
        unsafe { sys::nfs_get_readmax(self.context.0) as u64 }
    }

    /// Get the maximum write size supported by the server.
    ///
    /// Returns the maximum number of bytes that can be written in a single operation.
    #[must_use]
    pub fn get_writemax(&self) -> u64 {
        // nfs_get_writemax returns size_t which is u64 on Linux, usize on macOS.
        // Cast to u64 is lossless on 64-bit platforms.
        unsafe { sys::nfs_get_writemax(self.context.0) as u64 }
    }
}

impl NfsFile {
    /// Read data from the file at a specific offset.
    ///
    /// # Errors
    /// Returns an error if the read operation fails or if count exceeds platform limits.
    pub fn pread(&self, count: u64, offset: u64) -> Result<Vec<u8>> {
        // SAFETY: We target 64-bit minimum platforms. On 64-bit systems, u64 fits in usize.
        // Check for truncation to handle potential future 128-bit platforms gracefully.
        let capacity = usize::try_from(count).map_err(|_| Error::NfsOperationFailed {
            message: format!("Read count {count} exceeds platform usize limit"),
        })?;
        // Allocate and initialize the buffer to avoid exposing uninitialized memory
        let mut buffer: Vec<u8> = vec![0u8; capacity];

        // The libnfs API changed between versions:
        // - Old API (< 4.0): nfs_pread(nfs, fh, buf, count, offset)
        // - New API (>= 4.0): nfs_pread(nfs, fh, offset, count, buf)
        #[cfg(libnfs_new_api)]
        let read_size = unsafe {
            sys::nfs_pread(
                self.nfs.0,
                self.handle,
                offset,
                count,
                buffer.as_mut_ptr().cast(),
            )
        };
        #[cfg(not(libnfs_new_api))]
        let read_size = unsafe {
            sys::nfs_pread(
                self.nfs.0,
                self.handle,
                buffer.as_mut_ptr().cast(),
                capacity,
                offset,
            )
        };

        check_retcode(self.nfs.0, read_size)?;
        #[expect(clippy::cast_sign_loss)]
        buffer.truncate(read_size as usize);
        Ok(buffer)
    }

    /// Read data from the beginning of the file.
    ///
    /// # Errors
    /// Returns an error if the read operation fails.
    pub fn read(&self, count: u64) -> Result<Vec<u8>> {
        self.pread(count, 0)
    }

    /// Write data to the file at a specific offset.
    ///
    /// # Errors
    /// Returns an error if the write operation fails.
    pub fn pwrite(&self, buffer: &[u8], offset: u64) -> Result<i32> {
        // The libnfs API changed between versions:
        // - Old API (< 4.0): nfs_pwrite(nfs, fh, buf, count, offset)
        // - New API (>= 4.0): nfs_pwrite(nfs, fh, offset, count, buf)
        #[cfg(libnfs_new_api)]
        let write_size = {
            // SAFETY: We target 64-bit minimum platforms, so usize -> u64 is safe
            let count = u64::try_from(buffer.len()).map_err(|_| Error::NfsOperationFailed {
                message: format!(
                    "Write buffer length {} exceeds platform u64 limit",
                    buffer.len()
                ),
            })?;
            unsafe {
                sys::nfs_pwrite(
                    self.nfs.0,
                    self.handle,
                    offset,
                    count,
                    buffer.as_ptr().cast(),
                )
            }
        };
        #[cfg(not(libnfs_new_api))]
        let write_size = unsafe {
            sys::nfs_pwrite(
                self.nfs.0,
                self.handle,
                buffer.as_ptr() as *mut _,
                buffer.len(),
                offset,
            )
        };

        check_retcode(self.nfs.0, write_size)?;
        Ok(write_size)
    }

    /// Write data to the beginning of the file.
    ///
    /// # Errors
    /// Returns an error if the write operation fails.
    pub fn write(&self, buffer: &[u8]) -> Result<i32> {
        self.pwrite(buffer, 0)
    }

    /// Get file statistics (64-bit version).
    ///
    /// # Errors
    /// Returns an error if the fstat operation fails.
    pub fn fstat64(&self) -> Result<nfs_stat_64> {
        unsafe {
            let mut stat_buf: nfs_stat_64 = zeroed();
            check_retcode(
                self.nfs.0,
                sys::nfs_fstat64(self.nfs.0, self.handle, &raw mut stat_buf),
            )?;
            Ok(stat_buf)
        }
    }

    /// Sync file data to the server.
    ///
    /// # Errors
    /// Returns an error if the fsync operation fails.
    pub fn fsync(&self) -> Result<()> {
        unsafe {
            check_retcode(self.nfs.0, sys::nfs_fsync(self.nfs.0, self.handle))?;
            Ok(())
        }
    }

    /// Truncate the file to a specified length.
    ///
    /// # Errors
    /// Returns an error if the truncate operation fails.
    pub fn ftruncate(&self, len: u64) -> Result<()> {
        unsafe {
            check_retcode(self.nfs.0, sys::nfs_ftruncate(self.nfs.0, self.handle, len))?;
            Ok(())
        }
    }

    /// Change file mode.
    ///
    /// # Errors
    /// Returns an error if the chmod operation fails.
    pub fn fchmod(&self, mode: i32) -> Result<()> {
        unsafe {
            check_retcode(self.nfs.0, sys::nfs_fchmod(self.nfs.0, self.handle, mode))?;
            Ok(())
        }
    }

    /// Change file ownership.
    ///
    /// # Errors
    /// Returns an error if the chown operation fails.
    pub fn fchown(&self, uid: i32, gid: i32) -> Result<()> {
        unsafe {
            check_retcode(
                self.nfs.0,
                sys::nfs_fchown(self.nfs.0, self.handle, uid, gid),
            )?;
            Ok(())
        }
    }
}

impl Iterator for NfsDirectory {
    type Item = Result<DirEntry>;

    fn next(&mut self) -> Option<Self::Item> {
        // SAFETY: The nfs_readdir function returns a pointer to a statically-allocated
        // nfsdirent structure that is valid until the next call to nfs_readdir or
        // nfs_closedir on this directory handle. We immediately copy all needed data
        // from the dirent structure before returning, so there's no use-after-free.
        // The dirent pointer is checked for null before dereferencing.
        // All fields accessed (name, type_, mode, size, etc.) are primitive types
        // or pointers that the C library guarantees are valid when dirent is non-null.
        unsafe {
            let dirent = sys::nfs_readdir(self.nfs.0, self.handle);
            if dirent.is_null() {
                return None;
            }

            // Defensive: check for null name pointer to avoid undefined behavior
            let name_ptr = (*dirent).name;
            if name_ptr.is_null() {
                return None;
            }

            let file_name = CStr::from_ptr(name_ptr);
            let d_type = match EntryType::from_ftype3((*dirent).type_) {
                Ok(ty) => ty,
                Err(e) => {
                    return Some(Err(e));
                }
            };
            // nfsdirent.mode is always u32 in libnfs, but Mode expects mode_t which is:
            // - u16 on macOS
            // - u32 on Linux
            // Cast to the appropriate type for the platform.
            #[cfg(target_os = "macos")]
            #[expect(clippy::cast_possible_truncation)]
            let mode = Mode::from_bits_truncate((*dirent).mode as u16);
            #[cfg(not(target_os = "macos"))]
            let mode = Mode::from_bits_truncate((*dirent).mode);
            Some(Ok(DirEntry {
                path: PathBuf::from(file_name.to_string_lossy().into_owned()),
                inode: (*dirent).inode,
                d_type,
                mode,
                size: (*dirent).size,
                atime: (*dirent).atime,
                mtime: (*dirent).mtime,
                ctime: (*dirent).ctime,
                uid: (*dirent).uid,
                gid: (*dirent).gid,
                nlink: (*dirent).nlink,
                dev: (*dirent).dev,
                rdev: (*dirent).rdev,
                blksize: (*dirent).blksize,
                blocks: (*dirent).blocks,
                used: (*dirent).used,
                atime_nsec: (*dirent).atime_nsec,
                mtime_nsec: (*dirent).mtime_nsec,
                ctime_nsec: (*dirent).ctime_nsec,
            }))
        }
    }
}

// Safety: NfsPtr contains a raw pointer to an NFS context, but the
// context is only accessed through the safe wrapper methods.
// The context itself is not thread-safe, so we don't implement Send/Sync.
// Usage should be confined to a single thread.
