[package]
description = "SFTP data connector for Spice.ai runtime"
edition.workspace = true
license-file.workspace = true
name = "connector-sftp"
publish.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
linkme.workspace = true
paste.workspace = true
runtime = { path = "../../runtime" }
snafu.workspace = true
tokio.workspace = true
url.workspace = true
