[package]
name = "connector-git"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license-file.workspace = true
description = "Git data connector for Spice.ai runtime"

[dependencies]
async-trait.workspace = true
data_components = { path = "../../data_components" }
datafusion.workspace = true
globset.workspace = true
opentelemetry.workspace = true
reqwest.workspace = true
runtime = { path = "../../runtime" }
secrecy.workspace = true
snafu.workspace = true
tokio.workspace = true
tracing.workspace = true
