[package]
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license-file.workspace = true
name = "document_parse"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
bytes.workspace = true
calamine = "0.28"
docx-rs = { git = "https://github.com/spiceai/docx-rs", rev = "2a85dce57d0128e2cd7c369545516c347cb8c529" }
pdf-extract = { path = "../vendor/pdf-extract" }
quick-xml = "0.38"
snafu.workspace = true
tokio = { workspace = true, features = ["sync"] }
zip = "7.2"
