/*
Copyright 2024-2025 The Spice.ai OSS Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
use arrow::{array::RecordBatch, datatypes::Schema};
use async_stream::stream;
use async_trait::async_trait;
use datafusion::{
    common::{Column, JoinType},
    datasource::{MemTable, TableProvider},
    error::DataFusionError,
    execution::SendableRecordBatchStream,
    logical_expr::{Expr as LogicalExpr, select_expr::SelectExpr, sqlparser::ast::Expr},
    physical_plan::stream::RecordBatchStreamAdapter,
    prelude::SessionContext,
    sql::sqlparser::ast::Ident,
};

use futures::{Stream, StreamExt};
use snafu::ResultExt;
use std::sync::Arc;

use crate::generation::{CandidateGeneration, InternalSnafu, Result};

/// [`PostApplyCandidateGeneration`] applies filter predicate and retrieves additional columns to a
///  [`CandidateGeneration`] that may not have full support.
pub struct PostApplyCandidateGeneration {
    inner: Arc<dyn CandidateGeneration>,

    /// The [`TableProvider`] associated with the [`CandidateGeneration`] method.
    /// Filters and additional projections pertain to this table.
    table_provider: Arc<dyn TableProvider>,

    /// Columns map rows from `table_provider` to candidates generated by `inner`'s [`CandidateGeneration::search`].
    primary_key: Vec<String>,

    ctx: Option<Arc<SessionContext>>,
}

/// Temporary table names used internally in SQL.
static TABLE_PROVIDER_TABLE_NAME: &str = "table_provider";
static CANDIDATE_GENERATION_TABLE_NAME: &str = "candidate_generation";

// Increase `LIMIT` clause by a multiple to allow for post-filtering.
static MAX_LIMIT_MULTIPLIER: usize = 100;

impl PostApplyCandidateGeneration {
    pub fn new(
        table: Arc<dyn TableProvider>,
        inner: Arc<dyn CandidateGeneration>,
        primary_key: Vec<String>,
    ) -> Self {
        Self {
            table_provider: table,
            inner,
            primary_key,
            ctx: None,
        }
    }

    #[must_use]
    pub fn with_ctx(mut self, ctx: Arc<SessionContext>) -> Self {
        self.ctx = Some(ctx);
        self
    }

    /// Return the subset of `filters` that are supported by the underlying [`CandidateGeneration`].
    fn supported_underlying_filters<'a>(&self, filters: &'a [&'a Expr]) -> Result<Vec<&'a Expr>> {
        let underlying_filters = self
            .inner
            .supports_filters_pushdown(filters)?
            .into_iter()
            .zip(filters.iter())
            .filter_map(|(supported, &filter)| if supported { Some(filter) } else { None })
            .collect::<Vec<_>>();

        Ok(underlying_filters)
    }

    /// Return the subset of `projections` that are supported by the underlying [`CandidateGeneration`].
    fn supported_underlying_projection<'a>(
        &self,
        projections: &[&'a Expr],
    ) -> Result<Vec<&'a Expr>> {
        let supported = self.inner.supports_columns(projections)?;
        let underlying_projection = supported
            .into_iter()
            .zip(projections.iter())
            .filter_map(|(supported, &expr)| if supported { Some(expr) } else { None })
            .collect::<Vec<_>>();

        Ok(underlying_projection)
    }

    async fn apply_postprocessing(
        &self,
        stream: SendableRecordBatchStream,
        remaining_filters: &[&Expr],
        remaining_projection: &[&Expr],
        limit: usize,
    ) -> Result<SendableRecordBatchStream> {
        let ctx = self.ctx.clone().unwrap_or(Arc::new(SessionContext::new()));
        let _ = ctx
            .register_table(TABLE_PROVIDER_TABLE_NAME, Arc::clone(&self.table_provider))
            .boxed()
            .context(InternalSnafu)?;

        let (new_schema, strm) = Self::postprocessing_stream(
            stream,
            ctx,
            self.primary_key.clone(),
            remaining_filters
                .iter()
                .copied()
                .map(Clone::clone)
                .collect(),
            remaining_projection
                .iter()
                .copied()
                .map(Clone::clone)
                .collect(),
            limit,
        )
        .await;

        Ok(Box::pin(RecordBatchStreamAdapter::new(new_schema, strm)))
    }

    /// For each [`RecordBatch`] provided, add the remaining columns (joining on primary keys), and apply the appropriate filters.
    async fn postprocessing_stream(
        mut stream: SendableRecordBatchStream,
        ctx: Arc<SessionContext>,
        primary_key: Vec<String>,
        remaining_filters: Vec<Expr>,
        remaining_projection: Vec<Expr>,
        limit: usize,
    ) -> (
        Arc<Schema>,
        impl Stream<Item = Result<RecordBatch, DataFusionError>>,
    ) {
        let mut schema = stream.schema();
        let mut remaining_limit = limit;
        let s = stream! {
            while let Some(item) = stream.next().await {
                let batch = item?;
                let schema = batch.schema();
                let t = match MemTable::try_new(Arc::clone(&schema), vec![vec![batch]]) {
                    Ok(t) => t,
                    Err(e) => {
                        yield Err(e);
                        continue;
                    }
                };

                if let Err(e) = ctx.register_table(CANDIDATE_GENERATION_TABLE_NAME, Arc::new(t)) {
                    yield Err(e);
                    continue;
                }

                // Convert to `SelectExpr` to avoid ambiguity between tables.
                let mut cols: Vec<_> = schema.fields.iter().map(|f|  SelectExpr::Expression(LogicalExpr::Column(Column::new(
                    Some(CANDIDATE_GENERATION_TABLE_NAME),
                    f.name().clone(),
                )))).collect();

                cols.append(&mut remaining_projection.iter().filter_map(|s| {
                    match s {
                        // Intentionally ignore `quote_style`. `DataFrame::select` will reapply.
                        Expr::Identifier(Ident{value,..}) => Some(SelectExpr::Expression(LogicalExpr::Column(Column::new(Some(TABLE_PROVIDER_TABLE_NAME), value)))),
                        _ => None
                    }
                }).collect::<Vec<_>>());

                let mut sql = ctx.table(CANDIDATE_GENERATION_TABLE_NAME).await?.join_on(
                    ctx.table(TABLE_PROVIDER_TABLE_NAME).await?,
                    JoinType::Inner,
                    primary_key.iter().map(|pk|
                        LogicalExpr::Column(Column::new(Some(CANDIDATE_GENERATION_TABLE_NAME), pk))
                            .eq(LogicalExpr::Column(Column::new(Some(TABLE_PROVIDER_TABLE_NAME), pk)))
                    )
                )?;

                if !remaining_filters.is_empty() {
                    let filter_expr = sql.parse_sql_expr(remaining_filters
                        .iter()
                        .map(ToString::to_string)
                        .collect::<Vec<_>>()
                        .join(" AND ").as_str())?;

                    sql = sql.filter(filter_expr)?;
                }
                sql = sql.select(cols)?;

                match sql.collect().await {
                    Ok(batches) => {
                        for batch in batches {
                            if remaining_limit > 0 {
                                let num_rows = batch.num_rows();
                                if remaining_limit < num_rows {
                                    yield Ok(batch.slice(0, remaining_limit));
                                    remaining_limit = 0;
                                    break;
                                }
                                yield Ok(batch);
                                remaining_limit = remaining_limit.saturating_sub(num_rows);
                            }
                        }
                    }
                    Err(e) => {
                        yield Err(e);
                    }
                }
                // Early exit on `LIMIT` clause
                if remaining_limit == 0 {
                    break;
                }
            }
        };

        // Peek at the first item to infer the schema.
        let mut s = Box::pin(s.peekable());

        match s.as_mut().peek().await {
            Some(Ok(batch)) => schema = batch.schema(),
            Some(Err(e)) => {
                tracing::warn!(
                    "Failed to infer schema while augmenting search candidate stream: {e}. Using as is"
                );
            }
            None => {}
        }
        (schema, s)
    }
}

#[async_trait]
impl CandidateGeneration for PostApplyCandidateGeneration {
    async fn search(
        &self,
        query: String,
        opt_filters: &[&Expr],
        addition_projection: &[&Expr],
        limit: usize,
    ) -> Result<SendableRecordBatchStream> {
        let underlying_filters = self.supported_underlying_filters(opt_filters)?;
        let underlying_projection = self.supported_underlying_projection(addition_projection)?;

        let unapplied_filters: Vec<&Expr> = opt_filters
            .iter()
            .filter(|&&f| !underlying_filters.contains(&f))
            .copied()
            .collect::<Vec<_>>();
        let unapplied_projection: Vec<&Expr> = addition_projection
            .iter()
            .filter(|&&p| !underlying_projection.contains(&p))
            .copied()
            .collect::<Vec<_>>();

        let need_post_apply = !unapplied_filters.is_empty() || !unapplied_projection.is_empty();
        let underlying_limit = if unapplied_filters.is_empty() {
            limit
        } else {
            // Will stream one batch at a time, so not going to full table scan underlying.
            MAX_LIMIT_MULTIPLIER * limit
        };
        let underlying = self
            .inner
            .search(
                query,
                underlying_filters.as_slice(),
                underlying_projection.as_slice(),
                underlying_limit,
            )
            .await?;

        // If there are no unapplied filters or projections, we can return the underlying stream directly.
        if !need_post_apply {
            return Ok(underlying);
        }

        self.apply_postprocessing(
            underlying,
            unapplied_filters.as_slice(),
            unapplied_projection.as_slice(),
            limit,
        )
        .await
    }

    fn supports_filters_pushdown(&self, filters: &[&Expr]) -> Result<Vec<bool>> {
        Ok(vec![true; filters.len()])
    }

    fn supports_columns(&self, projection: &[&Expr]) -> Result<Vec<bool>> {
        Ok(vec![true; projection.len()])
    }

    fn value_derived_from(&self) -> String {
        self.inner.value_derived_from()
    }
}

#[cfg(feature = "text_search")]
#[cfg(test)]
mod tests {

    use std::sync::Arc;

    use crate::generation::CandidateGeneration;
    use crate::generation::text_search::tests::{create_basic_index, validate_result};
    use crate::generation::{
        post_apply::PostApplyCandidateGeneration, text_search::FullTextSearchFieldIndex,
    };
    use arrow::{
        array::{RecordBatch, StringArray, UInt64Array},
        datatypes::{DataType, Field, Schema},
    };
    use datafusion::sql::sqlparser::dialect::GenericDialect;
    use datafusion::sql::sqlparser::parser::Parser;
    use datafusion::{
        datasource::{MemTable, TableProvider},
        logical_expr::sqlparser::ast::Expr,
    };

    // Keep in sync with `crate::generation::text_search::tests::create_basic_index`.
    fn create_table_provider() -> Arc<dyn TableProvider> {
        let schema = Schema::new(vec![
            Field::new("title", DataType::Utf8, false),
            Field::new("body", DataType::Utf8, false),
            Field::new("year_published", DataType::UInt64, false),
            Field::new("author", DataType::Utf8, true),
            Field::new("isbn", DataType::Utf8, false),
        ]);

        let title = StringArray::from(vec![
            "The Old Man and the Sea",
            "Of Mice and Men",
            "Frankenstein",
        ]);

        let body = StringArray::from(vec![
            "He was an old man who fished alone in a skiff in the Gulf Stream and he had gone \
            eighty-four days now without taking a fish.",
            "A few miles south of Soledad, the Salinas River drops in close to the hillside \
            bank and runs deep and green. The water is warm too, for it has slipped twinkling \
            over the yellow sands in the sunlight before reaching the narrow pool. On one \
            side of the river the golden foothill slopes curve up to the strong and rocky \
            Gabilan Mountains, but on the valley side the water is lined with fish and trees—willows \
            fresh and green with every spring, carrying in their lower leaf junctures the \
            debris of the winter's flooding; and sycamores with mottled, white, recumbent \
            limbs and branches that arch over the pool.",
            "You will rejoice to hear that no disaster has accompanied the commencement of an \
            enterprise which you have regarded with such evil forebodings.  I arrived here \
            yesterday, and my first task is to assure my dear sister of my welfare and \
            increasing confidence in the success of getting fish.",
        ]);

        let year_published = UInt64Array::from(vec![1952, 1937, 1818]);
        let author = StringArray::from(vec!["Ernest Hemingway", "John Steinbeck", "Mary Shelley"]);

        let isbn = StringArray::from(vec![
            "978-0-684-80122-3",
            "978-0-14-017739-8",
            "978-0-19-953715-7",
        ]);

        let rb = RecordBatch::try_new(
            Arc::new(schema.clone()),
            vec![
                Arc::new(title),
                Arc::new(body),
                Arc::new(year_published),
                Arc::new(author),
                Arc::new(isbn),
            ],
        )
        .expect("Failed to create RecordBatch");

        Arc::new(
            MemTable::try_new(schema.into(), vec![vec![rb]]).expect("Failed to create MemTable"),
        )
    }

    fn expr_from_sql(sql: &str) -> Expr {
        let mut parser = Parser::new(&GenericDialect {})
            .try_with_sql(sql)
            .expect("Failed to parse SQL");
        parser
            .parse_expr()
            .unwrap_or_else(|_| panic!("Failed to parse expression `{sql}`"))
    }

    #[tokio::test]
    async fn test_filter() {
        let fts = FullTextSearchFieldIndex::try_new(
            &create_basic_index(),
            "body".to_string(),
            vec!["title".to_string()],
            None,
        )
        .expect("failed to create FullTextSearch");

        let table_provider = create_table_provider();
        let post_apply = PostApplyCandidateGeneration::new(
            table_provider,
            Arc::new(fts),
            vec!["title".to_string()],
        );

        let year_published = expr_from_sql("year_published >= 1900");
        let result = post_apply
            .search("fish".into(), &[&year_published], &[], 3)
            .await;

        let rb_as_value = validate_result(result).await;
        insta::assert_json_snapshot!(rb_as_value);
    }

    #[tokio::test]
    async fn test_projection() {
        let fts = FullTextSearchFieldIndex::try_new(
            &create_basic_index(),
            "body".to_string(),
            vec![],
            None,
        )
        .expect("failed to create FullTextSearch");

        let table_provider = create_table_provider();
        let post_apply = PostApplyCandidateGeneration::new(
            table_provider,
            Arc::new(fts),
            vec!["title".to_string()],
        );

        let year_published = expr_from_sql("year_published");
        let author = expr_from_sql("author");
        let result = post_apply
            .search("fish".into(), &[], &[&year_published, &author], 3)
            .await;

        let rb_as_value = validate_result(result).await;
        insta::assert_json_snapshot!(rb_as_value);
    }
}
