[package]
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license-file.workspace = true
name = "runtime-query-engine"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
arrow.workspace = true
arrow-schema.workspace = true
async-trait.workspace = true
datafusion.workspace = true
globset.workspace = true
snafu.workspace = true
