---
name: ai benchmark (nsql)

on:
  workflow_dispatch:
    inputs:
      model_option:
        description: 'Which model do you want to test? (Default is ALL)'
        required: false
        type: choice
        options:
          - 'all'
          - 'gpt-5.1'
          - 'gpt-5-mini'
          - 'o3-mini'
          - 'llama3-3B-Instruct'
          - 'claude-sonnet-4-5'
          - 'grok4'
        default: 'all'
  schedule:
    - cron: '0 5 * * 2,5' # Every Monday and Thursday at 10pm PST (5am UTC next day)

concurrency:
  # Allow only one workflow per any non-trunk branch.
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.ref_name == 'trunk' && github.sha || 'any-sha' }}
  cancel-in-progress: true

jobs:
  build-testoperator:
    name: Build testoperator
    runs-on: 'spiceai-macos'
    steps:
      - uses: actions/checkout@v6

      - name: Build Testoperator
        uses: ./.github/actions/build-testoperator
        with:
          install_to_system_path: 'false'
          upload_artifact: 'true'

  build-spiced:
    name: Build spiced
    runs-on: 'spiceai-macos'
    steps:
      - uses: actions/checkout@v6

      - name: Set up Rust
        uses: ./.github/actions/setup-rust
        with:
          os: darwin

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build spiced
        if: matrix.target.target_os != 'darwin'
        run: |
          make -C bin/spiced SPICED_NON_DEFAULT_FEATURES="models"

      - name: make spiced executable
        if: matrix.target.target_os != 'windows'
        run: |
          mv target/release/spiced spiced
          chmod +x spiced

      - name: Save spice artifact
        uses: actions/upload-artifact@v5
        with:
          name: spiced
          path: spiced

  setup-matrix:
    name: Setup matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setup-matrix.outputs.result }}

    steps:
      - name: Set up matrix
        uses: actions/github-script@v8
        id: setup-matrix
        with:
          script: |
            const matrix = [
              { name: "gpt-5.1" },
              { name: "gpt-5-mini" },
              { name: "o3-mini" },
              { name: "llama3-3B-Instruct" },
              { name: "claude-sonnet-4-5" },
              { name: "grok4" },
            ];

            const model_option = context.payload.inputs?.model_option || 'all';
            let filtered = matrix;

            if (model_option !== 'all') {
              filtered = filtered.filter(m => m.name === model_option);
            }

            return filtered;

  run-testoperator:
    name: tpch_nsql benchmark
    needs:
      - build-testoperator
      - build-spiced
      - setup-matrix
    runs-on: 'spiceai-macos'
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        target: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v6

      - name: Download testoperator
        uses: actions/download-artifact@v6
        with:
          name: testoperator-darwin

      - name: Download spiced
        uses: actions/download-artifact@v6
        with:
          name: spiced

      - name: Mark binaries executable
        run: |
          chmod +x ./testoperator
          chmod +x ./spiced

      - name: Run tpch_nsql evals
        env:
          SPICE_OPENAI_API_KEY: ${{ secrets.SPICE_SECRET_OPENAI_API_KEY }}
          SPICE_HF_TOKEN: ${{ secrets.SPICE_SECRET_HF_TOKEN }}
          SPICE_ANTHROPIC_API_KEY: ${{ secrets.SPICE_SECRET_ANTHROPIC_API_KEY }}
          SPICE_XAI_API_KEY: ${{ secrets.SPICE_SECRET_XAI_API_KEY }}
          SPICEAI_BENCHMARK_METRICS_KEY: ${{ secrets.SPICEAI_BENCHMARK_METRICS_KEY }}
        run: |
          ./testoperator run evals \
            -s $GITHUB_WORKSPACE/spiced \
            -p test/spicepods/models/nsql_bench.yaml \
            -d $GITHUB_WORKSPACE/test/nsql_bench/data \
            --ready-wait 180 \
            --metrics
