name: E2E Test CI (models)

on:
  workflow_run:
    workflows:
      - E2E Test CI
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.event.workflow_run.id }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  setup-matrix:
    name: Setup strategy matrix
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      matrix: ${{ steps.setup.outputs.result }}
    steps:
      - name: Set up matrix
        id: setup
        uses: actions/github-script@v8
        with:
          script: |
            const targets = [
              {
                name: "Linux x64",
                runner: "spiceai-dev-runners",
                target_os: "linux",
                target_arch: "x86_64",
                target_arch_go: "amd64"
              },
              {
                name: "macOS aarch64 (Apple Silicon)",
                runner: "spiceai-macos",
                target_os: "darwin",
                target_arch: "aarch64",
                target_arch_go: "arm64"
              }
            ];

            const parentEvent = context.payload.workflow_run.event;
            if (parentEvent === "pull_request") {
              return [targets[0]];
            }
            return targets;

  test_openai_model:
    name: 'openai model (${{ matrix.target.target_os }}-${{ matrix.target.target_arch }})'
    timeout-minutes: 5
    runs-on: ${{ matrix.target.runner }}
    needs:
      - setup-matrix
    if: ${{ github.event.workflow_run.conclusion == 'success' && needs.setup-matrix.outputs.matrix != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          fetch-depth: 1

      - name: download artifacts - build_${{ matrix.target.target_os }}_${{ matrix.target.target_arch }}
        uses: dawidd6/action-download-artifact@ac66b43f0e6a346234dd65d4d0c8fbb31cb316e5 # v11
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          run_id: ${{ github.event.workflow_run.id }}
          name: build_${{ matrix.target.target_os }}_${{ matrix.target.target_arch }}
          path: ./build

      - name: Install spice
        uses: ./.github/actions/install-spice
        with:
          build-path: ./build

      - name: Init spice app
        run: |
          cp ./test/models/spicepod_openai.yml ./spicepod.yaml
          cat ./spicepod.yaml

      - name: Start spice runtime
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SPICE_OPENAI_API_KEY: ${{ secrets.SPICE_SECRET_OPENAI_API_KEY }}
        run: |
          spice run &> spice.log &

      - name: Wait for Spice runtime is ready
        timeout-minutes: 1
        run: |
          while [[ "$(curl -s http://localhost:8090/v1/ready)" != "ready" ]]; do sleep 1; done

      - name: Install expect (linux)
        if: matrix.target.target_os == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y expect

      - name: Install expect (macOS)
        if: matrix.target.target_os == 'darwin' && matrix.target.runner != 'spiceai-macos'
        run: |
          brew install expect

      - name: Test vector search
        run: |
          ./test/models/search_01.exp

      - name: Test chat
        run: |
          ./test/models/chat_01.exp

      - name: Stop spice and check logs
        if: always()
        run: |
          killall spice || true
          cat spice.log

  test_hf_model:
    name: 'huggingface model (${{ matrix.target.target_os }}-${{ matrix.target.target_arch }})'
    timeout-minutes: 10
    runs-on: ${{ matrix.target.runner }}
    needs:
      - setup-matrix
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      fail-fast: false
      matrix:
        target:
          - name: 'macOS aarch64 (Apple Silicon)'
            runner: 'spiceai-macos'
            target_os: 'darwin'
            target_arch: 'aarch64'
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          fetch-depth: 1

      - name: download artifacts - build_${{ matrix.target.target_os }}_${{ matrix.target.target_arch }}
        uses: dawidd6/action-download-artifact@ac66b43f0e6a346234dd65d4d0c8fbb31cb316e5 # v11
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          run_id: ${{ github.event.workflow_run.id }}
          name: build_${{ matrix.target.target_os }}_${{ matrix.target.target_arch }}
          path: ./build

      - name: Install spice
        uses: ./.github/actions/install-spice
        with:
          build-path: ./build

      - name: Init spice app
        run: |
          cp ./test/models/spicepod_hf.yml ./spicepod.yaml
          cat ./spicepod.yaml

      - name: Start spice runtime
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SPICE_OPENAI_API_KEY: ${{ secrets.SPICE_SECRET_OPENAI_API_KEY }}
        run: |
          spice run &> spice.log &

      - name: Wait for Spice runtime is ready
        timeout-minutes: 5
        run: |
          while [[ "$(curl -s http://localhost:8090/v1/ready)" != "ready" ]]; do sleep 1; done

      - name: Install expect (linux)
        if: matrix.target.target_os == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y expect

      - name: Install expect (macOS)
        if: matrix.target.target_os == 'darwin' && matrix.target.runner != 'spiceai-macos'
        run: |
          brew install expect

      - name: Test vector search
        run: |
          ./test/models/search_01.exp

      # Local model does not support tools so we check that it can respond only
      - name: Test chat
        run: |
          ./test/models/chat_01_simple.exp

      - name: Stop spice and check logs
        if: always()
        run: |
          killall spice || true
          cat spice.log
