name: Enforce PR labels

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]
  merge_group:
    types: [checks_requested]
jobs:
  enforce-label:
    runs-on: ubuntu-latest
    steps:
    - uses: yogevbd/enforce-label-action@2.2.2
      if: github.event_name == 'pull_request'
      with:
        REQUIRED_LABELS_ANY: "kind/refactor,kind/bug,kind/enhancement,kind/documentation,kind/optimization,kind/dependencies"
        REQUIRED_LABELS_ANY_DESCRIPTION: "Select at least one label ['kind/refactor','kind/bug','kind/enhancement','kind/documentation', 'kind/optimization', 'kind/dependencies']"
        BANNED_LABELS: "invalid,wontfix,nomerge,duplicate"
