name: Enforce Pulls with Spice

on:
  pull_request_target:
    types:
      [labeled, unlabeled, opened, edited, synchronize, assigned, unassigned]
  merge_group:
    types: [checks_requested]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.event.merge_group.head_ref }}
  cancel-in-progress: true

jobs:
  enforce-pull-with-spice:
    runs-on: self-hosted
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: spiceai/pulls-with-spice-action@61ef22e4a17be07209f0811fbfe4f0deb2e490a4 # v2.0.0
        if: github.event_name == 'pull_request_target'
        with:
          require_title_min_length: '10'
          required_label_prefixes: 'kind/,area/'
          banned_labels: 'invalid,wontfix,nomerge,duplicate'
          require_assignee: 'true'
          auto_label: 'true'
          auto_label_size: 'true'
          auto_label_type: 'true'
          auto_assign_author: 'true'
