---
name: financebench

on:
  workflow_dispatch:
    inputs:
      model_option:
        description: 'Which model do you want to test? (Default is ALL)'
        required: false
        type: choice
        options:
          - 'all'
          - 'gpt-4o'
          - 'gpt-4.1'
          - 'gpt-5'
          - 'o1'
          - 'o3-mini'
          - 'o4-mini'
        default: 'all'
      search_option:
        description: 'Which search configuration should be used (Default is embedding)'
        required: false
        type: choice
        options:
          - 'embedding'
          - 'hybrid'
          - 'full_text'
          - 's3_vectors'
        default: 'embedding'
  schedule:
    - cron: '0 4 * * 2,5' # Every Monday and Thursday at 8pm PST (4am UTC next day)

concurrency:
  # Allow only one workflow per any non-trunk branch.
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.ref_name == 'trunk' && github.sha || 'any-sha' }}
  cancel-in-progress: true

jobs:
  build-testoperator:
    name: Build testoperator
    runs-on: 'spiceai-macos'
    steps:
      - uses: actions/checkout@v6

      - name: Build Testoperator
        uses: ./.github/actions/build-testoperator
        with:
          install_to_system_path: 'false'
          upload_artifact: 'true'
          force_rebuild: 'true'
          download_from_minio: 'false'
  build-spiced:
    name: Build spiced
    runs-on: 'spiceai-macos'
    steps:
      - uses: actions/checkout@v6

      - name: Set up Rust
        uses: ./.github/actions/setup-rust
        with:
          os: darwin

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build spiced
        if: matrix.target.target_os != 'darwin'
        run: |
          make -C bin/spiced SPICED_NON_DEFAULT_FEATURES="models"

      - name: make spiced executable
        if: matrix.target.target_os != 'windows'
        run: |
          mv target/release/spiced spiced
          chmod +x spiced

      - name: Save spice artifact
        uses: actions/upload-artifact@v5
        with:
          name: spiced
          path: spiced

  setup-matrix:
    name: Setup matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setup-matrix.outputs.result }}

    steps:
      - name: Set up matrix
        uses: actions/github-script@v8
        id: setup-matrix
        with:
          script: |

            const matrix = [
              { name: "gpt-4o", run_on_schedule: false },
              { name: "gpt-4.1", run_on_schedule: true },
              { name: "gpt-5", run_on_schedule: true },
              { name: "o1", run_on_schedule: false },
              { name: "o3-mini", run_on_schedule: false },
              { name: "o4-mini", run_on_schedule: true }
            ];

            let filtered = matrix;
            if (context.eventName === 'schedule') {
              filtered = filtered.filter(m => m.run_on_schedule === true);
            }
            else {
              const model_option = context.payload.inputs.model_option;
              if (model_option !== 'all') {
                filtered = filtered.filter(m => m.name === model_option);
              }
            }
            // Default to `embedding[openai]` for manual and scheduled runs. Override below.
            filtered = filtered.map((m) => {
                m.spicepod = "./test/spicepods/financebench/embedding[openai].yaml";
                return m;
            });

            if (context.eventName !== 'schedule') {
              const search_option = context.payload.inputs.search_option;
              if (search_option=== 'hybrid') {
                filtered = filtered.map((m) => {
                    m.spicepod = "./test/spicepods/financebench/hybrid[openai].yaml";
                    return m;
                });
              }
              if (search_option === 'full_text') {
                filtered = filtered.map((m) => {
                    m.spicepod = "./test/spicepods/financebench/fts[openai].yaml";
                    return m;
                });
              }
              if (search_option === 's3vectors') {
                filtered = filtered.map((m) => {
                    m.spicepod = "./test/spicepods/financebench/embedding[s3vector].yaml";
                    return m;
                });
              }
            }
            return filtered;

  run-testoperator:
    name: benchmark
    needs:
      - build-testoperator
      - build-spiced
      - setup-matrix
    runs-on: 'spiceai-macos'
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        target: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v6

      - name: Download testoperator
        uses: actions/download-artifact@v6
        with:
          name: testoperator-darwin

      - name: Download spiced
        uses: actions/download-artifact@v6
        with:
          name: spiced

      - name: Mark binaries executable
        run: |
          chmod +x ./testoperator
          chmod +x ./spiced

      - name: Run FinanceBench evals
        env:
          SPICEAI_FINANCEBENCH_API_KEY: ${{ secrets.SPICE_SECRET_SPICEAI_FINANCEBENCH_API_KEY}}
          OPENAI_API_KEY: ${{ secrets.SPICE_SECRET_OPENAI_API_KEY }}
          SPICEAI_BENCHMARK_METRICS_KEY: ${{ secrets.SPICEAI_BENCHMARK_METRICS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_VECTORS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_VECTORS_SECRET }}
          AWS_REGION: 'us-east-1'
        run: |
          ./testoperator run evals \
            -s $GITHUB_WORKSPACE/spiced \
            -z ./test/spicepods/financebench/core \
            -p ${{ matrix.target.spicepod }} \
            --model ${{ matrix.target.name }} \
            --ready-wait 180 \
            --metrics
