name: Generate Acknowledgements

on:
  workflow_dispatch:

  pull_request:
    branches:
      - trunk

jobs:
  generate:
    name: Generate Acknowledgements
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Acknowledgements
        shell: bash
        run: |
          make generate-acknowledgements

      - run: |
          cat acknowledgements.md
