name: pr - helm-lint

on:
  pull_request:
    branches:
      - trunk
      - release-*
      - release/*
      - feature-*
    paths:
      - 'deploy/chart/**'

jobs:
  lint-helm:
    name: Helm Lint
    runs-on: spiceai-macos

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 1

      - name: Set up Helm
        uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5

      - name: Lint Helm chart
        run: helm lint deploy/chart/
