---
name: integration tests

on:
  pull_request:
    branches:
      - trunk
      - release-*

  workflow_dispatch:

env:
  CONTAINER_REGISTRY: spiceaitestimages.azurecr.io/

jobs:
  build:
    name: Integration Tests
    runs-on: ubuntu-latest-16-cores
    steps:
      - uses: actions/checkout@v4

      - name: Login to ACR
        uses: docker/login-action@v3
        # This will fail for forks, so we only run it for the main repo
        if: github.repository == 'spiceai/spiceai'
        with:
          registry: spiceaitestimages.azurecr.io
          username: spiceai-repo-pull
          password: ${{ secrets.AZCR_PASSWORD }}

      # Change the CONTAINER_REGISTRY to public.ecr.aws/docker/library/ if this is a fork
      - name: Use public ECR for forks
        if: github.repository != 'spiceai/spiceai'
        run: echo "CONTAINER_REGISTRY=public.ecr.aws/docker/library/" >> $GITHUB_ENV

      - name: Pull the Postgres/MySQL images
        run: |
          echo ${{ env.CONTAINER_REGISTRY }}
          docker pull ${{ env.CONTAINER_REGISTRY }}postgres:latest
          docker pull ${{ env.CONTAINER_REGISTRY }}mysql:latest

      - name: Set up Rust
        uses: ./.github/actions/setup-rust
        with:
          os: 'linux'

      - name: Set up Spice.ai API Key
        run: |
          echo 'SPICEAI_API_KEY="${{ secrets.SPICE_SECRET_SPICEAI_KEY }}"' > .env

      - name: Run integration test
        env:
          SPICE_SECRET_SPICEAI_KEY: ${{ secrets.SPICE_SECRET_SPICEAI_KEY }}
        run: |
          if [ -n "$SPICE_SECRET_SPICEAI_KEY" ]; then
            make test-integration
          else
            make test-integration-without-spiceai-dataset
          fi
