---
name: integration tests (llms)

on:
  push:
    branches:
      - trunk
      - release-*
    paths:
      - "crates/llms/**"

  workflow_dispatch:
    inputs:
      run:
        description: "Which groups of models to run"
        required: true
        default: "all"
        type: choice
        options:
          - "all"
          - "hosted"
          - "networked"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.ref_name == 'trunk' && github.sha || 'any-sha' }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Test Binary
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: ./.github/actions/setup-rust
        with:
          os: "darwin"

      # Build the test binary without running tests
      - name: Build LLMs integration test binary
        run: |
          TEST_BINARY_PATH=$(cargo test -p llms --test integration --features metal --no-run --message-format=json | jq -r 'select(.reason == "compiler-artifact" and (.target.kind | contains(["test"])) and .executable != null) | .executable')
          cp $TEST_BINARY_PATH ./llms_integration_test

      # Upload the test binary as an artifact
      - name: Upload test binary
        uses: actions/upload-artifact@v4
        with:
          name: llms-integration-test-binary
          path: ./llms_integration_test
          retention-days: 1

  test-hosted:
    name: Self-hosted LLMs Integration Tests
    needs: build
    permissions: read-all
    if: ${{ github.event_name == 'push' || github.event.inputs.run == 'all' || github.event.inputs.run == 'hosted' }}
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v4
      - name: Run hosted integration tests
        uses: ./.github/actions/run-llm-integration-tests
        with:
          model_allowlist: "local_phi3,hf_phi3"
          networked: "false"

  test-networked:
    name: Networked LLMs Integration Tests
    needs: build
    permissions: read-all
    if: ${{ github.event_name == 'push' || github.event.inputs.run == 'all' || github.event.inputs.run == 'networked' }}
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v4
      - name: Run networked integration tests
        uses: ./.github/actions/run-llm-integration-tests
        with:
          model_allowlist: "anthropic,openai,xai"
          networked: "true"
        env:
          SPICE_SECRET_OPENAI_API_KEY: ${{ secrets.SPICE_SECRET_OPENAI_API_KEY }}
          SPICE_SECRET_ANTHROPIC_API_KEY: ${{ secrets.SPICE_SECRET_ANTHROPIC_API_KEY }}
          SPICE_SECRET_XAI_API_KEY: ${{ secrets.SPICE_SECRET_XAI_API_KEY }}
