---
name: integration tests (models)

on:
  push:
    branches:
      - trunk
      - release/*
  pull_request_target:
    branches:
      - trunk
      - release-*
      - release/*
      - feature-*
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
      - 'README.md'
      - 'Makefile'
      - 'CONTRIBUTING.md'
      - 'SECURITY.md'
      - 'LICENSE'
      - '.github/**'
      - 'version.txt'
      - '.schema/**'
      - '.vscode/**'
      - 'deploy/**'
      - 'install/**'
      - 'media/**'
      - 'monitoring/**'
      - 'acknowledgements.md'
      - 'Dockerfile*'
      - 'bin/spice/**'

  workflow_dispatch:
    inputs:
      run_all_tests:
        description: 'Run all tests'
        type: boolean
        required: false
        default: false

concurrency:
  # Allow only one workflow per any non-trunk branch.
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}-${{ github.ref_name == 'trunk' && github.sha || 'any-sha' }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Test Binary
    runs-on: 'spiceai-macos'
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Rust
        uses: ./.github/actions/setup-rust
        with:
          os: 'darwin'

      - name: Install Nextest
        run: |
          curl -LsSf https://get.nexte.st/latest/darwin | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin

      # Build the test archive without running tests
      - name: Build AI integration test archive
        env:
          # Metal runners do not have `xcrun metal`
          # See `https://github.com/EricLBuehler/mistral.rs/pull/1311`
          MISTRALRS_METAL_PRECOMPILE: 0
        run: |

          FEATURES="flightsql,models,metal,s3_vectors"
           if [[ "${{ github.event.inputs.run_all_tests }}" == "true" ]]; then
             FEATURES="${FEATURES},bedrock,extended_tests"
             echo "Including extended_tests"
           else
             echo "Excluding extended_tests"
           fi

           cargo nextest archive -p runtime --test integration_models --features ${FEATURES} --archive-file integration_models.tar.zst

      # Upload the test archive as an artifact
      - name: Upload test archive
        uses: actions/upload-artifact@v4
        with:
          name: ai-integration-test-archive
          path: ./integration_models.tar.zst
          retention-days: 1

  test-openai:
    name: Test OpenAI Models
    needs: build
    permissions: read-all
    runs-on: 'spiceai-macos'
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Download test archive
        uses: actions/download-artifact@v5
        with:
          name: ai-integration-test-archive
          path: ./integration_test

      - name: Install Nextest
        run: |
          curl -LsSf https://get.nexte.st/latest/darwin | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin

      - name: Set up Open.ai API Key
        run: |
          echo 'SPICE_OPENAI_API_KEY="${{ secrets.SPICE_SECRET_OPENAI_API_KEY }}"' > .env

      - name: Run integration test
        env:
          SPICE_SECRET_OPENAI_API_KEY: ${{ secrets.SPICE_SECRET_OPENAI_API_KEY }}
        run: |
          if [ -z "$SPICE_SECRET_OPENAI_API_KEY" ] ; then
            echo "Error: OpenAI API key is not defined."
            exit 1
          fi
          INSTA_WORKSPACE_ROOT="${PWD}" CARGO_MANIFEST_DIR="${PWD}" cargo nextest run --workspace-remap "${PWD}" --archive-file ./integration_test/integration_models.tar.zst openai_test

      - name: Run Beta functionality embeddings test
        env:
          SPICE_SECRET_OPENAI_API_KEY: ${{ secrets.SPICE_SECRET_OPENAI_API_KEY }}
        run: |
          if [ -z "$SPICE_SECRET_OPENAI_API_KEY" ] ; then
            echo "Error: OpenAI API key is not defined."
            exit 1
          fi
          INSTA_WORKSPACE_ROOT="${PWD}" CARGO_MANIFEST_DIR="${PWD}" cargo nextest run --workspace-remap "${PWD}" --archive-file ./integration_test/integration_models.tar.zst openai_embeddings_beta_requirements

  test-hf:
    name: Test Huggingface Models
    needs: build
    if: ${{ github.event.inputs.run_all_tests == 'true' }}
    permissions: read-all
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Download test archive
        uses: actions/download-artifact@v5
        with:
          name: ai-integration-test-archive
          path: ./integration_test

      - name: Install Nextest
        run: |
          curl -LsSf https://get.nexte.st/latest/darwin | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin

      - name: Run integration test
        env:
          SPICE_HF_TOKEN: ${{ secrets.SPICE_SECRET_HF_TOKEN }}
        run: |
          if [ -z "$SPICE_HF_TOKEN" ] ; then
            echo "Error: Hugging Face API Token is not defined."
            exit 1
          fi
          INSTA_WORKSPACE_ROOT="${PWD}" CARGO_MANIFEST_DIR="${PWD}" cargo nextest run --workspace-remap "${PWD}" --archive-file ./integration_test/integration_models.tar.zst huggingface_test

      - name: Run Beta functionality embedding tests
        env:
          SPICE_HF_TOKEN: ${{ secrets.SPICE_SECRET_HF_TOKEN }}
        run: |
          if [ -z "$SPICE_HF_TOKEN" ] ; then
            echo "Error: Hugging Face API Token is not defined."
            exit 1
          fi
          INSTA_WORKSPACE_ROOT="${PWD}" CARGO_MANIFEST_DIR="${PWD}" cargo nextest run --workspace-remap "${PWD}" --archive-file ./integration_test/integration_models.tar.zst hf_embeddings_beta_requirements

  test-local:
    name: Test Local Models
    needs: build
    permissions: read-all
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Download test archive
        uses: actions/download-artifact@v5
        with:
          name: ai-integration-test-archive
          path: ./integration_test

      - name: Install Nextest
        run: |
          curl -LsSf https://get.nexte.st/latest/darwin | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin

      - name: Run Beta functionality embedding tests
        run: |
          INSTA_WORKSPACE_ROOT="${PWD}" CARGO_MANIFEST_DIR="${PWD}" cargo nextest run --workspace-remap "${PWD}" --archive-file ./integration_test/integration_models.tar.zst local_embeddings_beta_requirements

  test-bedrock:
    name: Test Bedrock Models
    needs: build
    if: ${{ github.event.inputs.run_all_tests == 'true' }}
    permissions: read-all
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Download test archive
        uses: actions/download-artifact@v5
        with:
          name: ai-integration-test-archive
          path: ./integration_test

      - name: Install Nextest
        run: |
          curl -LsSf https://get.nexte.st/latest/darwin | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin

      - name: Run Beta functionality embedding tests
        env:
          AWS_BEDROCK_KEY: ${{ secrets.AWS_BEDROCK_KEY }}
          AWS_BEDROCK_SECRET: ${{ secrets.AWS_BEDROCK_SECRET }}
        run: |
          INSTA_WORKSPACE_ROOT="${PWD}" CARGO_MANIFEST_DIR="${PWD}" cargo nextest run --workspace-remap "${PWD}" --archive-file ./integration_test/integration_models.tar.zst bedrock_test

  test-workers:
    name: Test Workers
    needs: build
    permissions: read-all
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Download test archive
        uses: actions/download-artifact@v5
        with:
          name: ai-integration-test-archive
          path: ./integration_test

      - name: Install Nextest
        run: |
          curl -LsSf https://get.nexte.st/latest/darwin | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin

      - name: Set up Open.ai API Key
        run: |
          echo 'SPICE_OPENAI_API_KEY="${{ secrets.SPICE_SECRET_OPENAI_API_KEY }}"' > .env

      - name: Run integration test
        env:
          SPICE_SECRET_OPENAI_API_KEY: ${{ secrets.SPICE_SECRET_OPENAI_API_KEY }}
        run: |
          if [ -z "$SPICE_SECRET_OPENAI_API_KEY" ] ; then
            echo "Error: OpenAI API key is not defined."
            exit 1
          fi
          INSTA_WORKSPACE_ROOT="${PWD}" CARGO_MANIFEST_DIR="${PWD}" cargo nextest run --workspace-remap "${PWD}" --archive-file ./integration_test/integration_models.tar.zst workers

  test-search:
    name: Test Search
    needs: build
    permissions: read-all
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Download test archive
        uses: actions/download-artifact@v5
        with:
          name: ai-integration-test-archive
          path: ./integration_test

      - name: Install Nextest
        run: |
          curl -LsSf https://get.nexte.st/latest/darwin | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin

      - name: Set up Open.ai API Key
        run: |
          echo 'SPICE_OPENAI_API_KEY="${{ secrets.SPICE_SECRET_OPENAI_API_KEY }}"' > .env

      - name: Run integration test
        env:
          SPICE_SECRET_OPENAI_API_KEY: ${{ secrets.SPICE_SECRET_OPENAI_API_KEY }}
          AWS_S3_VECTORS_KEY: ${{ secrets.AWS_S3_VECTORS_KEY }}
          AWS_S3_VECTORS_SECRET: ${{ secrets.AWS_S3_VECTORS_SECRET }}
        run: |
          if [ -z "$SPICE_SECRET_OPENAI_API_KEY" ] ; then
            echo "Error: OpenAI API key is not defined."
            exit 1
          fi
          INSTA_WORKSPACE_ROOT="${PWD}" CARGO_MANIFEST_DIR="${PWD}" cargo nextest run --workspace-remap "${PWD}" --archive-file ./integration_test/integration_models.tar.zst search
