---
name: Check for forbidden licenses

# Checks for any forbidden/copyleft licenses using their SPDX identifiers
# (https://spdx.org/licenses/)

# List of copyleft licenses derived from Blue Oak Council Guide to Copyleft
# https://blueoakcouncil.org/copyleft

# List of forbidden licenses derived from Google License Classifier
# (https://github.com/google/licenseclassifier)

on:
  pull_request:
    branches:
      - trunk
      - release-*

jobs:
  license-check:
    name: license check
    runs-on: ubuntu-latest
    env:
      GOVER: 1.17
      FORBIDDEN_LICENSE_CHECK: |
        grep -E "GPL|CC|APSL|CPAL|EUPL|NPOSL|OSL|SSPL|Parity|RPL|QPL|Sleepycat|copyleft|CDDL|CPL|EPL|ErlPL|IPL|MPL|MS-RL|SPL|WTFPL|Facebook|Commons-Clause" | grep . && echo "copyleft/forbidden license detected!" || echo "ok" 
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GOVER }}

      - name: Install go-licences
        run: go get github.com/google/go-licenses

      - name: Check spice licenses
        working-directory: cmd/spice
        run: |
          go-licenses csv . |& ${{ env.FORBIDDEN_LICENSE_CHECK }}
      
      - name: Check spiced licenses
        working-directory: cmd/spiced
        run: |
          go-licenses csv . |& ${{ env.FORBIDDEN_LICENSE_CHECK }}

      - name: Install root packages
        run: |
          yarn install

      - name: Check root package licenses
        run: |
          npx license-checker |& ${{ env.FORBIDDEN_LICENSE_CHECK }}

      - name: Install dashboard packages
        working-directory: dashboard
        run: |
          yarn install

      - name: Check dashboard package licenses
        working-directory: dashboard
        run: |
          npx license-checker |& ${{ env.FORBIDDEN_LICENSE_CHECK }}

      - name: Set up Python 3.8.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.11

      - name: Install AI packages
        working-directory: ai/src
        run: |
          pip install -r requirements/production.txt
          pip install -r requirements/development.txt
          pip install -r requirements/common.txt

      - name: Install pip-licenses
        working-directory: ai/src
        run: |
          pip install pip-licenses

      - name: Check AI package licenses
        working-directory: ai/src
        run: |
          pip-licenses |& grep -E ${{ env.FORBIDDEN_LICENSE_CHECK }}