---
name: pr_test

on:
  pull_request:
    branches:
      - trunk
      - release-*

jobs:
  proto_unchanged:
    name: validate protobuf files unchanged
    runs-on: ubuntu-latest
    env:
      GOVER: 1.17

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GOVER }}

      - name: write .netrc
        env:
          PAT: ${{ secrets.PAT_PHILLIP }}
        run: |
          echo "machine github.com login phillipleblanc password $PAT" > ~/.netrc

      - name: go get github.com/spiceai/data-components-contrib
        env:
          GONOSUMDB: github.com/spiceai/data-components-contrib
        run: go get github.com/spiceai/data-components-contrib

      - name: Make venv for proto gen
        working-directory: ai/src
        run: make venv-gen-proto

      - name: Run gen-proto check diff
        run: |
          wget https://github.com/protocolbuffers/protobuf/releases/download/v3.17.3/protoc-3.17.3-linux-x86_64.zip
          unzip protoc-3.17.3-linux-x86_64.zip -d protoc
          sudo cp -r protoc/include/google/ /usr/local/include/
          sudo chmod -R 755 /usr/local/include/google
          sudo cp protoc/bin/protoc /usr/local/bin/
          sudo chmod +x /usr/local/bin/protoc
          rm -r protoc protoc-3.17.3-linux-x86_64.zip
          make init-proto
          export PATH="$PATH:$(go env GOPATH)/bin"
          make gen-proto check-proto-diff

  spiced-and-spice:
    name: go test spiced & spice
    runs-on: ubuntu-latest
    env:
      GOVER: 1.17

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GOVER }}

      - name: write .netrc
        env:
          PAT: ${{ secrets.PAT_PHILLIP }}
        run: |
          echo "machine github.com login phillipleblanc password $PAT" > ~/.netrc

      - name: go get github.com/spiceai/data-components-contrib
        env:
          GONOSUMDB: github.com/spiceai/data-components-contrib
        run: go get github.com/spiceai/data-components-contrib

      - name: Build and copy dashboard
        working-directory: dashboard
        run: make

      - name: Test dashboard
        run: yarn test
        working-directory: dashboard

      - name: go vet
        run: go vet ./...

      - name: go test
        run: go test ./...

  aiengine:
    name: test aiengine
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.11

      - name: Cache PIP
        id: cache-pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ hashFiles('ai/src/requirements/development.txt') }}

      - name: Install Python dependencies
        working-directory: ai/src
        run: make venv-dev

      - name: Run tests
        working-directory: ai/src
        run: make test
