---
name: pr_test

on:
  pull_request:
    branches:
      - trunk
      - release-*

jobs:
  spiced-and-spice:
    name: go test spiced & spice
    runs-on: ubuntu-latest
    env:
      GOVER: 1.16

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GOVER }}

      - name: go vet
        run: go vet ./...

      - name: go test
        run: go test ./...

  aiengine:
    name: test aiengine
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.11
      - name: Install Python dependencies
        working-directory: ai/src
        run: make venv
      - name: Run tests
        working-directory: ai/src
        run: make test
