name: spiced_docker

on:
  push:
    branches:
      - trunk
      - release-*
    tags:
      - v*

  workflow_dispatch:

jobs:
  build:
    name: Build Spice ${{ matrix.target_os }}_${{ matrix.target_arch }} Docker image
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        target_arch: [amd64]
        include:
          - os: ubuntu-latest
            target_os: linux

    steps:
      - uses: actions/checkout@v2

      - name: Set REL_VERSION from version.txt
        run: python ./.github/scripts/get_release_version.py

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Package Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Sets latest tags for release
        run: |
          echo "LATEST_GHCR_TAG=ghcr.io/spiceai/spiceai:latest" >> $GITHUB_ENV
          echo "LATEST_DOCKERHUB_TAG=spiceai/spiceai:latest" >> $GITHUB_ENV
        if: endsWith(env.REL_VERSION, '-rc') == false

      - name: Build and push Docker images
        id: docker_build
        uses: docker/build-push-action@v2.5.0
        with:
          context: .
          file: docker/Dockerfile
          platforms: ${{ matrix.target_os }}/${{ matrix.target_arch }}
          push: ${{ github.event_name != 'pull_request' && startswith(github.ref, 'refs/tags/v') }}
          build-args: |
            REL_VERSION=${{ env.REL_VERSION }}
          tags: |
            ghcr.io/spiceai/spiceai:${{ env.REL_VERSION }}
            ghcr.io/spiceai/spiceai:${{ env.REL_VERSION }}-${{ matrix.target_os }}-${{ matrix.target_arch }}
            spiceai/spiceai:${{ env.REL_VERSION }}
            spiceai/spiceai:${{ env.REL_VERSION }}-${{ matrix.target_os }}-${{ matrix.target_arch }}
            ${{ env.LATEST_GHCR_TAG }}
            ${{ env.LATEST_DOCKERHUB_TAG }}
          # cache-from: type=gha
          # cache-to: type=gha,mode=max

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
