name: spiced_docker

on:
  push:
    tags:
      - v*

  workflow_dispatch:

jobs:
  build:
    name: Build Spice linux_amd64/linux_arm64 Docker image
    runs-on: ubuntu-latest-16-cores

    steps:
      - uses: actions/checkout@v4

      - name: Set REL_VERSION from version.txt
        run: python3 ./.github/scripts/get_release_version.py

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Package Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Sets latest tags for release
        run: |
          echo "LATEST_GHCR_TAG=ghcr.io/spiceai/spiceai:latest" >> $GITHUB_ENV
          echo "LATEST_DOCKERHUB_TAG=spiceai/spiceai:latest" >> $GITHUB_ENV

      - name: Build and push Docker images
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ startswith(github.ref, 'refs/tags/v') }}
          build-args: |
            REL_VERSION=${{ env.REL_VERSION }}
          tags: |
            ghcr.io/spiceai/spiceai:${{ env.REL_VERSION }}
            spiceai/spiceai:${{ env.REL_VERSION }}
            ${{ env.LATEST_GHCR_TAG }}
            ${{ env.LATEST_DOCKERHUB_TAG }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}