name: throughput tests

on:
  workflow_dispatch:
    inputs:
      spiced_commit:
        description: 'spiced build commit'
        required: false
        type: string
      spicepod_path:
        description: 'The spicepod file to test with'
        required: true
        type: string
      query_set:
        description: 'Query set'
        required: true
        default: 'tpch'
        type: choice
        options:
          - 'tpch'
          - 'tpcds'
          - 'clickbench'
      query_overrides:
        description: 'Query overrides'
        required: false
        type: choice
        default: ''
        options:
          - ''
          - 'sqlite'
          - 'postgresql'
          - 'mysql'
          - 'dremio'
          - 'odbc-athena'
          - 'duckdb'

jobs:
  run-throughput:
    name: Run throughput test
    runs-on: spiceai-runners
    steps:
      - uses: actions/checkout@v4

      - name: Run the testoperator
        uses: ./.github/actions/run-testoperator
        with:
          spiced_commit: ${{ github.event.inputs.spiced_commit }}
          spicepod_path: ${{ github.event.inputs.spicepod_path }}
          query_set: ${{ github.event.inputs.query_set }}
          query_overrides: ${{ github.event.inputs.query_overrides }}
          testoperator_mode: 'throughput'