name: testoperator dispatch

on:
  schedule:
    # Every day, at 0900 UTC (0200 PDT)
    - cron: '0 9 * * *'

  workflow_dispatch:
    inputs:
      spiced_commit:
        description: 'An optional commit hash to use for spiced'
        required: false
        type: string
      workflow_type:
        description: 'the workflow to execute (bench, throughput, load, etc)'
        required: true
        default: 'bench'
        type: choice
        options:
          - 'bench'
          - 'load'
          - 'throughput'
          - 'append'
          - 'http-consistency'
          - 'nas'
          - 'text-to-sql'
      update_snapshots:
        description: 'Update snapshots?'
        required: false
        type: boolean
        default: false
      scheduled:
        description: 'Run schedule?'
        required: false
        type: boolean
        default: false

jobs:
  dispatch-scheduled:
    name: Dispatch tests - Scheduled
    runs-on: spiceai-dev-runners
    if: ${{ github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.event.inputs.scheduled == 'true') }}
    strategy:
      fail-fast: false
      matrix:
        branch:
          - 'trunk'
          - 'release/1.10'
    concurrency:
      group: testoperator-dispatch-scheduled
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          ref: ${{ matrix.branch }}

      - name: Install MinIO
        uses: ./.github/actions/setup-minio
        with:
          minio_endpoint: ${{ secrets.TEST_MINIO_ENDPOINT }}
          minio_access_key: ${{ secrets.TEST_MINIO_ACCESS_KEY }}
          minio_secret_key: ${{ secrets.TEST_MINIO_SECRET_KEY }}

      - name: Setup spiced
        uses: ./.github/actions/setup-spiced
        id: setup-spiced
        with:
          ref: refs/heads/${{ matrix.branch }}

      - name: Display spiced commit
        run: echo "SPICED_COMMIT=${{ steps.setup-spiced.outputs.SPICED_COMMIT }}"

      - name: Build Testoperator
        uses: ./.github/actions/build-testoperator
        with:
          minio_endpoint: ${{ secrets.TEST_MINIO_ENDPOINT }}
          minio_access_key: ${{ secrets.TEST_MINIO_ACCESS_KEY }}
          minio_secret_key: ${{ secrets.TEST_MINIO_SECRET_KEY }}

      - name: Build spicepod validator
        uses: ./.github/actions/build-spicepod-validator
        with:
          minio_endpoint: ${{ secrets.TEST_MINIO_ENDPOINT }}
          minio_access_key: ${{ secrets.TEST_MINIO_ACCESS_KEY }}
          minio_secret_key: ${{ secrets.TEST_MINIO_SECRET_KEY }}

      - name: Validate spicepods - TPCH - SF1
        run: |
          for file in ./test/spicepods/tpch/sf1/**/*.yaml; do
            echo "Validating $file"
            ./target/release/spicepod-validator "$file"
          done

      - name: Validate spicepods - TPCDS - SF1
        run: |
          for file in ./test/spicepods/tpcds/sf1/**/*.yaml; do
            echo "Validating $file"
            ./target/release/spicepod-validator "$file"
          done

      - name: Validate spicepods - ClickBench - SF1
        run: |
          for file in ./test/spicepods/clickbench/sf1/**/*.yaml; do
            echo "Validating $file"
            ./target/release/spicepod-validator "$file"
          done

      - name: Validate spicepods - TPCH - SF100
        run: |
          for file in ./test/spicepods/tpch/sf100/**/*.yaml; do
            echo "Validating $file"
            ./target/release/spicepod-validator "$file"
          done

      - name: Dispatch Testoperator - Scheduled Bench - TPCH - SF1
        run: |
          testoperator dispatch ./tools/testoperator/dispatch/tpch/sf1 --workflow bench
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SPICED_COMMIT: ${{ steps.setup-spiced.outputs.SPICED_COMMIT }}
          WORKFLOW_COMMIT: ${{ matrix.branch }}

      - name: Dispatch Testoperator - Scheduled Bench - TPCDS
        run: |
          testoperator dispatch ./tools/testoperator/dispatch/tpcds/sf1 --workflow bench
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SPICED_COMMIT: ${{ steps.setup-spiced.outputs.SPICED_COMMIT }}
          WORKFLOW_COMMIT: ${{ matrix.branch }}

      - name: Dispatch Testoperator - Scheduled Bench - ClickBench
        run: |
          testoperator dispatch ./tools/testoperator/dispatch/clickbench/sf1 --workflow bench
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SPICED_COMMIT: ${{ steps.setup-spiced.outputs.SPICED_COMMIT }}
          WORKFLOW_COMMIT: ${{ matrix.branch }}

      - name: Dispatch Testoperator - Scheduled Append - TPCH - SF1
        run: |
          testoperator dispatch ./tools/testoperator/dispatch/tpch/sf1 --workflow append
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SPICED_COMMIT: ${{ steps.setup-spiced.outputs.SPICED_COMMIT }}
          WORKFLOW_COMMIT: ${{ matrix.branch }}

      - name: Dispatch Testoperator - Scheduled Bench - TPCH - SF100
        run: |
          testoperator dispatch ./tools/testoperator/dispatch/tpch/sf100 --workflow bench
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SPICED_COMMIT: ${{ steps.setup-spiced.outputs.SPICED_COMMIT }}
          WORKFLOW_COMMIT: ${{ matrix.branch }}

      - name: Dispatch Testoperator - Scheduled Text-to-SQL - TPCH
        run: |
          testoperator dispatch ./tools/testoperator/dispatch/text_to_sql --workflow text-to-sql
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SPICED_COMMIT: ${{ steps.setup-spiced.outputs.SPICED_COMMIT }}
          WORKFLOW_COMMIT: ${{ matrix.branch }}

  dispatch-input:
    name: Dispatch tests - Input
    runs-on: spiceai-dev-runners
    if: ${{ github.event_name == 'workflow_dispatch' }}
    concurrency:
      group: testoperator-dispatch-${{ github.event.ref }}
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Install MinIO
        uses: ./.github/actions/setup-minio
        with:
          minio_endpoint: ${{ secrets.TEST_MINIO_ENDPOINT }}
          minio_access_key: ${{ secrets.TEST_MINIO_ACCESS_KEY }}
          minio_secret_key: ${{ secrets.TEST_MINIO_SECRET_KEY }}

      - name: Setup spiced
        uses: ./.github/actions/setup-spiced
        id: setup-spiced
        with:
          spiced_commit: ${{ github.event.inputs.spiced_commit }}
          ref: ${{ github.event.ref }}

      - name: Display spiced commit
        run: echo "SPICED_COMMIT=${{ steps.setup-spiced.outputs.SPICED_COMMIT }}"

      - name: Build Testoperator
        uses: ./.github/actions/build-testoperator
        with:
          minio_endpoint: ${{ secrets.TEST_MINIO_ENDPOINT }}
          minio_access_key: ${{ secrets.TEST_MINIO_ACCESS_KEY }}
          minio_secret_key: ${{ secrets.TEST_MINIO_SECRET_KEY }}

      - name: Build spicepod validator
        uses: ./.github/actions/build-spicepod-validator
        with:
          minio_endpoint: ${{ secrets.TEST_MINIO_ENDPOINT }}
          minio_access_key: ${{ secrets.TEST_MINIO_ACCESS_KEY }}
          minio_secret_key: ${{ secrets.TEST_MINIO_SECRET_KEY }}

      - name: Validate spicepods - TPCH - SF1
        run: |
          for file in ./test/spicepods/tpch/sf1/**/*.yaml; do
            echo "Validating $file"
            spicepod-validator "$file"
          done

      - name: Validate spicepods - TPCDS - SF1
        run: |
          for file in ./test/spicepods/tpcds/sf1/**/*.yaml; do
            echo "Validating $file"
            spicepod-validator "$file"
          done

      - name: Validate spicepods - ClickBench - SF1
        run: |
          for file in ./test/spicepods/clickbench/sf1/**/*.yaml; do
            echo "Validating $file"
            spicepod-validator "$file"
          done

      - name: Validate spicepods - TPCH - SF100
        run: |
          for file in ./test/spicepods/tpch/sf100/**/*.yaml; do
            echo "Validating $file"
            spicepod-validator "$file"
          done

      - name: Dispatch Testoperator - ${{ github.event.inputs.workflow_type }} - TPCH - SF1
        run: |
          testoperator dispatch ./tools/testoperator/dispatch/tpch/sf1 \
            --workflow ${{ github.event.inputs.workflow_type }} \
            --update-snapshots ${{ github.event.inputs.update_snapshots }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SPICED_COMMIT: ${{ steps.setup-spiced.outputs.SPICED_COMMIT }}
          WORKFLOW_COMMIT: ${{ github.event.ref }}

      - name: Dispatch Testoperator - ${{ github.event.inputs.workflow_type }} - TPCDS
        run: |
          testoperator dispatch ./tools/testoperator/dispatch/tpcds/sf1 \
            --workflow ${{ github.event.inputs.workflow_type }} \
            --update-snapshots ${{ github.event.inputs.update_snapshots }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SPICED_COMMIT: ${{ steps.setup-spiced.outputs.SPICED_COMMIT }}
          WORKFLOW_COMMIT: ${{ github.event.ref }}

      - name: Dispatch Testoperator - ${{ github.event.inputs.workflow_type }} - ClickBench
        run: |
          testoperator dispatch ./tools/testoperator/dispatch/clickbench/sf1 \
            --workflow ${{ github.event.inputs.workflow_type }} \
            --update-snapshots ${{ github.event.inputs.update_snapshots }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SPICED_COMMIT: ${{ steps.setup-spiced.outputs.SPICED_COMMIT }}
          WORKFLOW_COMMIT: ${{ github.event.ref }}

      - name: Dispatch Testoperator - ${{ github.event.inputs.workflow_type }} - TPCH - SF100
        run: |
          testoperator dispatch ./tools/testoperator/dispatch/tpch/sf100 \
            --workflow ${{ github.event.inputs.workflow_type }} \
            --update-snapshots ${{ github.event.inputs.update_snapshots }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SPICED_COMMIT: ${{ steps.setup-spiced.outputs.SPICED_COMMIT }}
          WORKFLOW_COMMIT: ${{ github.event.ref }}

      - name: Dispatch Testoperator - ${{ github.event.inputs.workflow_type }} - Text to SQL
        run: |
          testoperator dispatch ./tools/testoperator/dispatch/text_to_sql \
            --workflow ${{ github.event.inputs.workflow_type }} \
            --update-snapshots ${{ github.event.inputs.update_snapshots }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SPICED_COMMIT: ${{ steps.setup-spiced.outputs.SPICED_COMMIT }}
          WORKFLOW_COMMIT: ${{ github.event.ref }}
