name: testoperator dispatch

on:
  workflow_dispatch:
    inputs:
      test_files_path:
        description: 'path to load test files to dispatch'
        required: true
        type: string
      workflow_type:
        description: 'the workflow to execute (bench, throughput, load, etc)'
        required: true
        default: 'bench'
        type: choice
        options:
          - 'bench'
          - 'load'
          - 'throughput'

jobs:
  dispatch-tests:
    name: Dispatch tests
    runs-on: spiceai-runners
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 10
      
      - name: Setup spiced
        uses: ./.github/actions/setup-spiced
        id: setup-spiced
      
      - name: Display spiced commit
        run: echo "SPICED_COMMIT=${{ steps.setup-spiced.outputs.SPICED_COMMIT }}"