CREATE INDEX idx_store_sales_sold_date_item_customer ON store_sales (ss_sold_date_sk, ss_item_sk, ss_customer_sk);
CREATE INDEX idx_store_sales_item_customer_store ON store_sales (ss_item_sk, ss_customer_sk, ss_store_sk);
CREATE INDEX idx_date_dim_date_sk ON date_dim (d_date_sk);
CREATE INDEX idx_date_dim_date ON date_dim (d_date);
CREATE INDEX idx_item_item_sk_category ON item (i_item_sk, i_category_id);
CREATE INDEX idx_item_category_brand ON item (i_category_id, i_brand_id);
CREATE INDEX idx_store_store_sk_name ON store (s_store_sk, s_store_name);
CREATE INDEX idx_customer_demographics_demo_sk ON customer_demographics (cd_demo_sk);
CREATE INDEX idx_household_demographics_demo_sk ON household_demographics (hd_demo_sk);
CREATE INDEX idx_call_center_call_center_sk_country ON call_center (cc_call_center_sk, cc_country);
CREATE INDEX idx_catalog_sales_sold_date_item ON catalog_sales (cs_sold_date_sk, cs_item_sk);
CREATE INDEX idx_catalog_sales_item ON catalog_sales (cs_item_sk);
CREATE INDEX idx_ship_mode_ship_mode_sk ON ship_mode (sm_ship_mode_sk);
CREATE INDEX idx_warehouse_warehouse_sk ON warehouse (w_warehouse_sk);
CREATE INDEX idx_time_dim_time_sk ON time_dim (t_time_sk);
CREATE INDEX idx_time_dim_time_id ON time_dim (t_time_id);
CREATE INDEX idx_store_sales_customer ON store_sales (ss_customer_sk);
CREATE INDEX idx_store_sales_sold_date ON store_sales (ss_sold_date_sk);
CREATE INDEX idx_catalog_sales_customer ON catalog_sales (cs_ship_customer_sk);
CREATE INDEX idx_catalog_sales_sold_date ON catalog_sales (cs_sold_date_sk);
CREATE INDEX idx_web_sales_customer ON web_sales (ws_bill_customer_sk);
CREATE INDEX idx_web_sales_sold_date ON web_sales (ws_sold_date_sk);
CREATE INDEX idx_customer_address_county ON customer_address (ca_county);
CREATE INDEX idx_customer_name ON customer (c_last_name, c_first_name);
CREATE INDEX idx_date_dim ON date_dim (d_year);
CREATE INDEX idx_store_sales_customer_sold_date ON store_sales (ss_customer_sk, ss_sold_date_sk);
CREATE INDEX idx_catalog_sales_customer_bill ON catalog_sales (cs_bill_customer_sk, cs_sold_date_sk);
CREATE INDEX idx_web_sales_customer_bill ON web_sales (ws_bill_customer_sk, ws_sold_date_sk);
CREATE INDEX idx_store_returns_returned_date_store ON public.store_returns (sr_returned_date_sk, sr_store_sk);
CREATE INDEX idx_catalog_returns_returned_date_catalog_page ON public.catalog_returns (cr_returned_date_sk, cr_catalog_page_sk);
CREATE INDEX idx_store_sales_sold_date_store ON public.store_sales (ss_sold_date_sk, ss_store_sk);
CREATE INDEX idx_catalog_sales_sold_date_catalog_page ON public.catalog_sales (cs_sold_date_sk, cs_catalog_page_sk);
CREATE INDEX idx_web_sales_sold_date_web_site ON public.web_sales (ws_sold_date_sk, ws_web_site_sk);