[package]
name = "connector-gcs"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license-file.workspace = true
description = "Google Cloud Storage (GCS) data connector for Spice.ai runtime"

[dependencies]
linkme.workspace = true
object_store = { workspace = true }
runtime = { path = "../../runtime" }
snafu.workspace = true
tokio.workspace = true
url.workspace = true

[dev-dependencies]
app = { path = "../../app" }
runtime-secrets = { path = "../../runtime-secrets", default-features = false }
secrecy.workspace = true
tokio = { workspace = true, features = ["sync"] }

[lints]
workspace = true
