name: Installs the cc toolchain
description: 'composite action'

runs:
  using: 'composite'
  steps:
    - name: Install cc
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake pkg-config libssl-dev unixodbc unixodbc-dev protobuf-compiler